### ISSUE TITLE
Document Twins service 

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#1000]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
[Official Documentation section](https://mainflux.readthedocs.io/) is missing for Twins service 

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by drasko** [comment]
Closed via https://github.com/mainflux/docs/pull/32
