### ISSUE TITLE
Password change on GUI fails

### ISSUE THREAD

**Issue by Thalhammer** [absmach/magistrala#1012]
**BUG REPORT**

1. What were you trying to achieve?
Use the builtin UI to change the current users password.

2. What are the expected results?
API returns valid HTTP code, password gets changed.

3. What are the received results?
API returns "405 Not allowed" and old password is preserved.

4. What are the steps to reproduce the issue?
* Follow getting started tutorial (i.e. git clone master, make run)
* Create example user with cli
* Login with example user
* Try to change password

5. In what environment did you encounter the issue?
Ubuntu 18.04.3 LTS (x64) virtualized using LXC on a Proxmox host.
But it should fail on any docker installation.

6. Additional information you deem important:
In case it matters, the old password was test1234# the new password followed the same rules (lower case + numbers + special)

**Comment by manuio** [comment]
@Thalhammer We recently moved the UI to a new repository (https://github.com/mainflux/ui). There you can also find a specific docker-compose + nginx config. 

I would also recommend you to create your user from the UI instead of using the CLI. If your problems persist, create a new issue there.
