### ISSUE TITLE
Update SDK to use API keys

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#1015]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
   Update SDK to use [API keys](https://github.com/mainflux/mainflux/issues/932) instead of fetching user JWT (requiring username and password).
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by drasko** [comment]
@manuio what's the status of this?

**Comment by manuio** [comment]
@drasko pending

**Comment by drasko** [comment]
This should be working in the current implementation, as key type is transparent to the SDK (weather we provide login key or API key, it should work).

**Comment by fbugarski** [comment]
This works, we can close this issue.
