### ISSUE TITLE
Wrapping MQTT client

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#1034]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Maybe we should consider wrapping MQTT client with few methods like Connect(srv.opts) Pub() Sub() Close() etc...and hide paho impl. I saw the same code at least 10 times (and it's not short, we will need it in Twins, e2e testing, etc...all places where we use MQTT).

Same for NATS, extend our MessagePublisher interface and hide nats impl. Consider adding multiple publishers' as an option, so I can pass the engine I use (kafka or NATS). The idea is to use our API in Core and hide the fact that we use nats or Kafka or even MQTT, make abstraction

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
nice-to-have

**Comment by drasko** [comment]
@nmarcetic you can probably take this one as a part of E2E test implementation

**Comment by nmarcetic** [comment]
@drasko I can take it after. I would prefer to not mix it with e2e, it's not related at all. e2e will be huge work, separated from the rest of the code (no changes in core, but will be part of the core ofc).
I would also join @dusanb94 after e2e rather than start with this, as we planed.

**Comment by drasko** [comment]
> Maybe we should consider wrapping MQTT client with few methods like Connect(srv.opts) Pub() Sub() Close() etc...and hide paho impl. I saw the same code at least 10 times (and it's not short, we will need it in Twins, e2e testing, etc...all places where we use MQTT).

Most of this task has been finished by adding messaging interfaces: https://github.com/mainflux/mainflux/tree/master/pkg/messaging/mqtt

What is left is to check where this is used and replace calls to Paho lib with interfaces.
