### ISSUE TITLE
Can't Proxy pass to mainflux mqtt adapter over WS in Nginx

### ISSUE THREAD

**Issue by longlnk** [absmach/magistrala#1037]
I can't connect mqtt over WS in Nginx use verne cluster
![image](https://user-images.githubusercontent.com/15074179/74662731-0d35da00-51cd-11ea-91fc-13471090f598.png)

![image](https://user-images.githubusercontent.com/15074179/74662754-1b83f600-51cd-11ea-8a4e-51ef3f5f86f6.png)

I only can connect mqtt over WS in mqtt in Mqtt-adapter
![image](https://user-images.githubusercontent.com/15074179/74662842-4ec68500-51cd-11ea-8243-f90bc29b8991.png)

Please help me!
--

**Comment by chinhnguyentrung** [comment]
Address WS Verne: ws://ip:port/mqtt -> proxy pass nginx: proxy_pass http://mqtt_ws_cluster/mqtt;

**Comment by longlnk** [comment]
> Address WS Verne: ws://ip:port/mqtt -> proxy pass nginx: proxy_pass http://mqtt_ws_cluster/mqtt;

Hi,

My nginx'config current, Can you help me?, because location is /mqtt/ based mainflux's nginx

![image](https://user-images.githubusercontent.com/15074179/74723692-956bbc00-526d-11ea-9116-9d0801999fc3.png)

**Comment by blokovi** [comment]
As @chinhnguyentrung already said, try edit this last line like this:
`proxy_pass http://mqtt_ws_cluster/mqtt;` 
because Verne accepts ws connection on `/mqtt` path

**Comment by longlnk** [comment]
Hi all,
It worked, I edit:
        # Proxy pass to mainflux-mqtt-adapter over WS
        location /mqtt {
            include snippets/proxy-headers.conf;
            include snippets/ws-upgrade.conf;
            proxy_pass http://mqtt_ws_cluster/mqtt;
        }
localtion **/mqtt** not /mqtt/

And add environment on Nginx container:
DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
DOCKER_VERNEMQ_PLUGINS__MFX_AUTH: "on"
DOCKER_VERNEMQ_PLUGINS__MFX_AUTH__PATH: /mainflux/_build/default
DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: debug

Thanks all!
