### ISSUE TITLE
MF_AUTH_URL vs MF_AUTHN_URL

### ISSUE THREAD

**Issue by jdevoo** [absmach/magistrala#1041]
1. I was trying to run mainflux/cli provision test against newly pulled images for 0.10.0 and an older docker-compose.yaml file

2. I was expecting the user and 2 things to be created

3. Instead I kept receiving unauthorized access (`provision test` does not tell which step fails)

4. I had MF_AUTHN_URL in my things section of the docker-compose.yaml file instead of MF_AUTH_URL *without* N

5. My environment: docker for windows 19.03.5

To locate this issue, I started with ngninx logs, then things logs and finally authn which would not show a trace upon things creation. That lead me to check the URL until I noticed the missing N. This variable is missing from the things microservice README.md page.

**Comment by jdevoo** [comment]
Just to add - using the latest mainflux/cli docker image worked on my windows machine where I ran `mainflux/cli provision test` but I still have problems with the cli binary from the release on my ubuntu machine. Docker image worked though.

**Comment by drasko** [comment]
Maybe CLI was changed, but not rebuilt and republished. Something to take a look at.
