### ISSUE TITLE
"invalid argument passed" during test provision

### ISSUE THREAD

**Issue by cowboylux** [absmach/magistrala#1044]
I'm trying to make a test provision with command:
**mainflux-cli provision test**
and get the following error:
**invalid argument passed**

**Comment by nmarcetic** [comment]
@cowboylux how did you install mainflux-cli ? 

You must re-build it, we made some small changes, just do `make cli` from `<project_root>`, which will build mainflux-cli in `<project_root>/build` folder. 
Later if you want you can copy `mainflux-cli` to your `$GOBIN` or just use it from `<project_root>/build` directory as [discrabed in doc](https://mainflux.readthedocs.io/en/latest/cli/)

**Comment by cowboylux** [comment]
Can I download a binaries somewhere?

**Comment by nmarcetic** [comment]
@cowboylux Unfortunately not, because it's not a release and we don't publish the latest artifacts. 
Do you have any blockers to do a build?
