### ISSUE TITLE
Websocket connection doesn't receive Things info

### ISSUE THREAD

**Issue by smrgrg94** [absmach/magistrala#1047]
I am trying to use Mainflux to send data (non- SenML) from my devices to another application.
Publishing data from devices via http and listening to messages via websocket.

I don't see any thing related information (id, name) when I receive the payload on websocket.
I don't want to put device name on the payload as it won't scale well when I use multiple devices. (I don't want to change firmware code)

It's a must-have feature as I won't be able to classify payloads without device info attached to it. I am running the latest release 0.10.0 right now.

Note: Can't use writer/reader service as my data is not in SenML format

**Comment by nmarcetic** [comment]
@smrgrg94 I understand your requirement, but unfortunately, it will make more cons than pros into the Mainflux core, which aims to be lean, simple and fast. Adding additional info in messaging except payload will increase message size and many things will be affected with this (latency, bandwidth, etc...). 

Your requirements maybe can be accomplished without changing your fw code, using channels per device or subtopic per device? So device A can publish on `channels/<channel_id>/messages/A` and device B on `channels/<channel_id>/messages/B`  you can put whatever you want as a subtopic and you use as many levels as you want. 

I don't get this 
```
I don't want to put the device name on the payload as it won't scale well when I use multiple devices. (I don't want to change firmware code)
```

**Comment by smrgrg94** [comment]
@nmarcetic 
In the future, I want to use the same fw code for all my devices, so that I can use the same binary to flash all my devices. I am planning to use a bootstarpping service so that I don't have to update the Things token while creating my binary as well.

```
Your requirements maybe can be accomplished without changing your fw code, using channels per device or subtopic per device? So device A can publish on `channels/<channel_id>/messages/A` and device B on `channels/<channel_id>/messages/B` you can put whatever you want as a subtopic and you use as many levels as you want.
 ```

I tried this work-around, I have to create a separate ws connection to listen to each device. A connection to `channels/<channel_id>/messages/A` to listen to device A, another connection to `channels/<channel_id>/messages/B` to listen to device B, etc..

Which is okay, But I will have to update the binary for each device with a separate url as well. It's an easy task but still cumbersome while working with say 100+ devices. :P

**Comment by nmarcetic** [comment]
@smrgrg94  ` I have to create a separate ws connection to listen to each device` You can just subscribe to `#` and get all messages from one connection so connection `channels/<channel_id>/messages/#` will get messages published from both A and B its a joker topic.

`But I will have to update the binary for each device with a separate url as well` 
Not really, you can put this in bootstrap config ;) We do this also, we provision 2 channels for each device data and control and save this in bootstrap configuration when device pull its config from bootstrap it reads values for data and control channels and starts publishing/listening so it's generic not hardcoded in binary (plus can be changed by uploading new config in bootstrap and configure your device to pull config on power-up).

**Comment by nmarcetic** [comment]
@smrgrg94  ` I have to create a separate ws connection to listen to each device` You can just subscribe to `#` and get all messages from one connection so connection `channels/<channel_id>/messages/#` will get messages published from both A and B its a joker topic.

`But I will have to update the binary for each device with a separate url as well` 
Not really, you can put this in bootstrap config ;) We do this also, we provision 2 channels for each device data and control and save this in bootstrap configuration when device pull its config from bootstrap it reads values for data and control channels and starts publishing/listening so it's generic not hardcoded in binary (plus can be changed by uploading new config in bootstrap and configure your device to pull config on power-up).

**Comment by smrgrg94** [comment]
@nmarcetic Thanks for the info on bootstapping. I will try that.

I subscribed to the subtopics with * wildcard as I am not using mqtt over my ws connection.
But in this case too, the messages I get over the connection again don't have information of the subtopic it originated from. I am planning to send device name/id in the message payload and configure the device name variable as well via bootstrapping.

**Comment by nmarcetic** [comment]
@smrgrg94 I think this is the best for your use case.
```
. I am planning to send device name/id in the message payload and configure the device name variable as well via bootstrapping.
```
Np, feel free to ping for help. You can also use [Gitter](https://gitter.im/Mainflux/mainflux) for community support.

**Comment by drasko** [comment]
@smrgrg94 @nmarcetic can this one be closed or there is some other work left here?
