### ISSUE TITLE
{"level":"warn","message":"Failed to tranform received message: json: cannot unmarshal object into Go value of type []senml.Record"

### ISSUE THREAD

**Issue by opotmans** [absmach/magistrala#1048]
**BUG REPORT**

1. What were you trying to achieve?
I have installed the mainflux infrastructure including influxdb influx-writer and grafana.
I use a raspberry pi with sense hat and I send to mainflux the information captured by sense hat via mqtt after the definition of a thing (the raspberry), a channel and the authorization of the thing to use the channel.

the message sent by mqtt (mosquitto on raspberry) to mainflux is :
{"temperature":33.06,"humidity":35.29,"pressure":977.87}

it works because I see this result on the debugging:
mainflux-mqtt   | {"level":30,"time":1582808844856,"msg":"published","pid":1,"hostname":"d772a4c824ec","client":{"id":"mqtt_18ae3c3.e7fdec4"},"message":{"topic":"channels/e36f293a-f61b-4d33-89eb-9e982b0264b7/messages","qos":0,"retain":false},"v":1}

It seems that the message sent by mqtt is not stored in the influx db. With grafana, I didn't see anything.

if I analyze the logs of influx-writer, I have this message
{"level":"warn","message":"Failed to tranform received message: json: cannot unmarshal object into Go value of type []senml.Record","ts":"...."

it seems that this  is the writer.go file which generates that warning and I suspect that the message is not written in db

2. What are the expected results?

The transformation is correctly made. I would like to know if the message sent by mqtt on the raspberry is in the correct format and can be transformed.
If the answer is yes, the warning is just informal and the data is stored in the db?
if yes, which kind of request should I use in grafana to extract the data

3. What are the received results?
A chart on grafana tool with the humidity, the pressure and the temperature

4. What are the steps to reproduce the issue?
see above
5. In what environment did you encounter the issue?
ubuntu linux 19.04 + docker + mosquitto on raspberry to push the message.

6. Additional information you deem important:
just a mistyping error in the message just add a "s" to transform :-)

**Comment by manuio** [comment]
Hi @opotmans this is because writers expect SenML format and `{"temperature":33.06,"humidity":35.29,"pressure":977.87}` is not valid. 
You can use something like this: `[{"n": "temperature", "t": 0 , "v": 33.06}, {"n":"humidity", "t": 0}, {"n": "pressure",  "t": 0, "v": 977.87}]`

**Comment by opotmans** [comment]
Sorry for the delay of my answer
Meanwhile, I reached the same conclusion by deduction and effectively this works!
thanks for the information . 👍
