### ISSUE TITLE
DELETE client returns 500 internal server error if ID is wrong

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#106]
When trying to DELETE a client with wrong or empty ID the manager returns "500 internal server error". Should be "403 Forbidden".

To reproduce:
`curl -s -S -i --noproxy localhost -X DELETE -H "Content-Type: application/senml+json" -H "Authorization: <user_token>" localhost:8180/clients/`
`curl -s -S -i --noproxy localhost -X DELETE -H "Content-Type: application/senml+json" -H "Authorization: <user_token>" localhost:8180/clients/<inexistent_ID>`

**Comment by mijicd** [comment]
@manuIO the bug specification is not quite precise. The problem you're encountering is not related to non-existent identifiers. You can verify this by using any kind of UUID as request parameter (that does not exist), and the service will respond with status 204. However, using an *invalid UUID* will cause the error you've described.
