### ISSUE TITLE
Impossible to read things messages

### ISSUE THREAD

**Issue by bnjroos** [absmach/magistrala#1063]
1. What were you trying to achieve?
Read things messages

2. What are the expected results?
Get the sent messages
3. What are the received results?
Can't read message via cli
```
{
  "limit": 0,
  "offset": 0,
  "total": 0
}
```
or ui
`failed to read messages error 200
`
4. What are the steps to reproduce the issue?
docker-compose after using git clone and adding UI to docker compose
Send messages via mqtt

```
mainflux-mqtt   | {"level":"info","message":"Publish - client ID Arduino-00000945 to the topic: channels/e8abc986-e816-4d27-9e9a-b631b498c536/messages","ts":"2020-03-06T11:08:25.92475706Z"}
mainflux-mqtt   | {"level":"info","message":"AuthPublish - client ID: Arduino-00000945 topic: channels/e8abc986-e816-4d27-9e9a-b631b498c536/messages","ts":"2020-03-06T11:08:42.155098355Z"}
mainflux-things | {"level":"info","message":"Method can_access_by_id for channel e8abc986-e816-4d27-9e9a-b631b498c536 and thing 259dd3bf-a57f-409d-98b4-b5e0a569d9b3 took 2.434783ms to complete without errors.","ts":"2020-03-06T11:08:42.158837083Z"}
```

5. In what environment did you encounter the issue?
docker on ubuntu 18.04

**Comment by manuio** [comment]
@bnjroos if you get this:
```
{
  "limit": 0,
  "offset": 0,
  "total": 0
}
```
it means that you don't have stored messages. Which writer and reader are you using?

**Comment by bnjroos** [comment]
I am using influxdb writer and reader. Any idea?

**Comment by manuio** [comment]
@bnjroos Looks like your database is empty.
Please, can you try to send messages over HTTP with the CLI: `mainflux-cli messages send <channel_id> '[{"bn":"Dev1","n":"temp","v":20}, {"n":"hum","v":40}, {"bn":"Dev2", "n":"temp","v":20}, {"n":"hum","v":40}]' <thing_auth_token>`

**Comment by bnjroos** [comment]
Same thing, I get OK as response but while trying to read it is still empty.

**Comment by manuio** [comment]
@bnjroos Please, can you copy paste here the docker logs of `influxdb-reader` and `influxdb-writer`?

**Comment by bnjroos** [comment]
Ok manuio, thank you for the help, found the issue, had to follow the SenML format, all good now. Thank you for the fast respond.
