### ISSUE TITLE
Adapters should insert timestamp in the case it is missing

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#1069]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
SenML message can be sent without timestamp, because:
- Low-power devices might not have RTC
- Clocks are not synchronized via NTP
- Some other reason

Protocol adapters - who are the first recepients of the message - should insert a timestamp in the case it is missing.

Even more - we should consider of an another fiels in Mainflux `Message{}` like `received`.

Writers will then use this timestamp, and this will help with implementing queue and workers in https://github.com/mainflux/mainflux/issues/1068 and assuring that messages are written in order, although processed by several parallel writers.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must-have

**Comment by chombium** [comment]
Having small battery operated sensors without RTC is one of the reasons why I use custom adapters with which I enhance the received message or even repackage it as SenML.

Where are we going to get the time for the timestamps from? Time synchronization between all Mainflux services would be nice to have feature.
I guess simply reading the time from the adapter's container would be a good start. We can add a `time provider service` and time synchronization to all services later.

@mainflux/contributors wdyt?

**Comment by drasko** [comment]
@chombium I think as you mentioned - from an underlying Linux system. Containers should be deployed on a NTP synced machines (if even higher precision is needed [PTP](https://www.masterclock.com/support/library/network-timing-ntp-vs-ptp) can be used with manchines that support it).

When you mentioned `time provider` service, you meant one API that will provide you a current timestamp? I think this will introduce unnecessary delay and incorrectness.

**Comment by chombium** [comment]
@drasko yes, I thought of one API with different backends for getting the correct time and provide it to the MF services, but I agree that that would introduce delays.

Time syncing on the OS level for containers and time syncing between pods in Kubernetes would be the most reliable thing to do. I guess this is another topic for the deployment guide ;)

**Comment by chombium** [comment]
I'll take a look at this one.

**Comment by manuio** [comment]
@chombium great, thank you! But it would be easier for you to wait for this one: https://github.com/mainflux/mainflux/pull/1080

**Comment by chombium** [comment]
@manuio there are some things to add to our docker compose files and I guess to the Helm chart to ensure the time sync between the services. The other part about the adapters I will try to solve it on a central place as some kind of "middleware" which will get the decoded message payload, check it and adjust it. I will start and follow what's happening in #1080

**Comment by drasko** [comment]
@chombium this is fantastic, but take care that change would have to be made practically in every adapter, as we need to change `Message{}` struct to add a `timestamp` field which adapters will set.

We do not have to do it at the same time in all adapters, but that is the final destination.

**Comment by chombium** [comment]
@drasko I completely agree. I will do it once and have to find the appropriate place to attach the code

**Comment by manuio** [comment]
@drasko if it's done in the new generic  publisher no need to duplicate code in the adapters

**Comment by drasko** [comment]
@manuio this is true. @chombium please follow the work here: https://github.com/mainflux/mainflux/pull/1080 on unification of adapter's publishing part. Should be merged soon.

**Comment by manuio** [comment]
@chombium The Publisher is ready here: https://github.com/mainflux/mainflux/blob/master/broker/nats.go

**Comment by manuio** [comment]
@chombium I added received timestamp in adapters. 
You can continue with the synchronization here: https://github.com/mainflux/mainflux/issues/1107
