### ISSUE TITLE
Add MQTT forwarder

### ISSUE THREAD

**Issue by lizhanglz** [absmach/magistrala#1079]
**BUG REPORT**

1. What were you trying to achieve?
I am trying to publish messages using HTTP or Websocket so a device using MQTT subscribe can receive messages.

2. What are the expected results?
When publishing messages using HTTP or Websocket over a channel, a device subscribe to that channel using MQTT should receive messages.

3. What are the received results?
MQTT sub are not receiving messages published by HTTP or Websocket.

4. What are the steps to reproduce the issue?
- Create two things and a channel and connect both things to that channel.
- Subscribe to the channel using thing-1-id and thing-1-key. 
- Publish a message using thing-2-id and thing-2-key over the channel using HTTP or Websocket

5. In what environment did you encounter the issue?
- Latest Docker images deployed using docker-compose.
- Tried everything on one Linux machine, or separate pub and sub into two Linux machines.

6. Additional information you deem important:
- MQTT sub receives MQTT pub without any issues.
- Websocket receives HTTP, Websocket and MQTT published messages without any issues.
- Subscribe using mosquitto
```mosquitto_sub -u 7287b133-942c-45f1-a19f-ff77167db47b -P ebd001f4-a6ec-4c03-b0fb-6f78bd16608c -t channels/434b9b66-94be-4f99-913d-6de7bb1c2008/messages/ct/application_senml-json -h localhost```
- Subscribe using Paho
Created a Java program using Paho library to subscribe to the same channel.
- Publish using CURL 
```curl -s -S -X POST -H "Content-Type: application/senml+json" -H "Authorization: 0250e814-deca-4cca-8201-9ab535ed32a9" http://localhost/http/channels/434b9b66-94be-4f99-913d-6de7bb1c2008/messages -d '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]'```
- Publish using CLI
```docker run -it --rm mainflux/cli -m http://<host ip> messages send 434b9b66-94be-4f99-913d-6de7bb1c2008 '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]' 0250e814-deca-4cca-8201-9ab535ed32a9```
- Publish using Websocket
Created a JS page and published same message using Websocket.

**Comment by nmarcetic** [comment]
@lizhanglz I am confirming the issue. We are currently working on [mproxy](https://github.com/mainflux/mproxy) implementation and we are releasing feature by feature. Right now adding [MQTT over WS support](https://github.com/mainflux/mproxy/pull/9) and next one is a multi-protocol bridge, that you reported.
If you need multi-protocol you should use [official release](https://github.com/mainflux/mproxy) not the latest (code or Docker images), where we usually break things under rapid development. 
We are expecting multi-protocol support to be done next week. Stay tuned and keep this issue opened I will let you know. 
Thanks for reporting.

**Comment by lizhanglz** [comment]
@nmarcetic Thank you for your prompt response. I changed to pull 0.10.0 tag and rewound some of the docker-compose file env settings. Now everything is back to normal. Can't wait for the new mproxy features. Thank you for your great work!

**Comment by drasko** [comment]
@manuio please do not close this one, it should be used for addition of the NATS subscriber for cross-protocol comm.

**Comment by drasko** [comment]
@dusanb94 I have sketched the proposed solution in https://github.com/mainflux/mainflux/pull/1155 on a separate branch [relay](https://github.com/mainflux/mainflux/tree/relay).

It includes change of messaging interfaces and addition of MQTT messaging interfaces so that relay can implement PUB/SUB.

Relaying is done in a separate goroutine where relay functionality of MQTT adapter at the same time subscribes to NATS (via messaging `Subscriber` interface implementation for NATS) and then publishes to VerneMQ (via messaging `Publisher` interface implementation for MQTT).

Please note thhat relay (forwarder) idea should be generalized, as we will have similar need for CoAP and potentially other bidirectional protocols.
