### ISSUE TITLE
Duplicate variable in entrypoint of nginx?

### ISSUE THREAD

**Issue by jonathandreyer** [absmach/magistrala#1089]
In the script `entrypoint.sh` of nginx (Here: https://github.com/mainflux/mainflux/blob/70955d1937759a634df1b2f00f301bd7637b0563/docker/nginx/entrypoint.sh#L15), is it normal that variable `${MF_THINGS_HTTP_PORT}` is indicated twice?

**Comment by drasko** [comment]
Looks like a bug to me.

**Comment by jonathandreyer** [comment]
@manuio From what I understand, it will be fix when the #1066 will be closed. Right?

**Comment by manuio** [comment]
@jonathandreyer right!
