### ISSUE TITLE
Unify publisher and subscriber mocks

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#1092]
Many service implement their own publisher or subscriber mock. Since now we have a new broker package mocks should be defined there and used in all tests.

**Comment by manuio** [comment]
I'm not sure about this one... There are only mocks for HTTP and Twins.
What do you think @drasko ?

**Comment by drasko** [comment]
I do not see some big need for now. Maybe later.

**Comment by manuio** [comment]
Closing this one for now
