### ISSUE TITLE
Connection refused while mainflucx-cli provision test

### ISSUE THREAD

**Issue by nishchay3** [absmach/magistrala#1095]
I am trying to run `mainflucx-cli provision test` after make run mainflux in another ssh putty connection. It is giving an error of

`Post http://localhost/users: dial tcp 127.0.0.1:80: connect: connection refused`

My Linux Server:
`Operating System: Red Hat Enterprise Linux`
`Kernel: Linux 3.10.0-957.el7.x86_64`
`Architecture: x86-64`

Wget:
`wget 127.0.0.1`
`--2020-04-02 09:52:01--  http://127.0.0.1/`
`Connecting to 127.0.0.1:80... failed: Connection refused.`

Traceroute:
`traceroute 127.0.0.1`
`traceroute to 127.0.0.1 (127.0.0.1), 30 hops max, 60 byte packets`
`1  localhost (127.0.0.1)  0.062 ms  0.029 ms  0.027 ms`

Ping:
`ping 127.0.0.1`
`PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.`
`^C`
`--- 127.0.0.1 ping statistics ---`
`87 packets transmitted, 0 received, 100% packet loss, time 86006ms`

Can anyone please help with configuring this.

**Comment by manuio** [comment]
@nishchay3 What it means `after make run mainflux in another ssh putty `? Can you first try running mainflux locally? 
If mainflux is not running in `localhost` you can set the URL with `--mainflux-url` flag.

**Comment by nishchay3** [comment]
> @nishchay3 What it means `after make run mainflux in another ssh putty `? Can you first try running mainflux locally?
> If mainflux is not running in `localhost` you can set the URL with `--mainflux-url` flag.

Can you please guide me how to check if it running locally.
And `in another ssh putty` means that I ran on same Linux Server in two different shared putty connections.

**Comment by manuio** [comment]
@nishchay3 https://mainflux.readthedocs.io/en/latest/getting-started/#step-1-run-the-system

**Comment by drasko** [comment]
Please read the manual and ask questions on Gitter. This is not the place for these kind of questions.
