### ISSUE TITLE
Can't provision on fresh install

### ISSUE THREAD

**Issue by tomyalmaarif** [absmach/magistrala#1100]
**BUG REPORT**

1. What were you trying to achieve?
Fresh installation

2. What are the expected results?
Failed for provision or create user

3. What are the received results?
`[root@localhost ~]# ./cli provision test

invalid argument passed`
`[root@localhost ~]# ./cli users create test@example.com 1234

invalid argument passed`

Log
`mainflux-users  | {"level":"warn","message":"Failed to decode user credentials: malformed entity specification","ts":"2020-04-05T21:47:16.724458979Z"}`

4. What are the steps to reproduce the issue?
Fresh install

5. In what environment did you encounter the issue?
Debian 10, Ubuntu 18.04, Centos 7
Docker 18.09.9
Docker-compose 1.24.1
CLI 0.10.0

6. Additional information you deem important:

**Comment by drasko** [comment]
@tomyalmaarif I think size of the password has been augmented and minimum is limited to 6 or 8 (I do not remember out of the head).

Please follow the example here: https://mainflux.readthedocs.io/en/latest/provisioning/#account-creation

**Comment by tomyalmaarif** [comment]
What I mean is:

If I'm using compiled mainflux-cli 0.10.0 the error is occured, even if using provision test
```
[root@localhost ~]# ./mainflux-cli_v0.10.0_linux-amd64 provision test

invalid argument passed

```

If I'm compiled from source, it no problem.

```
[root@localhost mainflux]# ./build/mainflux-cli provision test

{
  "Email": "wizardly_keller@email.com",
  "Metadata": null,
  "Password": "12345678"
}

```

So I'm suggesting to upload new compiled mainflux-cli to release.

**Comment by drasko** [comment]
Yes, makes sense.

**Comment by luixal** [comment]
I'm hitting the same issue with a fresh install, not only with `./mainflux-cli provision test` but also with `users create`, `users token`...

Thing is, maybe is not the CLI tool. I'm also getting errors when trying to provision user throught http queries. I can create a new user:

```
curl -s -S -i --cacert docker/ssl/certs/ca.crt -X POST -H "Content-Type: application/json" https://localhost/users -d '{"email":"luixal@jeje.com", "password":"123456789ee9"}'

HTTP/2 201 
server: nginx/1.16.0
date: Mon, 06 Apr 2020 12:08:20 GMT
content-type: application/json
content-length: 0
strict-transport-security: max-age=63072000; includeSubdomains
x-frame-options: DENY
x-content-type-options: nosniff
access-control-allow-origin: *
access-control-allow-methods: *
access-control-allow-headers: *
```
logs from docker seem right:

```
mainflux-users  | {"level":"info","message":"Method register for user luixal@jeje.com took 68.19924ms to complete without errors.","ts":"2020-04-06T12:08:20.796795411Z"}
```
but then, when I try to get the token:

```
curl -s -S -i --cacert docker/ssl/certs/ca.crt -X POST -H "Content-Type: application/json" https://localhost/tokens -d '{"email":"luixal@jeje.com", "password":"123456789ee9"}'

HTTP/2 400 
server: nginx/1.16.0
date: Mon, 06 Apr 2020 12:10:57 GMT
content-type: application/json
content-length: 30

{"error":"non-existent user"}
```

logs are according to the error:

```
mainflux-users  | {"level":"warn","message":"Method login for user luixal@jeje.com took 65.098026ms to complete with error: non-existent user : rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8181: connect: connection refused\".","ts":"2020-04-06T12:10:57.149317733Z"}
```

If I try to re-create the user, I got the error telling me "Save user to DB failed" and logs printing it's due to user already existing, which is right.

No idea how to follow from here :(

PS: I guess this error I see in the logs may be related to this:
```
mainflux-users  | {"level":"warn","message":"Failed to decode user credentials: malformed entity specification","ts":"2020-04-06T12:04:20.207854114Z"}
```

**Comment by manuio** [comment]
@luixal can you please update your master and try building again with `make cli`?  
I just tried and all works for me.
