### ISSUE TITLE
Add Time synchronization between all Mainflux services 

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#1107]
Description from @chombium :
Having small battery operated sensors without RTC is one of the reasons why I use custom adapters with which I enhance the received message or even repackage it as SenML.

Where are we going to get the time for the timestamps from? Time synchronization between all Mainflux services would be nice to have feature.
I guess simply reading the time from the adapter's container would be a good start. We can add a time provider service and time synchronization to all services later.

**Comment by drasko** [comment]
This issue is not needed.
