### ISSUE TITLE
Document Provision service

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#1125]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Document new Provision (Zero-Touch Provisioning) service.

In general improve documentation of all edge services (Agent, Export, Provision) with various diagrams, schemas, images, etc...

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must-have

**Comment by mteodor** [comment]
closed by https://github.com/mainflux/docs/pull/33
