### ISSUE TITLE
mainflux-postgres-writer: Failed to unmarshal received message: unexpected EOF

### ISSUE THREAD

**Issue by EflakeEver** [absmach/magistrala#1142]
The context was running standard mainflux service, and adding mainflux-postgres-writer and mainflux-postgres-reader service.

Everything works fine, but when I was sending message to the mainflux by MQTT，I got this error message "Failed to unmarshal received message: unexpected EOF" logged by mainflux-postgres-writer, means that the message can not write into DB, but it can send to NATS successfully.

the same result shown when I was trying HTTP sending message.

The detail console log shown like this :

```
mainflux-mqtt      | {"level":"info","message":"AuthPublish - client ID: 28a3f9475a50431c91ff546e619e6f83 topic: channels/f1a214e8-d4e7-403d-9e21-6cffa79f5866/messages","ts":"2020-04-24T07:23:18.765623901Z"}
mainflux-things    | {"level":"info","message":"Method can_access_by_id for channel f1a214e8-d4e7-403d-9e21-6cffa79f5866 and thing a99f6921-03d7-4787-97ae-74209d98ead8 took 176.68µs to complete without errors.","ts":"2020-04-24T07:23:18.766117021Z"}
mainflux-mqtt      | {"level":"info","message":"Publish - client ID 28a3f9475a50431c91ff546e619e6f83 to the topic: channels/f1a214e8-d4e7-403d-9e21-6cffa79f5866/messages","ts":"2020-04-24T07:23:18.766462858Z"}
mainflux-postgres-writer | {"level":"warn","message":"Failed to unmarshal received message: unexpected EOF,req:\n$f1a214e8-d4e7-403d-9e21-6cffa79f5866\u001a$a99f6921-03d7-4787-97ae-74209d98ead8\"\u0004mqtt2m[{\"n\": \"temperature\", \"t\": 0 , \"v\": 33.06}, {\"n\":\"humidity\", \"t\": 0}, {\"n\": \"pressure\", \"t\": 0, \"v\": 977.87}]:\u000c\u0008槊\ufffd\u0005\u0010\ufffdǾ\ufffd\u0002","ts":"2020-04-24T07:23:18.76689014Z"}
```
The message what i was send is like this:
```
[{"n": "temperature", "t": 0 , "v": 33.06}, {"n":"humidity", "t": 0}, {"n": "pressure", "t": 0, "v": 977.87}]
```

Please help me as soon as possible,thanks

**Comment by manuio** [comment]
@EflakeEver Looks like here: `{"n":"humidity", "t": 0}` you forgot a value.

**Comment by EflakeEver** [comment]
> @EflakeEver Looks like here: `{"n":"humidity", "t": 0}` you forgot a value.

@manuio After adding the "v" value，It still reported the same error message.It seems not the reason.

**Comment by manuio** [comment]
@EflakeEver Please, can you pull latest master and build again all docker images?  Simply do `make dockers` from the root directory and repeat your tests. We recently removed the message payload content-type field (https://github.com/mainflux/mainflux/pull/1121). You are maybe using some old docker images.

**Comment by EflakeEver** [comment]
@manuio OK，I will try it, please wait for my answer.

**Comment by drasko** [comment]
@manuio @EflakeEver logs say that non-valid SenML was sent:
```bash
mainflux-postgres-writer | {"level":"warn","message":"Failed to unmarshal received message: unexpected EOF,req:\n$f1a214e8-d4e7-403d-9e21-6cffa79f5866\u001a$a99f6921-03d7-4787-97ae-74209d98ead8\"\u0004mqtt2m[{\"n\": \"temperature\", \"t\": 0 , \"v\": 33.06}, {\"n\":\"humidity\", \"t\": 0}, {\"n\": \"pressure\", \"t\": 0, \"v\": 977.87}]:\u000c\u0008槊\ufffd\u0005\u0010\ufffdǾ\ufffd\u0002","ts":"2020-04-24T07:23:18.76689014Z"}
```

**Comment by manuio** [comment]
@drasko the error comes from here: https://github.com/mainflux/mainflux/blob/master/writers/writer.go#L59
IMHO it's related to protobuf and the new structure without content-type

**Comment by EflakeEver** [comment]
@manuio You are right. After pulling the latest master and building again, now it works, thank u very much, that's really helpful. Maybe we can add some CI step alone with some basic  automated test code for the master code in the future.

**Comment by manuio** [comment]
@EflakeEver glad to hear that! CI will not help you with your local setup. The problem is that docker-compose only pull images if the tag don't exist locally.

**Comment by EflakeEver** [comment]
@manuio I found that http message can write into DB，but mqtt message can not, please check the master code?

**Comment by EflakeEver** [comment]
@manuio The console shows the same error log as the title says. Does it something I forget to do in the mqtt adapter or configuration?

**Comment by EflakeEver** [comment]
@manuio By the way, the message which send by http and mqtt is the same content, just like mentioned above.

**Comment by manuio** [comment]
@EflakeEver Try this example: https://mainflux.readthedocs.io/en/latest/messaging/#mqtt
I just tested and all works as expected. Maybe you are not using the latest docker-compose.yml from master?

**Comment by EflakeEver** [comment]
@manuio I just found that my local docker image of mqtt is not the latest one, maybe it is the problem, let me try to fix it and I will report the result later, thanks for your test.

**Comment by EflakeEver** [comment]
@manuio After updated the docker image of mqtt, now it works, thanks for ur patient help.
