### ISSUE TITLE
Problem connecting things and channels using SDK

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1145]
When i try to connect things and channels aI get follwing error using SDK
`mainflux-cli -m http://mainflux.ml provision connect conns $TOK`
`failed to connect thing to channel : 400 Bad Reques`

```
➜  certs git:(master) ✗ cat conns
{
    "thing_ids": [
        "173f51a0-fcb7-414e-983c-e7f139adb47b",
    ],
    "channel_ids": [
        "a584642e-0225-4d5c-b4af-8d21ec9210a6",
    ]
}
```

**Comment by manuio** [comment]
@mteodor I just tested and it works. The JSON that you are using is not good, you have an extra `,` after IDs.

**Comment by mteodor** [comment]
yes @manuio it works, file needs extension `.json` or `.csv` which wasnt clear to me from the docs

**Comment by drasko** [comment]
@mteodor which docs and were the docs fixed?

**Comment by drasko** [comment]
Fixed with https://github.com/mainflux/docs/pull/31
