### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by marijadstankovic** [absmach/magistrala#1147]
**BUG REPORT**

1. What were you trying to achieve?
I'm trying to run mainflux properly (folowing the yt video and instructions for installation and running from here).

2. What are the expected results?
The system working properly.

3. What are the received results?
a) When I run the command docker-compose up from docker file all the containers are working but I get:
mainflux-users | {"level":"error","message":"Failed to connect to postgres: dial tcp 172.22.0.7:5432: connect: connection refused", "ts":"2020-04-22T18:08:06.104001Z}
b) Also sometimes I get similar for mainflux-things
Using Grafana I can't connect to users-db either, although that container is working and no reported issues.

c) So, when I use mainflux-cli and try to make a user of course I get the same: connection refused.

d) I even tried mainflux 0.8.0 because it has ui. When I tried to sign up from there, errors from token and user requests appear with codes 400, 403 and 409.
e) But when I try to sing up again with the same email, in console user-db shows that the user already exists.

4. What are the steps to reproduce the issue?
Just running docker-compose up from docker file in mainflux I always get a) and d) but only sometimes the rest of anomalies and i don't know how to reproduce them.

5. In what environment did you encounter the issue?
I use Windows 10 and the latest version of Docker Desktop (stable) and with it I didn't need to install docker compose as it is already included. As for mainflux, I usually use 0.8.0 but I tried the others, and the error is the same.

**Comment by manuio** [comment]
@marijadstankovic I'm pretty sure that this video it's outdated. Please use 0.10.0 version (or latest one) and follow this doc: https://mainflux.readthedocs.io/en/latest/getting-started/
We moved the new UI here: https://github.com/mainflux/ui There you can also find a specific docker-compose to run all needed services.

**Comment by marijadstankovic** [comment]
@manuio Thank you for answering. Just a quick update: since I'm trying to run Mainflux on Windows I needed to adjust commands. Instead running wget command like said in [https://mainflux.readthedocs.io/en/latest/getting-started/](url)  or typing **make cli** command from root as suggested in [https://mainflux.readthedocs.io/en/latest/cli/](url) to install Mainflux CLI I manually run **go build** command, named the program mainflux-cli.exe (instead of just mainflux-cli) so I could execute it later and added it to Path. The CLI now works when I run provision test, but I get a little shady output:
![image](https://user-images.githubusercontent.com/58818571/80801034-6d70d100-8bab-11ea-8f17-8c876dbb9cca.png)
After provision test when I try sending messages I get:
![image](https://user-images.githubusercontent.com/58818571/80801172-d9ebd000-8bab-11ea-8fe4-09ee4b620158.png)
Maybe it has something to do with different coding but I don't know how to fix it.
Also, when I try to run Mainflux CLI from docker image I just get connection refused but now from 172.0.0.1:80 
Post http://localhost/users: dial tcp 127.0.0.1:80: connect: connection refused
Do you know why this is happening and more importantly will it be a problem when I start writing some applications that use Mainflux?

**Comment by mteodor** [comment]
@marijadstankovic not sure that it will work can you try to escape `"` with `\` like `'[{\"b\":\"some-base-name\"...`, 

for running the cli with docker image have in mind that cli application is run inside the docker network so it doesn't see `localhost` , so you have to make it "join" the network
`docker run -it --network=docker_mainflux-base-net  mainflux/cli -m http://users:8180 users token  test@email.com   test1234`

so you will be hitting each service by its name in `docker-compose.yml` `things`,`users` etc.
for checking the ports look into `.env` file

**Comment by marijadstankovic** [comment]
@mteodor It works when I switch " and ' like "[{'b':'some-base-name'....
