### ISSUE TITLE
Connecting new clients to a channel has an issue - Also is there any time stamp for any logs in database?

### ISSUE THREAD

**Issue by 2014siavash** [absmach/magistrala#115]
Hi,

Connecting new clients to a channel results in deleting the old clients which was connected to the channel before. So, I'd like to connect new clients to a channel one by one, but I could not.

Can you fix this?

**Comment by mijicd** [comment]
@2014siavash this is not an issue. Please check out the [API documentation](https://github.com/mainflux/mainflux/blob/master/manager/swagger.yaml#L278). In essence, `PUT` method replaces the content of the resource. So, if you want to add one client to a channel, you need to do that by providing the old ones as well.

**Comment by 2014siavash** [comment]
Yes Thank you. But I want to know if the new client of a channel could see the messages which sent before or not? I mean, is there any time stamp for each connection of clients (or for every things)?
For more explanation, suppose that there is a connected client A to a channel C. Then A sent some messages to this channel. After that, we want to add a new client B to the channel. In this situation, I have these questions:

1- do B can see or query the old messages sent by A?
2- do A can see or query her old messages sent by herself?
3- do we know when A and B are connected to the channel (and when they are get out from it)?
4- Is there the same issue when B wants to get out from the channel C? what happen for A in this situation?
5- As I understood, each client can access to the messages of some channels that she is connected to them. I want to exactly knows that any changes in configurations, specially the changes related to the channels that A connected to them, have what effects on accessibility of A to the messages on these channels?
6- The previous version of Mainflux, I mean the one which worked with influxdb, has time stamp for any logs. I can not see this in the newer version which is working with cassandra. Am I wrong? or why you remove this important feature?

thanks a lot for your support.
