### ISSUE TITLE
Connecting to mainflux server

### ISSUE THREAD

**Issue by Nitheshnithu121** [absmach/magistrala#1156]
How can i connect to mainflux server and how can i send the sensor data to the server using arduino uno or nodemcu

**Comment by drasko** [comment]
Start by checking the documentation and other resources on the website: https://www.mainflux.com/

**Comment by Nitheshnithu121** [comment]
after searching only i didn't get anything related to that ,that's why i
asked

**Comment by drasko** [comment]
Use MQTT messaging for example: https://mainflux.readthedocs.io/en/latest/messaging/#mqtt

**Comment by Nitheshnithu121** [comment]
Thank you
