### ISSUE TITLE
Forwarding messages by HTTP

### ISSUE THREAD

**Issue by jonathandreyer** [absmach/magistrala#1157]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
I use the Mainflux platform as a backend of my application and I need to transfer data to another microservices entity (without throughout a database). Actually, it is not possible to transfer some message directly to another application by HTTP. In fact with the Export service, it is possible to do something similar but it is with MQTT protocol. With HTTP, we can easily add circuit breakers, load balancers, rules, etc.
With @drasko, we have already discussed that on the Gitter (beginning of conversation here: https://gitter.im/Mainflux/mainflux?at=5e8e397c9316f34b8d8c5691).

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is definitely a should-have feature.

**Comment by jonathandreyer** [comment]
This [repository](https://github.com/jonathandreyer/mainflux-http-forwarder) resolves this issue.

**Comment by nmarcetic** [comment]
Great work @jonathandreyer
Closing this one.
