### ISSUE TITLE
Problems sending messages with CLI

### ISSUE THREAD

**Issue by luixal** [absmach/magistrala#1161]
**BUG REPORT**

1. What were you trying to achieve?

Once the system is freshly started (using docker compose on the master branch) and provisioned (with CLI `privision test`), Ive send a message from one generate thing to one generated channel using the CLI like this:

```sh
./mainflux-cli messages send 16917403-c0b2-4d67-86e3-fd473b93fa4f '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]' 55644f44-a79f-4b12-bdb3-a1fbd79bc2d8
```
 Response is `ok` as expected.

When I try to read messages for that thing on that channel using CLI like this:

```sh
./mainflux-cli messages read 16917403-c0b2-4d67-86e3-fd473b93fa4f ca7a176d-78d8-4f68-ae2a-9a5c9beb77f3
```
I got the following error:

```
Get http://localhost:8905/channels/16917403-c0b2-4d67-86e3-fd473b93fa4f/messages: dial tcp 127.0.0.1:8905: connect: connection refused
```

Looking at docker containers, I got no container with port 8905 mapped. Things container has this mapping:

```
0.0.0.0:8182-8183->8182-8183/tcp, 0.0.0.0:8989->8989/tcp
```

2. What are the expected results?

Get the messages instead of the error.

3. What are the received results?

Error described above.

4. What are the steps to reproduce the issue?

```sh
// once the repo is clonned and CLI is built:
mainflux-cli provision test
// send message (this works ok). json_message taken from examples to be sure:
mainflux-cli things messages send <channel_id> <json_message> <thing_key>
// read messages in channel for this thing, got the error described:
mainflux-cli things messages send <channel_id> <thing_key>
```

5. In what environment did you encounter the issue?

Master branch run using default docker-compose file.

6. Additional information you deem important:

Not much.

**Comment by manuio** [comment]
@luixal Looks like you are only running core services. You also need a database writer and reader.
Try with:
`docker-compose -f docker/addons/influxdb-writer/docker-compose.yml up` 
`docker-compose -f docker/addons/influxdb-reader/docker-compose.yml up`

**Comment by luixal** [comment]
Thanks for such a quick response @manuio. I've run the writer and reader and now I'm no getting errors, but I'm still not getting messages:

```json
{
  "limit": 0,
  "offset": 0,
  "total": 0
}
```

Messages I've tried sending:

Example message:

```json
[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]
```
And the same message without the `bt` field. No idea if it's mandatory (and I also haven't been able to find a converter from date to timestamp CBOR format...)

I've noticed I get some logs when sending a message in `mainflux-things` and `mainflux-http` like this:

```
mainflux-things | {"level":"info","message":"Method can_access for channel 16917403-c0b2-4d67-86e3-fd473b93fa4f and thing ca7a176d-78d8-4f68-ae2a-9a5c9beb77f3 took 322.947µs to complete without errors.","ts":"2020-05-04T14:34:24.11496665Z"}
mainflux-http   | {"level":"info","message":"Method publish to channel 16917403-c0b2-4d67-86e3-fd473b93fa4f took 1.061175ms to complete without errors.","ts":"2020-05-04T14:34:24.115199069Z"}
```
but none in `mainflux-influxdb`, `mainflux-influxdb-writer` or `mainflux-influxdb-reader`.

Is there any other config needed? Thanks!

**Comment by manuio** [comment]
@luixal Our master branch was broken last week. We merged the fix this morning but it could be that you are using a version with a bug. Can you please pull latest master branch and do `make docker_http` and `make docker_influxdb-writer`. When it's done run again docker-compose.

**Comment by luixal** [comment]
Ok @manuio, I had pulled this morning, but didn't perform the make commands (just removed docker images assumed CI/CD would have push changes to dockerhub).

In case anyone gets here, as @manuio said, building latest changes did the trick:

Just pulled again (just in case, no changes downloaded) and run:

```
make docker_http
make docker_influxdb-writer
make docker_influxdb-reader
```
then run containers like this:

```
docker-compose -f docker/docker-compose.yml -f docker/addons/influxdb-writer/docker-compose.yml -f docker/addons/influxdb-reader/docker-compose.yml up
```
And it did the trick:

```json
{
  "limit": 10,
  "messages": [
    {
      "channel": "77a29be6-43bc-4f61-b382-33e2b090ce55",
      "name": "current",
      "protocol": "http",
      "publisher": "e26a891c-bfaf-41b7-a79a-05608866732b",
      "time": -4,
      "value": 1.3
    },
    {
      "channel": "77a29be6-43bc-4f61-b382-33e2b090ce55",
      "name": "current",
      "protocol": "http",
      "publisher": "e26a891c-bfaf-41b7-a79a-05608866732b",
      "time": -5,
      "value": 1.2
    }
  ],
  "offset": 0,
  "total": 2
}
```

Just for taking in count, how often are new images pushed to dockerhub?

Thank you very much!

**Comment by manuio** [comment]
@luixal Let me explain it better. Every time that a pull request is merged in the master we build new docker images. You can pull github repo and run a docker composition but still use old images. To update the images that you are using locally you can do `docker pull mainflux/http` to use the image from DockerHub or `make docker_http`  to build it locally.

In any case glad to ear that it's working for you. Closing the issue.
