### ISSUE TITLE
Determining Message Publisher in Database

### ISSUE THREAD

**Issue by 2014siavash** [absmach/magistrala#117]
I think it is better to determine a message publisher by its id, not its access_key. If you think so, can you fix this? else, can you explain why you introduce message publisher by its access_key?

----------------------------------------------------------------------------------------------------

cqlsh> select * from message_writer.messages_by_channel;

 channel                              | id                                   | bn   | bs   | bt   | bu   | bv   | bver | l | n                      | protocol | publisher                                                                                                                                                                                    | s | t         | u | ut | v     | vb    | vd | vs
--------------------------------------+--------------------------------------+------+------+------+------+------+------+---+------------------------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---+-----------+---+----+-------+-------+----+----
 743219d8-a8d5-11e7-bb35-0242ac110005 | 1868de00-ac01-11e7-a1bf-f58bd8d3766a | null | null | null | null | null |    5 |   | some-base-name:voltage |     http | eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MDcxMDA5MDMsImlzcyI6Im1haW5mbHV4Iiwic3ViIjoiY2Y2YWRjMTMtYThkMi0xMWU3LWJiMWUtMDI0MmFjMTEwMDA1In0._z_SamNwgo2PMhKAAIyFqnSsWWliN_R2bfNas9SFzu4 | 0 | 1.276e+09 | V |  0 | 120.1 | False |    |

**Comment by mijicd** [comment]
@2014siavash this is already in progress. It depends on some other internal things though. Once the service discovery PR is completed (i'm working on it), this will be resolved as well. Until then, I am closing this issue.
