### ISSUE TITLE
Add a certificate service and certs endpoint to SDK

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1179]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

We should add endpoint into the SDK that can create certificates for things to be used in mTLS enabled deployment.
This endpoint then should be used in `Provision` service 

There is already some  certificate creation code written, here: 
https://github.com/mainflux/mainflux/blob/master/tools/provision/provision.go#L193

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Must have

**Comment by drasko** [comment]
@mteodor do you think that this should be `Provision` endpoint, and then supported by SDK (because SDK is not itself the service, but just a client - it can not expose endpoints)?

**Comment by mteodor** [comment]
@drasko we can do it that way also, though I thought that `Provision` service should just proxy requests for certs to a 3rd party service and that we just add this basic certificate creation when there is no such service.

**Comment by drasko** [comment]
https://jbrandhorst.com/post/certify/
