### ISSUE TITLE
How can i delete a channel, user, or client? 

### ISSUE THREAD

**Issue by 2014siavash** [absmach/magistrala#118]
Hi,

How can i delete a channel, user, or client?
There is no guid in your wiki.http://mainflux.readthedocs.io/en/latest/getting-started/

I am developing a simple UI for mainflux with django. I need to know this to put it in the UI.

Thanks

**Comment by mijicd** [comment]
@2014siavash Check out the API documentation of `manager` service [here](https://github.com/mainflux/mainflux/blob/master/manager/swagger.yaml). Currently, deleting users is not supported, while you can remove channels and clients.

**Comment by drasko** [comment]
Yes, "Getting Started" is just a doc to get you started, not a full API reference. For what is supported you'll have to look at swagger doc for now, and we'll try to put real API reference doc online (which will be generated from these swagger docs)
