### ISSUE TITLE
Issue with building the CLI 

### ISSUE THREAD

**Issue by Madd-Scientist** [absmach/magistrala#1182]
1. What were you trying to achieve?
Trying to build the cli using "make cli" 

2. What are the expected results?
It should build the cli. 

3. What are the received results?
<pre>CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags &quot;-s -w&quot; -o build/mainflux-cli cmd/cli/main.go
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run &apos;go help build&apos; for details.
Makefile:77: recipe for target &apos;cli&apos; failed
make: *** [cli] Error 2
</pre>

PFA: Screenshot of the terminal. 
![Screenshot from 2020-05-22 12-00-30](https://user-images.githubusercontent.com/19285349/82639034-8f4afa00-9c25-11ea-929f-aa109dbab09d.png)

4. What are the steps to reproduce the issue?
Clone the github repo, build the mainflux server using "make run", then try to build the cli using "make cli". 

5. In what environment did you encounter the issue?
Ubuntu 18.04, docker-ce version 18.09.9~3-0, docker compose version 1.24.1, go 1.7.3

6. Additional information you deem important:
Similar problem occurs while building anything in the cmd directory. I assume the issue is with my environment, but I'm unable to pinpoint the problem.

**Comment by dborovcanin** [comment]
Which version of Go are you using? It looks like you're using an old version of Go (probably <1.11). Do you have Go modules disabled (`GO111MODULE=off`)?

**Comment by drasko** [comment]
```bash
drasko@Mando:~/go/src/github.com/mainflux/mainflux$ make cli
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags "-s -w" -o build/mainflux-cli cmd/cli/main.go
drasko@Mando:~/go/src/github.com/mainflux/mainflux$ ls -la build/
total 9556
drwxr-xr-x  2 drasko drasko    4096 May 22 13:05 .
drwxr-xr-x 31 drasko drasko    4096 May 22 13:05 ..
-rwxr-xr-x  1 drasko drasko 9777152 May 22 13:05 mainflux-cli
```
Works like charm ;)

**Comment by Madd-Scientist** [comment]
I tried drasko's command, the output was similar but when I try using a mainflux-cli command, the command is not found. 

<pre><font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux</b></font>$ make cli
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags &quot;-s -w&quot; -o build/mainflux-cli cmd/cli/main.go
<font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux</b></font>$ ls -la build/
total 11168
drwxr-xr-x  2 maddscientist maddscientist     4096 May 27 18:26 <font color="#729FCF"><b>.</b></font>
drwxr-xr-x 31 maddscientist maddscientist     4096 May 27 18:26 <font color="#729FCF"><b>..</b></font>
-rwxr-xr-x  1 maddscientist maddscientist 11427840 May 27 20:09 <font color="#8AE234"><b>mainflux-cli</b></font>
</pre>

Earlier i was using an older version of go, and I updated it to 1.14
Now "make cli" is not showing any errors like earlier. 
I manually enabled the go modules as well, and added go to my $PATH 
Still, the response is same. 

<pre><font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~</b></font>$ export PATH=$PATH:/snap/bin/go
<font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~</b></font>$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin/go
<font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~</b></font>$ cd mainflux
<font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux</b></font>$ make cli
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags &quot;-s -w&quot; -o build/mainflux-cli cmd/cli/main.go
<font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux</b></font>$ mainfux-cli version
mainfux-cli: command not found</pre>

And 

<pre><font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux</b></font>$ GO111MODULE=on CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags &quot;-s -w&quot; -o build/mainflux-cli cmd/cli/main.go
<font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux</b></font>$ mainflux-cli version
mainflux-cli: command not found
</pre>

Please help me with the installation, I'm unable to pin-point the error. Everything else in mainflux (the server and the webUI) was installed smoothly and is running fine.

**Comment by drasko** [comment]
It's in the `build` dir.

**Comment by Madd-Scientist** [comment]
<pre><font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux/build</b></font>$ ls
<font color="#8AE234"><b>mainflux-cli</b></font>
<font color="#8AE234"><b>maddscientist@maddcomputer</b></font>:<font color="#729FCF"><b>~/mainflux/build</b></font>$ mainflux-cli version
mainflux-cli: command not found
</pre>

I can locate the file in the build directory but it doesn't seem to work as a command, what could be the reason?

**Comment by dborovcanin** [comment]
Looks like you are trying to run `mainflux-cli` command rather than trying to execute `mainflux-cli` binary. To execute `mainflux-cli` binary, you can do `./build/mainflux-cli` from the project root. To make `mainflux-cli` command available, you need to add `mainflux-cli` location to you PATH: `export PATH=$PATH:<MF_LOCATION>/build`.

**Comment by Madd-Scientist** [comment]
Oh yes, my bad. It is working now. Thanks for the active support.

**Comment by Madd-Scientist** [comment]
Hey, unrelated query but not big enough to create an issue. 
Where can I see the thing_auth_token? I am able to retrieve the thing ID and key from the webUI, but I need the auth token to send a message over HTTP.

**Comment by manuio** [comment]
@Madd-Scientist The topic of issues are always respected. For this kind of questions you can use our community chat: https://gitter.im/Mainflux/mainflux
