### ISSUE TITLE
Is there any time stamp for all logs in database?

### ISSUE THREAD

**Issue by 2014siavash** [absmach/magistrala#119]
Hi,

I think it is better to open a new issue for this subject, as you can see I wrote this for the response of the closed issue #115.

I want to know if the new client of a channel could see the messages which sent before or not? I mean, is there any time stamp for each connection of clients (or for every things)?
For more explanation, suppose that there is a connected client A to a channel C. Then A sent some messages to this channel. After that, we want to add a new client B to the channel. In this situation, I have these questions:

1- do B can see or query the old messages sent by A?
2- do A can see or query her old messages sent by herself?
3- do we know when A and B are connected to the channel (and when they are get out from it)?
4- Is there the same issue when B wants to get out from the channel C? what happen for A in this situation?
5- As I understood, each client can access to the messages of some channels that she is connected to them. I want to exactly knows that any changes in configurations, specially the changes related to the channels that A connected to them, have what effects on accessibility of A to the messages on these channels?
6- The previous version of Mainflux, I mean the one which worked with influxdb, has time stamp for any logs. I can not see this in the newer version which is working with cassandra. Am I wrong? or why you remove this important feature?

thanks a lot for your support.

**Comment by mijicd** [comment]
Hi,

Below you can find the answers:

1-2. Message querying is application specific, and depends on the use case.
3-4. What do you mean by "do we know"? As the owner of the channel, the user is in charge of connecting and disconnecting clients from channels.
5. None
6. Timeuuid which is used as an identifier contains the timestamp of message as well.

**Comment by 2014siavash** [comment]
Thank you very much. Here are some other questions:

For 1-2: So there are not any restrictions for queries on Cassandra in mainflux? Because I Think B should not see the old messages sent by A (because B is connected to the channel C after client A), but A should see her old messages, herself. Therefore, you mean that application should manages the queries.
For 3-4: "do we know" means whether the Timeuuid of connecting and disconnecting of each client to or from a channel is also logged in to the database or not? More precisely, the history of what happened for each client is logged or not?
For 5: You mean that if A is disconnected from the channel C, her old messages are not deleted from it and can be accessible? thanks.
For 6: Thanks.
