### ISSUE TITLE
Missing MQTT messages

### ISSUE THREAD

**Issue by marcelo-rute** [absmach/magistrala#1192]
I have the following problem. If Mainflux sends 5 MQTT messages to a device in sequence and the device takes 3 minutes to process each message synchronously, why do we only receive the first 2 messages? Is there any type of timeout for the messages? Could you help me with this problem, please?

**Comment by drasko** [comment]
Use MQTT QoS: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/
