### ISSUE TITLE
Documentation for integration to chirpstack

### ISSUE THREAD

**Issue by dcolley** [absmach/magistrala#1195]
**FEATURE REQUEST**

I am running the docker services, there is a link to "Admin > Lora Server", but none of the users are able to login.
Please could you point / provide a HowTo for mainflux <=> chirpstack / lora server

**Comment by drasko** [comment]
- Official doc: https://mainflux.readthedocs.io/en/latest/lora/
- Blog (tutorial): https://medium.com/mainflux-iot-platform/mainflux-lorawan-tutorial-c54632ffee99

**Comment by manuio** [comment]
@dcolley By default our lora-adapter is configured to subscribe to our Chirpspack demo MQTT broker located at `tcp://lora.mqtt.mainflux.io:1883`. You can configure it here: https://github.com/mainflux/mainflux/blob/master/.env#L130 

On the UI side you can configure the Admin / Lora Server page here: https://github.com/mainflux/ui/blob/master/src/environments/environment.prod.ts#L28

**Comment by dcolley** [comment]
thanks guys!
