### ISSUE TITLE
MongoDB-Reader v0.11.0 and master - 500 Internal Server Error

### ISSUE THREAD

**Issue by longlnk** [absmach/magistrala#1201]
I use Mainflux version v0.11.0 and master, it have errror 500 Internal Server Error when I get to mongodb-reader.

curl -s -S -i  -H "Authorization: 6bb4f8b1-d605-46d9-a925-0e91a7cf90af" http://IP_address:port/channels/0a2193ea-c358-4bff-8fb0-ab73d8155e62/messages
HTTP/1.1 500 Internal Server Error
Date: Fri, 05 Jun 2020 10:58:34 GMT
Content-Length: 0

# My config:
![image](https://user-images.githubusercontent.com/15074179/83869480-d7eed100-a756-11ea-88bc-19934a7d1aff.png)

![image](https://user-images.githubusercontent.com/15074179/83869516-e806b080-a756-11ea-88ad-6cbdc0498d54.png)

![image](https://user-images.githubusercontent.com/15074179/83869592-01a7f800-a757-11ea-8615-482688bec077.png)

# Things
helm 11 id "88e1b958-ed57-4796-b4ad-72ca169dc425" key "6bb4f8b1-d605-46d9-a925-0e91a7cf90af"

helm 12 id "149e131e-bf46-409f-9651-42cff1165f4c" key "e1621d52-1c2f-4c79-bcd0-cbe619af9a85"

# Channels
/channels/0a2193ea-c358-4bff-8fb0-ab73d8155e62

please help me.

**Comment by nmarcetic** [comment]
@longlnk What's the reader output log after error 500? The screenshot you posted is when you run reader service, but what about logs after you get error 500?

**Comment by manuio** [comment]
@nmarcetic I tested and the only error message is the one described in this issue. 
After some debug I found `rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8181: connect: connection refused"`. Let me try to fix this.

**Comment by longlnk** [comment]
Hi @manuio , Can you merge to tag v0.11.0?

**Comment by manuio** [comment]
@longlnk I'm not sure to understand the question. You should use the latest master version if you want this bug fixed.

**Comment by longlnk** [comment]
> I'm not sure to understand the question. You should use the latest master version if you want this bug fixed.

Thank you ;)
