### ISSUE TITLE
Remote control over HTTP

### ISSUE THREAD

**Issue by nightmeng** [absmach/magistrala#1222]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
NO

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
I want to known how we receive the response of remote RPC response over HTTP. 
For example, we publish a remote RPC to turn on a light and the endpoint device reply a response to the specified channel, how do we get the response over HTTP?

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Support remote RPC for HTTP

**Comment by nmarcetic** [comment]
@nightmeng HTTP supports only publish, because of the nature of the protocol. You can't subscribe to HTTP.  
You should consider MQTT instead.

**Comment by drasko** [comment]
> For example, we publish a remote RPC to turn on a light and the endpoint device reply a response to the specified channel, how do we get the response over HTTP?

As @nmarcetic said - we do not support HTTP callbacks that you can register. This would be an overkill when there are bidirectional protocols - like MQTT, WebSockets and CoAP that Mainflux supports and that can be used exactly for this purpose.

In the scenario of HTTP callbacks users would be forced to develop their HTTP endpoints (i.e. API to pass as a callback). When using some of the bidirectional protocols it is just a matter of using a lightweight library to subscribe to a channel.and get messages/responses asynchronously.

@nightmeng do you absolutely need HTTP, and can not use any other mentioned protocol (MQTT, WS or CoAP)?

**Comment by nightmeng** [comment]
@nmarcetic @drasko Thank you very much!!
I'm developing a modbus gateway device now, and I want to export HTTP API to users. I think I should develop an app service for my gateway devices, and the app service exports HTTP API to users.

**Comment by nmarcetic** [comment]
@nightmeng Yes, that makes more sense. Build an app/service on top of Mainflux for your users (expose your API and business logic) and use Mainflux for your gateway connections (I would suggest MQTT) and remote control. 
Its meant to be an MoM in your stack.

**Comment by drasko** [comment]
Closing the issue. Please reopen if needed.
