### ISSUE TITLE
404 Not Found - Mainflux UI doesn't work

### ISSUE THREAD

**Issue by altinvolkan** [absmach/magistrala#1239]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?

Standart installation progress.

2. What are the expected results?

Normal installation, and user registration

3. What are the received results?

Cannot access the panel

4. What are the steps to reproduce the issue?

started with "make run"
also tried to start /docker/addons/influxdb-writer/ & reader 

5. In what environment did you encounter the issue?

Ubuntu 18.0.8 - AWS t3.medium

6. Additional information you deem important:

When i downgraded with tig to 1.0.0 version, UI will work. But cannot register users, or function

**Comment by manuio** [comment]
@altinvolkan Please, use this repository for UI issues: https://github.com/mainflux/ui 
From there you can also deploy Mainflux + UI with the command `make run`
