### ISSUE TITLE
Error when trying to start mainflux-docker.sh

### ISSUE THREAD

**Issue by FractalWire** [absmach/magistrala#124]
Hello,

I tried to start the `mainflux-docker.sh` script, unfortunately, I get some error with NATS and Cassandra : 

```
Starting nats      ... error
Starting cassandra ... error

ERROR: for nats  Cannot start service nats: failed to create endpoint mainflux-nats on network bridge: failed to add the host (vethfbbd79a) <=> sandbox (vethfad9c8f) pair interfaces: operation not supported

ERROR: for cassandra  Cannot start service cassandra: failed to create endpoint mainflux-cassandra on network bridge: failed to add the host (vetha22aa05) <=> sandbox (vethd88054d) pair interfaces: operation not supported
ERROR: No containers to start
Aborting due to errexit on line 78. Exit code: 1

```

I'm using archlinux if that matter
docker version 17.10.0-ce
docker-compose version 1.17.0

**Comment by drasko** [comment]
Strange... Looks like you can not even start NATS and C* in the Docker.

Can you try running `docker-compose` just giving it this file: https://github.com/mainflux/mainflux/blob/master/bin/docker/docker-compose.infrastructure.yml

Otherwise fallback o manual installation: https://github.com/mainflux/mainflux/blob/master/bin/mainflux-install.sh

**Comment by theOgrable** [comment]
Ah, well.
No error there. And the `mainflux-docker` script works as well now.

My guess is one of the requirement needed a reboot (docker-compose maybe). I should have checked that, sorry.

**Comment by FractalWire** [comment]
Well,
No error here. And the docker script worked as well.

My guess is, one of the dependency needed a reboot (docker-compose maybe) to work properly. I should have checked that, sorry.
