### ISSUE TITLE
Return to service transport layer only service errors

### ISSUE THREAD

**Issue by darkodraskovic** [absmach/magistrala#1240]
Currently, we send to transport.go errors from different sources (db, cache, etc.). However, not all of these errors are addressed by the switch case in the transport.go. So we have a double problem: firstly, inconsistent error sources, secondly unaddressed errors.

Also, we need to make swagger spec in agreement with new error handling, plus, we need to migrate swaggers to openapi 3. 

This relates also to issue #1261, so the single PR should tackle both issues at once.

**Comment by manuio** [comment]
Migration from swagger to openapi done here: https://github.com/mainflux/mainflux/pull/1250

**Comment by manuio** [comment]
Partially resolved here: https://github.com/mainflux/mainflux/issues/1261
And here: https://github.com/mainflux/mainflux/issues/1263
