### ISSUE TITLE
Invalid require module github.com/mainflux/senml v1.5.0 in go.mod

### ISSUE THREAD

**Issue by youzio** [absmach/magistrala#1243]
Can‘t get the tag v1.5.0 for github.com/mainflux/senml.  only can get tags v1.0.0 and v1.0.1 .
Please check it, thank you.

**Comment by nmarcetic** [comment]
@youzio You are right, checking. Thanks for reporting!

**Comment by drasko** [comment]
@dusanb94 ca yo uplease take a look at this one?
