### ISSUE TITLE
Add access policies for users

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1248]
**FEATURE REQUEST**

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

We need possibility restrict and control users access in Mainflux.
Users access rights should be defined with policy and assigned to user either directly or via group he belongs to.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Must Have

**Comment by nmarcetic** [comment]
@mteodor You mean extend user access? Cause the user doesn't have any access besides `owner` Does this enable access to resources that are not strictly owned by the resource owner? Like I can access your channels and things, a different access level like unix `r w x` ? I got it for groups, that will be really useful.

**Comment by mteodor** [comment]
@nmarcetic this is restricting users in users space
this should introduce superadmin that doesnt have any restriction
superadmin would be able to create other users as well as users that are admins
other users would have restriction on creating and viewing other users accross different groups

**Comment by nmarcetic** [comment]
I see, but this will require a lot of changes. With policies, can we maybe keep everything as is, not extending userspace (in theory yes) but with groups help get the same behavior. For example, imaging everything as is now, you create a group called `admins` and assign user `Jon` to this group, then set a policy to this group which will say that this group has action `*` which means all actions to resource `users`. This means I can CRUD users. This is just a trivial example but possibilities with policies, groups, and Mainflux entities are huge, just leaving everything as is :) What is superadmin, actually? A predefined user in a system that belongs to the default group and has all permissions. Can you make other uses superadmin like, probably by adding `sudoers` group and adding the same policy, as in Unix? 
IMHO this is most flexible, simple, and clean. Maybe we should think about it.

Maybe it is best to describe the idea, the implementation that you had in mind, and how it should be done?

**Comment by nmarcetic** [comment]
@mteodor I just saw that you tag the issue with draft PR, you already stared with impl... so forget discussion :) Sorry I didn't saw it at first.

**Comment by mteodor** [comment]
Yes, please take a look at the PR cause it implements what you wrote
And yes, you can make other users super admin while there is one by default (he is not in any group ) @nmarcetic

**Comment by nmarcetic** [comment]
Sure @mteodor checking PR.

**Comment by drasko** [comment]
As per https://github.com/mainflux/mainflux/issues/1267:

> Currently any authorized token can fetch Users information. Add policies to ListUsers and ViewUsers methods to avoid unauthorized actions.
