### ISSUE TITLE
Reader endpoint that retrieves messages related to user

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1257]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Currently there is endpoint that retrieves messages from channels that are connected to thing passed in request.
There should be endpoint where you can retrieve messages for channels that belong to user filtered by some criteria.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Must have

**Comment by manuio** [comment]
I would say reader and adapters. Probably it can be done in auth layer

**Comment by drasko** [comment]
As mentioned [here](https://github.com/mainflux/mainflux/pull/1470#discussion_r786319670) we need to figure out what Authentication scheme will be used. Each decision will break the API.
