### ISSUE TITLE
Make Transformers configurable

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#1265]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Currently, Mainflux writers use transformers to transform the Mainflux message to the known format. However, those transformers are not configurable using Writer's configuration (env vars) but need to be changed programmatically. 

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a must-have.

**Comment by nmarcetic** [comment]
Strongly agree. IMHO it's a must-have
