### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by tritao** [absmach/magistrala#1268]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

As a recent user of Mainflux, I have spent some time using the CLI tool for creating users, things, channels,
as well as certificates and found some problems with user experience, even had to go through the source code to understand how to use some commands.

As such, I would like to suggest some changes that I think could help the new user experience a bit as well as make the CLI tool a bit more self-documented and easier to use.

## Introduce flags to commands instead of just using positional parameters

Lets take an example of the `certs issue` command:

Right now, it is like this: `"issue <thing_id> <keybits> <keytype> <hoursvalid> <user_auth_token>"`

The user has no way of knowing what each parameter expects, and also there is no way to tell the CLI about default good values. I suggest using flags instead for the optional parameters, which can have default values set in Cobra.

`usage: issue <thing_id> [--keysize=2048] [--keytype=rsa] [--ttl 128000]`

This provides the user with some information about the default values, as well as makes them optional if the default values are good enough (which most often are).

The long help for each command can be then used to document each flag, for instance, `--keytype` can take `rsa` or `ec`.

## Introduce a CLI config file as well as a new `--config <path>` flag.

The purpose of the config file would be to be able to contain settings for the CLI tool.
The config file would be read at launch and the CLI tool would automatically know default parameters for some flags.

Things like the Mainflux URL instance, and default user auth token could be setup, as well as whatever comes up in the future.

I was thinking maybe something like https://github.com/spf13/viper could be used, what do you think?

## Remove explicit user token positional parameters from all commands and use a global flag instead

It gets tiring to always have to copy paste the user auth token, and since it is used by a lot of commands,
I would suggest to introduce a global flag `--auth-token` or such, that would be used by default for the commands
that need to pass it to Mainflux API calls.

The default value would be read from config file. Each command that needs it would check to see if there is the
user auth token set, if not it would give an error message to the user telling how to set it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Nice-to-have.

Let me know your thoughts on these suggestions, I can send a PR for this if you think it is a good idea.

**Comment by nmarcetic** [comment]
I agree with all the proposed improvements. Most CLI's have kind of config files, at least for credentials and URL.
Flags are so obvious improvement and great self-documentation. IMHO CLI should be fully refactored, with DRY in mind.

**Comment by dborovcanin** [comment]
I like the idea. We'll need to address some of these features in the CLI, SDK, but also to add support for some of them even on the service side - for example, configuring Thing key or Thing/Channel id size when creating it - it may be very useful to have that kind of control because some constrained protocols such as CoAP might struggle with key/id size. We should start with simple improvements such as global `authn token`, and continue resolving this issue through incremental improvements.
