### ISSUE TITLE
Add option to rise log levels for dev purposes

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#127]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Add the option to rise log levels for development purposes.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
should-have

**Comment by mijicd** [comment]
Logs are already exposed regardless of the environment.
