### ISSUE TITLE
Add CLI support for Thing Groups

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1270]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Thing Groups manipulation should be supported same as User Groups and other entities in CLI

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must have

**Comment by dborovcanin** [comment]
Including changes that need to be made in SDK, as well.

**Comment by drasko** [comment]
CLI support for groups is already implemented.
