### ISSUE TITLE
Add Things Groups tests

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1271]
**ENHANCEMENT**

Describe the enhancement you are requesting:
Things Groups described in #397 and introduced in #1259 need to be tested.

Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a must-have.

**Comment by dborovcanin** [comment]
This includes updating mocks in other services such as Bootstrap if needed.

**Comment by drasko** [comment]
Will be closed via https://github.com/mainflux/mainflux/issues/1346
