### ISSUE TITLE
Update API documentation, document groups endpoints for Users and Things service

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1272]
Api endpoints for added Users and Things Groups are missing swagger.yml

**Comment by kavin404** [comment]
How can I get access to this already existing swagger doc?

**Comment by mteodor** [comment]
> How can I get access to this already existing swagger doc?

They need to be written

**Comment by drasko** [comment]
@kavin404 all OpenAPI (ex Swagger) docs are kept in a respected service directories. For example, for `Things` microservice, you can find a file [here](https://github.com/mainflux/mainflux/blob/master/things/openapi.yml).

Same will be for Things Groups once it is merged.

**Comment by drasko** [comment]
Gropus are moving to Auth microservice via https://github.com/mainflux/mainflux/issues/1346, and will be documented over there.
