### ISSUE TITLE
Use User ID instead of email for identification

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#1273]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
As of #1245, User ID is in the response of `Identify` method. Since we switched to User ID as the main user identification attribute, we should use it whenever we can instead of User email, which we use now.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a must-have.

_Originally posted by @dusanb94 in https://github.com/mainflux/mainflux/pull/1245#discussion_r512654502_

**Comment by manuio** [comment]
Duplicated issue: https://github.com/mainflux/mainflux/issues/739

Closing this one
