### ISSUE TITLE
Structure of things_id.json, things_key.json, channels_id.json files!!!

### ISSUE THREAD

**Issue by sitewhere-iot** [absmach/magistrala#1280]
![image](https://user-images.githubusercontent.com/66471900/98951838-c8489500-250b-11eb-9df4-7a393175f902.png)

**Comment by sitewhere-iot** [comment]
what does the structure of these files look like?

**Comment by drasko** [comment]
Duplicate of https://github.com/mainflux/benchmark/issues/9
