### ISSUE TITLE
Structure of things_id.json, things_key.json, channels_id.json files!!!

### ISSUE THREAD

**Issue by sitewhere-iot** [absmach/magistrala#1281]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?

2. What are the expected results?

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

**Comment by sitewhere-iot** [comment]
![image](https://user-images.githubusercontent.com/66471900/98952431-7d7b4d00-250c-11eb-96e7-fa2dd97e7a99.png)

**Comment by sitewhere-iot** [comment]
what does the structure of these files look like?

**Comment by drasko** [comment]
@sitewhere-iot opening duplicate issues will not help.

This one is enough: https://github.com/mainflux/benchmark/issues/9
