### ISSUE TITLE
Use official Protobuf implementation

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#1287]
**ENHANCEMENT**

1. Describe the enhancement you are requesting:
Consider migrating from [Protocol Buffers for Go with Gadgets](https://github.com/gogo/protobuf) to the [official Go Protobuf implementation](https://github.com/protocolbuffers/protobuf-go) since GoGo Probuf is [looking for new ownership](https://github.com/gogo/protobuf/issues/691). GoGo Protobuf can't catch up with the recent updates in the official Protobuf and it would be nice to switch to the official one due to the future support and updates. I don't like the recent updates and introduction of the reflection and passing things around using pointers in the recent versions of the Protobuf, but we have to live with that.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a should-have enhancement.

**Comment by drasko** [comment]
What is the status of this one?

**Comment by rodneyosodo** [comment]
Resolved by https://github.com/mainflux/mainflux/pull/1704
