### ISSUE TITLE
Sort order of things, channels

### ISSUE THREAD

**Issue by bbokun** [absmach/magistrala#1290]
When creating things/channels (for example in the UI), the sort order of the things and channels seems to be random, and not in a visual identifiable way.
Looking into the code, the sorting is done on the ID field, which is a UUID type, which is generated automatically by the database engine. (In very early versions of mainflux the ID was an integer. the sort order was reproducible as the things/channels created first, had lower IDs than the things/channels created later, and on that way some visible sort order exited)

It would be better to have a more natural sort order.

**Comment by manuio** [comment]
@bbokun what if we increase the limit?

**Comment by manuio** [comment]
@bbokun I've a small fix to sort by `name` instead of sort by `id`. Something better would be to sort by `created_at` but this probably deserve another issue :)

**Comment by drasko** [comment]
Both ULIDs and XIDs are lexicographically sortable. Real solution for this problem would be switching to this UUID variant, as explained in https://github.com/mainflux/mainflux/issues/930

This would break backwards compatibility, but it would allow for other nice features (besides sortability, short IDs are better for constrained devices)

**Comment by manuio** [comment]
@drasko We probably need both variants. Sort by name it's a cool feature. I'd keep it for now as default sorting and replace it later by the method that you described. Then, name or metadata sorting can be done with HTTP parameters.

**Comment by manuio** [comment]
@drasko @bbokun I've added an HTTP query parameter `order` for ListThings and ListChannels methods.
This filter is added to `offset`, `limit`, `name` and `metadata` filters that are now passed inside `PageMetadata`.
Setting `order=name` will order by name. By default order is done by `id`.  In the future we will replace `id` order by `created_at` or we can use ULIDs or XIDs that are lexicographically sortable.
