### ISSUE TITLE
Add Notifications service

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#1311]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
I want to create a Mainflux Writer that can send me an email when a message to some topic (channel + subtopic) is received. In the ideal case, these messages are processed using some sort of rules engine so that I can specify rules when receiving emails to avoid spam messages and unnecessary traffic, but creating an SMTP writer is the first step in that direction. Potential,  use cases are limitless, but most of them are related to notifications and alarms.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a should-have.

**Comment by nmarcetic** [comment]
@dusanb94 IMHO, this should not be a part of Core. Especially Core writers. Without knowing background of idea, I would put my two cents in different direction.   

A good first step would be to work on data processing (e.g., new custom reader), which will outgrow the rules engine (still without notifications). The last part should be notifications/alarms or even better notification events (there is an ES in core) which would be collected and fireered via such Writters as SMTP.
It would be nice to have such an add-on (not as a Core service).

**Comment by dborovcanin** [comment]
Since writers are primarily meant for message persistence, it makes sense not to put this in the writers. This can be extracted as a separate Notification service. Whether its place is in the core or not, I'm not sure at the moment. Let's leave it out for the time being. We can easily move it around later. The idea behind this service is rather simple: it consumes events/messages and sends notifications to the preconfigured email addresses. These messages/events will eventually come from the rules engine. Of course, later we can add more complex logic such as filtering notification receiver depending on some criteria and support for multiple protocols (push notifications, SMS).

**Comment by nmarcetic** [comment]
I like the idea of extracting as separate service and domain naming "Notification service". The thing I don't get is ` These messages/events will eventually come from the rules engine`, which rules engine? 
Maybe you think as service will listen to a specific topic/es and will do its job (send all messages from this channel as notifications) without taking care of rules or message source? This sounds good and usable. I really like the first step to a full-blown Rules engine with Notifications/Alarms, etc... 
This is also very interesting ` support for multiple protocols (push notifications, SMS).` We can do like writers, for example, satisfying Pusher interface you will be able to implement different notifications email, push like firebase, SMS, etc.

**Comment by dborovcanin** [comment]
@nmarcetic  `Maybe you think as service will listen to a specific topic/es and will do its job (send all messages from this channel as notifications) without taking care of rules or message source?` Exactly. The rules engine is yet to be made (or integrated using existing solutions), but the Notifications service will not care for the source. We can even attach it to send an email for every message on some Channel (or subtopic), for example, in cases that messages are not sent frequently.

**Comment by nmarcetic** [comment]
@dusanb94 Got it! 
This will be awesome! 
Just to clarify when I sad "not be part of Core" I mean, it's probably best to be an add-on (in the same mono repo, as other add-ons).
