### ISSUE TITLE
Consider adding additional filters by SenML `value`

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#1314]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - tests
   - code refactor
   - documentation
   - research
   - tooling

https://github.com/mainflux/mainflux/pull/1312 introduced filtering by SenML values.

It would probably be interesting to add a few more filters around `value`:
- Less than (`<some_value>`)
- Higher than (`<some_value>`)
- In range (less than `<value_max>` but higher than `<value_min>`)
- Not in range (less than `<value_min>` but higher than `<value_max>`)

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
Nice-to-have

**Comment by manuio** [comment]
To implement range and not-in-range value filters  we need  2 new parameters `v_min` and `v_max` combined with `comparison`.
