### ISSUE TITLE
failed to create admin user: malformed entity specification

### ISSUE THREAD

**Issue by lijieaa** [absmach/magistrala#1315]
version is 0.11.0,after run docker-compose -f docker/docker-compose.yml up , I got this error info:
mainflux-things-db | 2020-12-31 02:07:50.475 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mainflux-things-db | 2020-12-31 02:07:50.475 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mainflux-things-db | 2020-12-31 02:07:50.489 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mainflux-things-db | 2020-12-31 02:07:50.509 UTC [19] LOG:  database system was shut down at 2020-12-31 02:03:27 UTC
mainflux-things-db | 2020-12-31 02:07:50.514 UTC [1] LOG:  database system is ready to accept connections
mainflux-nats   | [1] 2020/12/31 02:07:50.799264 [INF] Starting nats-server version 1.3.0
mainflux-nats   | [1] 2020/12/31 02:07:50.799300 [INF] Git commit [eed4fbc]
mainflux-vernemq | config is OK
mainflux-vernemq | -config /vernemq/data/generated.configs/app.2020.12.31.02.07.52.config -args_file /vernemq/bin/../etc/vm.args -vm_args /verne                            mq/bin/../etc/vm.args
mainflux-es-redis | 1:C 31 Dec 2020 02:07:51.021 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
mainflux-es-redis | 1:C 31 Dec 2020 02:07:51.021 # Redis version=5.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
mainflux-es-redis | 1:C 31 Dec 2020 02:07:51.021 # Warning: no config file specified, using the default config. In order to specify a config fil                            e use redis-server /path/to/redis.conf
mainflux-nats   | [1] 2020/12/31 02:07:50.799393 [INF] Listening for client connections on 0.0.0.0:4222
mainflux-nats   | [1] 2020/12/31 02:07:50.799400 [INF] Server is ready
mainflux-es-redis | 1:M 31 Dec 2020 02:07:51.022 * Running mode=standalone, port=6379.
mainflux-es-redis | 1:M 31 Dec 2020 02:07:51.022 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxco                            nn is set to the lower value of 128.
mainflux-es-redis | 1:M 31 Dec 2020 02:07:51.022 # Server initialized
mainflux-es-redis | 1:M 31 Dec 2020 02:07:51.023 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. T                            o fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this                             to take effect.
mainflux-authn-db | 2020-12-31 02:07:51.092 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mainflux-authn-db | 2020-12-31 02:07:51.092 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mainflux-es-redis | 1:M 31 Dec 2020 02:07:51.023 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will creat                            e latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as ro                            ot, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
mainflux-vernemq | Exec:  /vernemq/bin/../erts-10.7.2.3/bin/erlexec -boot /vernemq/bin/../releases/1.11.0/vernemq               -config /vernemq                            /data/generated.configs/app.2020.12.31.02.07.52.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args                                          -pa /vernemq/bin/../lib/erlio-patches -- console -noshell -noinput
mainflux-vernemq | Root: /vernemq/bin/..
mainflux-authn-db | 2020-12-31 02:07:51.097 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mainflux-jaeger | 2020/12/31 02:07:51 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
mainflux-es-redis | 1:M 31 Dec 2020 02:07:51.023 * DB loaded from disk: 0.000 seconds
mainflux-es-redis | 1:M 31 Dec 2020 02:07:51.023 * Ready to accept connections
mainflux-authn-db | 2020-12-31 02:07:51.122 UTC [19] LOG:  database system was shut down at 2020-12-31 02:03:27 UTC
mainflux-things-redis | 1:C 31 Dec 2020 02:07:51.718 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
mainflux-things-redis | 1:C 31 Dec 2020 02:07:51.718 # Redis version=5.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
mainflux-things-redis | 1:C 31 Dec 2020 02:07:51.718 # Warning: no config file specified, using the default config. In order to specify a config                             file use redis-server /path/to/redis.conf
mainflux-things-redis | 1:M 31 Dec 2020 02:07:51.719 * Running mode=standalone, port=6379.
mainflux-things-redis | 1:M 31 Dec 2020 02:07:51.719 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/som                            axconn is set to the lower value of 128.
mainflux-things-redis | 1:M 31 Dec 2020 02:07:51.719 # Server initialized
mainflux-things-redis | 1:M 31 Dec 2020 02:07:51.719 # WARNING overcommit_memory is set to 0! Background save may fail under low memory conditio                            n. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for t                            his to take effect.
mainflux-things-redis | 1:M 31 Dec 2020 02:07:51.719 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will c                            reate latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' a                            s root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
mainflux-things-redis | 1:M 31 Dec 2020 02:07:51.719 * DB loaded from disk: 0.000 seconds
mainflux-things-redis | 1:M 31 Dec 2020 02:07:51.719 * Ready to accept connections
mainflux-jaeger | {"level":"info","ts":1609380471.332436,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route                            ":"/metrics"}
mainflux-authn-db | 2020-12-31 02:07:51.129 UTC [1] LOG:  database system is ready to accept connections
mainflux-jaeger | {"level":"info","ts":1609380471.332591,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"                            }
mainflux-authn  | {"level":"info","message":"Authentication service started using http, exposed port 8189","ts":"2020-12-31T02:07:51.820369953Z"                            }
mainflux-jaeger | {"level":"info","ts":1609380471.3326452,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
mainflux-users-db | 2020-12-31 02:07:52.051 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mainflux-users-db | 2020-12-31 02:07:52.051 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mainflux-jaeger | {"level":"info","ts":1609380471.3326623,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-s                            tatus":"unavailable"}
mainflux-authn  | {"level":"info","message":"Authentication gRPC service started using http on port 8181","ts":"2020-12-31T02:07:51.820601208Z"}
mainflux-authn  | {"level":"info","message":"Authentication gRPC service started, exposed port 8181","ts":"2020-12-31T02:07:51.820727611Z"}
mainflux-things | {"level":"info","message":"gRPC communication is not encrypted","ts":"2020-12-31T02:07:52.640546262Z"}
mainflux-users  | {"level":"info","message":"gRPC communication is not encrypted","ts":"2020-12-31T02:07:52.777419452Z"}
mainflux-users-db | 2020-12-31 02:07:52.058 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mainflux-things | {"level":"info","message":"Things service started using http on port 8182","ts":"2020-12-31T02:07:52.643424615Z"}
mainflux-things | {"level":"info","message":"Things service started using http on port 8182","ts":"2020-12-31T02:07:52.643567641Z"}
mainflux-things | {"level":"info","message":"Things gRPC service started using http on port 8183","ts":"2020-12-31T02:07:52.643612552Z"}
mainflux-jaeger | {"level":"info","ts":1609380471.3340256,"caller":"memory/factory.go:55","msg":"Memory storage initialized","configuration":{"M                            axTraces":0}}
mainflux-users  | {"level":"warn","message":"Method register for user  took 1.301µs to complete with error: malformed entity specification.","ts                            ":"2020-12-31T02:07:52.937086123Z"}
mainflux-users  | {"level":"error","message":"failed to create admin user: malformed entity specification","ts":"2020-12-31T02:07:52.937160077Z"                            }
mainflux-users-db | 2020-12-31 02:07:52.087 UTC [19] LOG:  database system was shut down at 2020-12-31 02:03:27 UTC
mainflux-coap   | {"level":"info","message":"gRPC communication is not encrypted","ts":"2020-12-31T02:07:53.702946398Z"}
mainflux-jaeger | {"level":"info","ts":1609380471.3393395,"caller":"grpc/builder.go:75","msg":"Agent requested insecure grpc connection to colle                            ctor(s)"}
mainflux-jaeger | {"level":"info","ts":1609380471.3394005,"caller":"grpc/clientconn.go:242","msg":"parsed scheme: \"\"","system":"grpc","grpc_lo                            g":true}
mainflux-jaeger | {"level":"info","ts":1609380471.3394413,"caller":"grpc/clientconn.go:248","msg":"scheme \"\" not registered, fallback to defau                            lt scheme","system":"grpc","grpc_log":true}
mainflux-coap   | {"level":"info","message":"CoAP service started, exposed port 5683","ts":"2020-12-31T02:07:53.705770743Z"}
mainflux-coap   | {"level":"info","message":"CoAP adapter service started, exposed port 5683","ts":"2020-12-31T02:07:53.705780686Z"}
mainflux-mqtt   | {"level":"info","message":"gRPC communication is not encrypted","ts":"2020-12-31T02:07:54.798770476Z"}
mainflux-users-db | 2020-12-31 02:07:52.096 UTC [1] LOG:  database system is ready to accept connections
mainflux-jaeger | {"level":"info","ts":1609380471.3394692,"caller":"grpc/resolver_conn_wrapper.go:113","msg":"ccResolverWrapper: sending update                             to cc: {[{127.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
mainflux-http   | {"level":"info","message":"gRPC communication is not encrypted","ts":"2020-12-31T02:07:53.845936205Z"}
mainflux-jaeger | {"level":"info","ts":1609380471.3396437,"caller":"base/balancer.go:76","msg":"base.baseBalancer: got new resolver state: {[{12                            7.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
mainflux-jaeger | {"level":"info","ts":1609380471.3397071,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change:                             0xc0001e0040, CONNECTING","system":"grpc","grpc_log":true}
mainflux-mqtt   | {"level":"info","message":"Starting MQTT proxy on port 1883","ts":"2020-12-31T02:07:54.816739599Z"}
mainflux-mqtt   | {"level":"info","message":"Starting MQTT over WS  proxy on port 8080","ts":"2020-12-31T02:07:54.816781344Z"}
mainflux-jaeger | {"level":"info","ts":1609380471.339929,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to conn                            ect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection                             refused\". Reconnecting...","system":"grpc","grpc_log":true}
mainflux-http   | {"level":"info","message":"HTTP adapter service started on port 8185","ts":"2020-12-31T02:07:53.849020843Z"}
mainflux-jaeger | {"level":"info","ts":1609380471.340034,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change:                             0xc0001e0040, TRANSIENT_FAILURE","system":"grpc","grpc_log":true}
mainflux-jaeger | {"level":"info","ts":1609380471.3403716,"caller":"all-in-one/main.go:198","msg":"Starting agent"}
mainflux-jaeger | {"level":"info","ts":1609380471.3405387,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}
mainflux-jaeger | {"level":"info","ts":1609380471.3433201,"caller":"all-in-one/main.go:241","msg":"Starting jaeger-collector TChannel server","p                            ort":14267}
mainflux-jaeger | {"level":"info","ts":1609380471.34353,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","g                            rpc-port":"14250"}
mainflux-jaeger | {"level":"info","ts":1609380471.3436446,"caller":"all-in-one/main.go:259","msg":"Starting jaeger-collector HTTP server","http-                            port":14268}
mainflux-jaeger | {"level":"info","ts":1609380471.3436673,"caller":"querysvc/query_service.go:130","msg":"Archive storage not created","reason":                            "archive storage not supported"}
mainflux-jaeger | {"level":"info","ts":1609380471.3436756,"caller":"all-in-one/main.go:341","msg":"Archive storage not initialized"}
mainflux-jaeger | {"level":"info","ts":1609380471.3455322,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"read                            y"}
mainflux-jaeger | {"level":"info","ts":1609380471.3455923,"caller":"app/server.go:134","msg":"Starting CMUX server","port":16686}
mainflux-jaeger | {"level":"info","ts":1609380471.345611,"caller":"app/server.go:111","msg":"Starting HTTP server","port":16686}
mainflux-jaeger | {"level":"info","ts":1609380471.3456495,"caller":"app/server.go:124","msg":"Starting GRPC server","port":16686}
mainflux-users exited with code 1
mainflux-users  | {"level":"warn","message":"Method register for user  took 1.489µs to complete with error: malformed entity specification.","ts                            ":"2020-12-31T02:07:57.532207968Z"}
mainflux-users  | {"level":"error","message":"failed to create admin user: malformed entity specification","ts":"2020-12-31T02:07:57.532244869Z"                            }
mainflux-users  | {"level":"warn","message":"Method register for user  took 1.156µs to complete with error: malformed entity specification.","ts                            ":"2020-12-31T02:07:59.77932151Z"}
mainflux-users  | {"level":"error","message":"failed to create admin user: malformed entity specification","ts":"2020-12-31T02:07:59.779396622Z"                            }
mainflux-users exited with code 1
mainflux-users exited with code 1
mainflux-users  | {"level":"warn","message":"Method register for user  took 1.764µs to complete with error: malformed entity specification.","ts                            ":"2020-12-31T02:08:10.808385324Z"}
mainflux-users  | {"level":"error","message":"failed to create admin user: malformed entity specification","ts":"2020-12-31T02:08:10.808442701Z"                            }
mainflux-users exited with code 1
mainflux-users exited with code 1
mainflux-users exited with code 1
mainflux-users exited with code 1
mainflux-users exited with code 1

**Comment by dborovcanin** [comment]
Please fill issue template for bugs properly.

**Comment by drasko** [comment]
Also, please use [GitHub Markdown](https://guides.github.com/features/mastering-markdown/) to properly format console logs.

I will close this issue for improper formatting and not respecting bug template, please open a new one if the bug still persist (but follow aforementioned instructions).
