### ISSUE TITLE
Can you support IEC104 ?

### ISSUE THREAD

**Issue by magixmin** [absmach/magistrala#1328]
our need IEC104  , Doyou plan to support it ?

**Comment by magixmin** [comment]
I want to write a data source that supports IEC104， Do you have a guide to do this ?

**Comment by manuio** [comment]
We don't support `IEC104` and we don't have a guide to write your own protocol adapter but we have documentation about existing ones: https://mainflux.readthedocs.io/en/latest/architecture/
I propose you to copy hhtp-adapter (https://github.com/mainflux/mainflux/tree/master/http) and replace the HTTP server by your IEC104 implementation. The NATS publisher should remain so you can publish messages in the internal message broker.

**Comment by magixmin** [comment]
Thanks men , i will try it .If that`s ok , i wll Contribute code to you

**Comment by drasko** [comment]
@magixmin I would suggest that you go through [Developer's Guide](https://mainflux.readthedocs.io/en/latest/dev-guide/) and try to add protocol adapter you need. There are some Go implementations that can get you going, like [this one](https://github.com/thinkgos/go-iecp5) or [this one](https://github.com/pascaldekloe/part5).

Once you are done, you can send us pull request and we will merge it to official repo.

**Comment by magixmin** [comment]
OK  I will try it
