### ISSUE TITLE
Create Python SDK

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#1329]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
We currently provide Go SDK. It would be useful to provide Python SDK as well, to facilitate creating Python apps on the top of Mainflux.
 
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
nice-to-have

**Comment by nmarcetic** [comment]
@drasko It's nice to have it. Yes, I am really happy to see progress here. I assume JS SDK would also be highly useful for the crowd. IMHO we should open an issue as an open call for contribution. 

I also think those none Go SDK's should not be part of the Core or monorepo. They should be moved to dedicated repo's

**Comment by drasko** [comment]
@nmarcetic let's thing about this - for now I would like to folow @fbugarski 's PR as he progresses. He will switch to JS after. It will be easy to pull these out to separate repos later.

**Comment by drasko** [comment]
Closed via https://github.com/mainflux/sdk-py/pull/1
