### ISSUE TITLE
Evaluate system's performance

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#134]
Benchmark should be performed in testing environment, using various loads (which are yet to be specified). Results must include:
- average request rate
- errors frequency
- messages throughput
- underlying system metrics

**Comment by drasko** [comment]
## HTTP
https://github.com/rakyll/hey
https://github.com/tsenart/vegeta

## MQTT
https://github.com/takanorig/mqtt-bench
https://github.com/emqtt/emqtt_benchmark
https://github.com/krylovsk/mqtt-benchmark

**Comment by mijicd** [comment]
This issue should be treated as follow up to #170. The decision is to use [Gatling](https://gatling.io/) as primary testing utility due to its maturity and the number of available plugins.
