### ISSUE TITLE
Create Groups API - add grouping of entities

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#1346]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Following the https://github.com/mainflux/mainflux/issues/931, we are breaking it in 2 issues. This one will handle the groups, and new one will be opened for policies (i.e. we will first merge groups only, and then add policies).
Groups will be part of Auth microservice.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must-have

**Comment by drasko** [comment]
Will be done in https://github.com/mainflux/mainflux/issues/1346

**Comment by manuio** [comment]
@drasko are you sure about closing this one?

**Comment by drasko** [comment]
Damn, wrong issue :)

I will reopen.
