### ISSUE TITLE
Metadata in URL query not being properly parsed

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1357]
**BUG REPORT**

1. What were you trying to achieve?

Search things/users by metadata

2. What are the expected results?

List of things that match the metadata query

3. What are the received results?
```
curl -i  -s -X GET http://localhost:8182/things\?name\=test\&metadata\=\{\"role\":\"manager\"\} -H "Authorization: $TOK" -H 'Content-Type: application/json'

HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Fri, 05 Feb 2021 20:04:15 GMT
Content-Length: 33

{"error":"invalid query params"}
```

**Comment by manuio** [comment]
@mteodor Looks like you have unecessary `\`. Try with: `http://localhost:4200/things?offset=0&limit=100&order=name&dir=asc&metadata={"type":"lora"}`

**Comment by mteodor** [comment]
Actually problem is with more complex metadata, when bone interprets metada as an array since it contains `,`, @dusanb94 found a solution for proper url parsing

**Comment by drasko** [comment]
As explained in https://github.com/mainflux/mainflux/pull/1358#pullrequestreview-599090382, we need an implementation of a dedicated endpoint for metadata search and JSON will be sent in a request body.

Let's use this same issue for the implementation. Assigning this one to @blokovi
