### ISSUE TITLE
Add StringValue and DataValue comparison filters 

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#1361]
This issue is the continuation of this one: https://github.com/mainflux/mainflux/issues/1314

New comparison filters `lt`, `le`, `gt` and `ge` are missing for DataValue and StringValue. 

Consider also adding range filters

**Comment by fthdrmzzz** [comment]
StringValue and DataValue are both strings. Do we want this comparison to be Case-Sensitive? Because by default Uppercase-letters < Lowercase-letters.
