### ISSUE TITLE
Sort Things and Channels connections by name 

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#1362]
Things and Channels list are sortable by name. We need the same feature for connections lists. 

Related to this issue: https://github.com/mainflux/mainflux/issues/1290

**Comment by nmarcetic** [comment]
The connection list will be probably removed with [policies](https://github.com/mainflux/mainflux/issues/1347), which are coming very soon and I suppose they will be a top priority for `0.13.0` which means picked first from the issue bucket. I am thinking, Is it worth working on the sort feature?

**Comment by drasko** [comment]
Agreed, closing this one.
