### ISSUE TITLE
Add USERS.md

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#1365]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - documentation
 
As the Mainflux community grows and approaching version `1.0.0`, it would be nice to keep track of users. 

USERS.md file should serve as a public ledger that holds Mainflux community users, together with basic info. 
A file is a community maintained by sending PR with basic info.

This is a common practice of tracking usage of OSS, there are plenty of projects that are doing the same. 
[ArgoCD](https://github.com/argoproj/argo-cd/blob/master/USERS.md)
[Cilium](https://github.com/cilium/cilium/blob/master/USERS.md)
Etc...

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
nice-to-have

**Comment by drasko** [comment]
Very nice proposal @nmarcetic!

**Comment by nmarcetic** [comment]
@drasko, I will send PR ASAP. Do you think `ADOPTERS.md`, which is also commonly used naming for this purpose,  would be more suitable than `USERS.md`? Maybe Adopters is more like self-explaining and sounds nicer.
