### ISSUE TITLE
Document API with curl examples

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#1374]
**ENHANCEMENT**
1. Describe the enhancement you are requesting.
We currently have `openapi.yml` docs that describe the API, but do not have all functions listed and documented with `curl` examples in our official docs. This needs to be added.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
Must have

**Comment by fbugarski** [comment]
Resolved via https://github.com/mainflux/docs/pull/77

**Comment by manuio** [comment]
@fbugarski can we close this one?
