### ISSUE TITLE
Issue regarding the CoAP adapter 

### ISSUE THREAD

**Issue by krishna710942** [absmach/magistrala#1375]
hi can anyone help me in this . I am using mainflux coap adapter for post and get messages:
my coap url : coap://" + "54.162.61.126" + ":" + "5683" + "/" +"channels/5b1ded45-f122-4830-83e6-b6b7dc1e95da/messages?authorization=577893d5-bc1e-4f77-9ede-15106b63a43f

error on the console ::{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-02-28T14:18:42.837932711Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-02-28T14:18:47.868028109Z"}
whats is wrong in this url ??

in coap url authorization will be thing key right?

thing detail :
{
  "data": {
    "id": 107,
    "userName": "70d89ec6-3e19-42ae-927d-065df923719d",
    "name": "coapThing",
    "password": "577893d5-bc1e-4f77-9ede-15106b63a43f",
    "protocol": "COAP"
  },
  "message": "Iot thing register successfully",
  "timestamp": "2021-02-28T04:44:48.395+00:00",
  "statusCode": 200,
  "isSuccess": true
}

channel :+1: 
{
  "data": {
    "id": 106,
    "name": "coapChannel",
    "channelId": "5b1ded45-f122-4830-83e6-b6b7dc1e95da",
    "protocol": "COAP"
  },
  "message": "Iot thing register successfully",
  "timestamp": "2021-02-28T04:45:15.841+00:00",
  "statusCode": 200,
  "isSuccess": true
}

coap and channel connection ::
{
  "data": {
    "id": 106,
    "channelId": "5b1ded45-f122-4830-83e6-b6b7dc1e95da",
    "userName": "70d89ec6-3e19-42ae-927d-065df923719d",
    "topic": "channels/5b1ded45-f122-4830-83e6-b6b7dc1e95da/messages"
  },
  "message": "Channel connection established with thing",
  "timestamp": "2021-02-28T04:45:58.593+00:00",
  "statusCode": 200,
  "isSuccess": true
}

**Comment by dborovcanin** [comment]
It's an error in the service documentation. Can you try using `auth` instead of `authorization`? Looks like you're doing everything else correctly. I'll send a PR with a README fix.

> **Please fill out the issue template correctly** and format the code. Otherwise, we can't guarantee that we'll even try to solve your issue.

**Comment by krishna710942** [comment]
@dusanb94  yes i change authorization to auth but same issue again occur on the coap adapter console
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:46.028389892Z"}

**Comment by dborovcanin** [comment]
Which client are you using? What's the response you get from the client (can you try using [Mainflux CoAP CLI tool](https://github.com/mainflux/coap-cli))? Which version of the CoAP Adapter are you using? Are you sure Channel and Thing are connected? What are the logs from the Auth service? Can you send the entire log of the CoAP adapter, since this error does not seem to exist in the current version of the adapter?

**Comment by krishna710942** [comment]
currently i am using eclipse californium with latest version
 <dependency>
            <groupId>org.eclipse.californium</groupId>
            <artifactId>californium-core</artifactId>
            <version>2.6.0</version>
        </dependency>
for the coap client . Mainflux coap adapter version 0.11.0 . and channel and things are connected and i checked on the ui also .

Coap adapter logs :::

{"level":"warn","message":"already subscribed to topic","ts":"2021-03-01T06:49:23.924816052Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:06.348503042Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:10.95852569Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:15.958388739Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:21.108445101Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:25.978421811Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:30.97835915Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:35.948438285Z"}

No i am not using the coap cli tool . I am creating a spring boot project i am creating two clients one client is used for the post request and other used for the get request .

post request ::::
 client.post(message+LocalDateTime.now().getSecond(), MediaTypeRegistry.TEXT_PLAIN,0);
get request :::
 client.observe(
                    new CoapHandler() {
                        @Override
                        public void onLoad(CoapResponse response) {
                        String content = response.getResponseText();
                            log.info("value ::::: {}  ",content);
                        }
                        @Override
                        public void onError() {
                            log.error("OBSERVING FAILED (press enter to exit)");
                        }
                    },0);
            log.info("End with response  ::::::::::::: {}");
        };

**Comment by dborovcanin** [comment]
1. Please **format the code** when you are pasting it to the issue description/comments.
2. Can you try using the latest version of the adapter?

This error is no longer in the code, so it's probably an old version of the service with different behavior. Please use the version of docs that corresponds to the service version. Release 0.12.0 is planned this month, so we will soon have a new tag, but at the moment, please try pulling and running the `latest` version.

**Comment by krishna710942** [comment]
@dusanb94  ok i will try it

**Comment by drasko** [comment]
@krishna710942 please use [Markdown formatting](https://guides.github.com/features/mastering-markdown/) to format the code lines. Otherwise they are very difficult to read.

**Comment by krishna710942** [comment]
Hi @drasko and @dusanb94  we are using the mainflux kubernetes latest helm chart to deploy the coap adapter and inside the coap yml file latest version is 0.11.0 .

(https://mainflux.readthedocs.io/en/latest/kubernetes/)


****this is my get coap message code** ::::**

public class TestinService {
    public static void main(String[] args) throws IOException, ConnectorException, InterruptedException {
        ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(1, 500, 0 L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue < > ());
        CoapClient client = new CoapClient("coap://" + "54.162.61.126" + ":" + "31739" + "/" +
            "channels/57b1d96e-6771-4c48-be32-63bd6596bab9/messages?auth=577893d5-bc1e-4f77-9ede-15106b63a43f");
        while (true) {
            Thread.sleep(5000);
            threadPoolExecutor.execute(coapPostMethod(client));
        }
    }

    private static Runnable coapPostMethod(CoapClient client) {
        Runnable runnable = () - > {
            client.observe(
                new CoapHandler() {
                    @Override
                    public void onLoad(CoapResponse response) {
                        String content = response.getResponseText();
                        log.info("value ::::: {}  ", content);
                    }
                    @Override
                    public void onError() {
                        log.error("OBSERVING FAILED (press enter to exit)");
                    }
                }, 0);
            log.info("End with response  ::::::::::::: {}");
        };
        return runnable;
    }
}


this is my post coap  :::::

public class CoapTestingReading2 {
    public static void main(String[] args) throws IOException, ConnectorException, InterruptedException {
        ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(1, 500, 0 L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue < > ());
        CoapClient client = new CoapClient("coap://" + "54.162.61.126" + ":" + "31739" + "/" +
            "channels/57b1d96e-6771-4c48-be32-63bd6596bab9/messages?auth=577893d5-bc1e-4f77-9ede-15106b63a43f");
        while (true) {
            Thread.sleep(5000);
            threadPoolExecutor.execute(coapPostMethod(client, "krishna1 "));
        }
    }

    private static Runnable coapPostMethod(CoapClient client, String message) {
        Runnable runnable = () - > {
            try {
                client.post(message + LocalDateTime.now().getSecond(), MediaTypeRegistry.TEXT_PLAIN, 0);
            } catch (ConnectorException e) {
                e.printStackTrace();
                Sentry.capture(e);
            } catch (IOException e) {
                e.printStackTrace();
                Sentry.capture(e);
            }
        };
        return runnable;
    }
}


**logs of the coap adapter ::::::::::::**

{"level":"warn","message":"Method subscribe to channel 57b1d96e-6771-4c48-be32-63bd6596bab9 for client cf169c1d1dccf676-70d89ec6-3e19-42ae-927d-065df923719d-57b1d96e-6771-4c48-be32-63bd6596bab9 took 1.836µs to complete with error: already subscribed to topic.","ts":"2021-03-01T06:49:18.924805981Z"}
{"level":"warn","message":"already subscribed to topic","ts":"2021-03-01T06:49:18.924846366Z"}
{"level":"info","message":"Method publish to channel 57b1d96e-6771-4c48-be32-63bd6596bab9 took 12.966µs to complete without errors.","ts":"2021-03-01T06:49:19.511297216Z"}
{"level":"warn","message":"Method subscribe to channel 57b1d96e-6771-4c48-be32-63bd6596bab9 for client d97fbd246b2a01fc-70d89ec6-3e19-42ae-927d-065df923719d-57b1d96e-6771-4c48-be32-63bd6596bab9 took 1.897µs to complete with error: already subscribed to topic.","ts":"2021-03-01T06:49:23.924772927Z"}
{"level":"warn","message":"already subscribed to topic","ts":"2021-03-01T06:49:23.924816052Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:06.348503042Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:10.95852569Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:15.958388739Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:21.108445101Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:25.978421811Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:30.97835915Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:35.948438285Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:40.958423941Z"}
{"level":"warn","message":"Failed to authorize: bad request","ts":"2021-03-01T13:37:46.028389892Z"}

**Comment by drasko** [comment]
@krishna710942 I appreciate your work on this issue, but please format properly your Java and other code in Markdown, using the instructions I have sent.

With proper tags you will get syntax highlighting.

Until then it is difficult for us to read, and we also insist that our community picks up the best practices and invest some effort in learning and self-improvement.

**Comment by drasko** [comment]
@krishna710942 if there is no action from your side, we'll close this issue due to inactivity.

**Comment by krishna710942** [comment]
mainflux-coap   | {"level":"warn","message":"Error reading observe option: option not found","ts":"2021-04-13T17:08:47.499241829Z"}

currently i am using latest version of the mainflux that is 0.12 but i get this issue when i am fetching the data .

`
 ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(1, 500, 0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>());
       
 CoapClient client = new CoapClient("coap://localhost/channels/fc5d574c-8f28-435f-ac1c-64032ef55f4b/messages? 
 auth=3d9cbd20-83ff-4cd9-a3bb-ab84b56b8140");
      
          while (true) {
           
                    Thread.sleep(10000);
             
                    client.observe(new CoapHandler() {
              
                         @Override
                        public void onLoad(CoapResponse response) {
                                log.info("value ::::: {}  ", response.getResponseText().getBytes());
                                log.info("value ::::: {}  ", response.getOptions());
                                log.info("value ::::: {}  ", response.getPayload());
                                 log.info("value ::::: {}  ", response.getCode());
                      }

                  @Override
                   public void onError() {
                         log.error("OBSERVING FAILED (press enter to exit)");
                    }
                }, 0);
        }

`

**Comment by dborovcanin** [comment]
@krishna710942 Looks like you are sending GET request without `observe` option. Such a request does not make sense in Mainflux (what do you want to GET?) and, as such, is rejected. GET makes sense only if you want to "subscribe". Can you set Observe option to `true` and try again?

**Comment by krishna710942** [comment]
hi @dusanb94  **in the first time when i am subscribe the topic by the coap observer method it perfectly fine** .

 **mainflux-things** | {"level":"info","message":"Method can_access for channel fc5d574c-8f28-435f-ac1c-64032ef55f4b and thing 4ca32394-b67d-48fd-a533-a558997b5bcd took 2.515794ms to complete without errors.","ts":"2021-04-14T05:38:40.537701853Z"}

**mainflux-coap**   | {"level":"info","message":**"Method subscribe to fc5d574c-8f28-435f-ac1c-64032ef55f4b for client 2faa6b48ae069a53 took 3.878907ms to complete without errors."**,"ts":"2021-04-14T05:38:50.536681307Z"}

**mainflux-things** | {"level":"info","message":"**Method can_access for channel fc5d574c-8f28-435f-ac1c-64032ef55f4b and thing 4ca32394-b67d-48fd-a533-a558997b5bcd** took 1.385944ms to complete without errors.","ts":"2021-04-14T05:38:50.535745604Z"}


**This is my subscribe code :::**

`
   CoapClient client = new CoapClient("coap://localhost:5683/channels/fc5d574c-8f28-435f-ac1c-64032ef55f4b/messages?auth=3d9cbd20-83ff-4cd9-a3bb-ab84b56b8140");

    client.get().getOptions().setObserve(0);
    
     while (true) {
           
            Thread.sleep(10000);
           
             client.observe(new CoapHandler() {
             
                @Override
                public void onLoad(CoapResponse response) {
                    log.info("value ::::: {}  ", response.getResponseText());
                    log.info("value ::::: {}  ", response.getOptions());
                    log.info("value ::::: {}  ", response.getPayload());
                    log.info("value ::::: {}  ", response.getCode());
                }

                @Override
                public void onError() {
                    log.error("OBSERVING FAILED (press enter to exit)");
                }
            },0);
        }
`


**when i start the post methdo it work also fine ::**

**mainflux-coap**   | {"level":"info","message":"Method publish to fc5d574c-8f28-435f-ac1c-64032ef55f4b took 1.771833ms to complete without errors.","ts":"2021-04-14T06:18:09.284720201Z"}
**mainflux-things** | {"level":"info","message":"Method can_access for channel fc5d574c-8f28-435f-ac1c-64032ef55f4b and thing 4ca32394-b67d-48fd-a533-a558997b5bcd took 1.071988ms to complete without errors.","ts":"2021-04-14T06:18:09.284403368Z"}

`
CoapClient client=new CoapClient("coap://localhost:5683/channels/fc5d574c-8f28-435f-ac1c-64032ef55f4b/messages?auth=3d9cbd20-83ff-4cd9-a3bb-ab84b56b8140");
      
      while (true) {

            Thread.sleep(10000);

            client.post("sending message to coap server", MediaTypeRegistry.TEXT_PLAIN,0);
        }
`
**But when i start both method together post and get then it will give me error  ::**

**mainflux-coap   | {"level":"warn","message":"Error decoding message: option not found","ts":"2021-04-14T05:31:57.926041418Z"}
mainflux-coap   | {"level":"warn","message":"Error decoding message: option not found","ts":"2021-04-14T05:31:57.926968905Z"}**


I think i miss the message format or any message class i have to use to send the message with the options please can you help me in this ?????.

currently i am using the maven dependency of the eclipse californium .

**Comment by dborovcanin** [comment]
What's the topic you are sending a message to? When do you get an error - on POST or on GET? What does this `0` mean in `client.post("sending message to coap server", MediaTypeRegistry.TEXT_PLAIN,0)` and what are the client settings? What does it mean you "start both methods together"? You probably want two Things with two different auth keys - one for sending and another for observing on the same channel.

**Comment by drasko** [comment]
Closed due to inactivity.
