### ISSUE TITLE
Code refactor - make http util package

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#1381]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   the existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
There is duplicated code across all services that is used for reading HTTP params, for example
`readStringQuery`, `readMetadataQuery`... this should be moved into one common package
for example `pkg/api/http`.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a should-have enhancement.

**Comment by dborovcanin** [comment]
I think that `internal` is a bit better fit than `pkg`.

**Comment by manuio** [comment]
@dusanb94 You are probably right. So `interrnal/api/http/` would be ok for you?

**Comment by dborovcanin** [comment]
Yes, that sounds good to me.

**Comment by manuio** [comment]
Resolved here: https://github.com/mainflux/mainflux/pull/1384
