### ISSUE TITLE
VerneMQ image build with invalid configuration file

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#1403]
Building VerneMQ from the source produce invalid configuration file `vernemq.conf` with:
```include conf.d/*.conf```
Until this issue is resolved, it's temporary fixed with PR #1402 where building source is specified with revision tag.
When fixed in upstream (VerneMQ) this should be addressed in Dockerfile for building mqtt broker image in Mainflux

**Comment by nmarcetic** [comment]
Follow up issue on [Vernemq repo](https://github.com/vernemq/vernemq/issues/1767)

**Comment by drasko** [comment]
Can this one be closed now?

**Comment by drasko** [comment]
@blokovi if this can be closed, please close the issue.
