### ISSUE TITLE
Bug with error handling for Thing update SQL

### ISSUE THREAD

**Issue by orangetcy** [absmach/magistrala#1408]
**BUG REPORT**

there is a very little code bug in things sql update function. In  mainflux/things/postgres/things.go line:99 - 101
error handle with  **res.RowsAffected**,  it should be errdb not err

**ENHANCEMENT**
from 
```go
        cnt, errdb := res.RowsAffected()
	if err != nil {
		return errors.Wrap(things.ErrUpdateEntity, errdb)
	}
```

to

```go
        cnt, errdb := res.RowsAffected()
	if errdb != nil {
		return errors.Wrap(things.ErrUpdateEntity, errdb)
	}
```

**Comment by dborovcanin** [comment]
@orangetcy  I can confirm the bug. Since this is rather a simple fix and the solution you proposed will do the job, do you want to issue a fix pull request and join the Mainflux contributors team?
