### ISSUE TITLE
Create Cassandra reader service

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#141]
A small Cassandra reader should be made in Go (few lines of Go code). Reader should tap into `messages_by_channel` table in the Cassandra's `message_writer` keyspace and query messages from there.

**Comment by mijicd** [comment]
Note that the service should follow conventions implemented in other services: go-kit, RED metrics, logging, and API documentation. Paging the results set does not need to be implemented for this release.

**Comment by mijicd** [comment]
Deprecated by #159.
