### ISSUE TITLE
Make "flattening" of JSON in JSON transformer optional

### ISSUE THREAD

**Issue by bbokun** [absmach/magistrala#1421]
1. What were you trying to achieve?
When I publish a message via http/mqtt/... I want it to be stored via the mongodb-writer into a mongodb database.
The mongodb-writer is configured to accept json, what means that the json transformer has to do the job.

2. What are the expected results?
I want the sent json to be written as-is in the database

3. What are the received results?
The json is "flattened". According to the documentation, this should happen, but this is definitely a problem, because the data-structures are gone. This makes sense if the data is read out only with the mongodb-reader, and makes it impossible to use other tools for data-evaluation

It would be better to make the "flattening" in the transformer optional, with default value - "flattening off".

**Comment by nmarcetic** [comment]
@dusanb94 ^ 
I remember this flattening, is there any chance to turn it off when using mongo (with or without JSON transformer)? E.g accomplish what @bbokun needs (save JSON as it's sent)? This will be common usage

**Comment by dborovcanin** [comment]
The change is rather simple, and we can do it quickly. [Here](https://github.com/dusanb94/mainflux/commit/2d3e182495141af5fe6f75e2081fafd8a465ab23) is an example of nested JOSN, we only need to make it configurable.

**Comment by nmarcetic** [comment]
That's awesome! Let's then make it configurable if flatten still makes sense? If I remember well you introduce it because of readers/filtering?

**Comment by dborovcanin** [comment]
I think it does make sense, but only for InfluxDB (and possibly other time-series DBs). For everything else, probably not. I'll make the Transformer configurable. I'm not sure if I'll make that option user-configurable through env vars or simply use flat for time series and nested for everything else. This is only for the sake of simplicity from the user perspective: if there is a JSON supported in DB, it's probably natural to expect 1-1 mapping between sent and stored data. This way we'll enable custom consumers (consumers other than readers) with no issues with format compatibility.

**Comment by nmarcetic** [comment]
Great! I don't think it's necessary to be user-configurable. I will expect to get what I send, which means if I want it to flatten I will send it structured like that from the source. Simplicity wins 👍
