### ISSUE TITLE
Fix documentation for Writers

### ISSUE THREAD

**Issue by bbokun** [absmach/magistrala#1422]
In the documentation on the page

https://mainflux.readthedocs.io/en/latest/storage/

is written:

"...For the sake of simplicity, nested JSON objects are flatten to a single JSON object, using composite keys with the default separator /. This implies that the separator character (/) is not allowed in the JSON object key...."

The separator is hardcoded as a const in the code and therefore can not be changed

https://github.com/mainflux/mainflux/blob/master/pkg/transformers/json/transformer.go
Line 15: const sep = "/"

 This is a little bit misleading. Please fix the documentation.

**Comment by dborovcanin** [comment]
I guess this `default` terminology is confusing, because it implies there can be something else, right?

**Comment by bbokun** [comment]
Hello @dusanb94 
Yes, it implies that there can be something else. Therefore it would be better to rephrase the sentence to something like:

"..For the sake of simplicity, nested JSON objects are flattened to a single JSON object, using composite keys, separated by the / separator...."
