### ISSUE TITLE
Support external UUIDs for Things and Channels

### ISSUE THREAD

**Issue by aspnair** [absmach/magistrala#1425]
**FEATURE REQUEST**

Explanation:
Currently, whenever a Thing or Channel is created the "mainflux-things" service allocates a new UUID as the Thing ID or the Channel ID.  The controlling Application or Service would get this UUID when they query the Things or Channels.

But, in some cases it would be better if the external Application or Service which is managing the Mainflux would get the freedom to define the UUID for that particular Thing or Channel.

How to use:
So effectively when a Thing or Channel is getting created, the user could also specify an external UUID as part of the POST request and the Mainflux should use it instead of allocating a new UUID.

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Please see above.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is very import for my use case as we are having our application which would like to manage Mainflux.

**Comment by manuio** [comment]
I recently had the same remark. We need a way to map Mainflux IDs with any external ID.  We can add an optional field `externalID` in Things and Channels or use it directly from the metadata. That way the mapping could be created during the provision process and auth service should simply switch the IDs.

**Comment by aspnair** [comment]
@manuio . The reason is because we are thinking about a few scenario. One of them is given below.  Just consider the example.
MF in site1: managing things 1 to 20; MF in site2: managing things 21 to 40
Now these site1 and site2 may be on an extended LAN or virtual LAN, but there could be connectivity issues.
So considering to have a Mainflux on Cloud which will have the details of everything.
MF Cloud: have all things 1 to 40 with the same id, key, metadata.
There would be my application in each site and cloud which will take care of the actual sync work between the site MF and MF Cloud.  Each instance of MF does not know about the other ones.

So effectively if my application can generate a UUID and ask MF to use that as the things UUID, all this could be done easily.

**Comment by aspnair** [comment]
I am considering a few intersite virtual LAN scenario.  All the devices could be on the same LAN and they could see/talk each other.  But the intersite connectivity is not stable, there could be communication breakages.  So, another alternate to above mentioned scenario.
Both site1 and site2 MF would have all the 40 Things with the same id, key, metadata. Using the DNS settings we can select which one is the current active one.  By updating the DNS we can make all things and apps to point to the second MF very easily.  Anyway, my application will be there in both sites and on cloud to do the necessary higher level control.

**Comment by manuio** [comment]
Resolved here: https://github.com/mainflux/mainflux/pull/1518
