### ISSUE TITLE
Add support for Basic Authentication in HTTP Adapter

### ISSUE THREAD

**Issue by bbokun** [absmach/magistrala#1439]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
I want to post a request via HTTP(s) with Basic Authentication. 

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Should have as Basic Authentication Scheme is defined in the RFC 7617 as one of the standard authentication schemes.

**Comment by dborovcanin** [comment]
Since Basic Auth is a standard, this is definitely a useful feature we can implement.
