### ISSUE TITLE
Add Readers test for JSON format

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#1442]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
  Add tests for Readers for messages in plain JSON format.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a should-have enhancement.

**Comment by manuio** [comment]
@dusanb94 Wasn't that done here? https://github.com/mainflux/mainflux/pull/1407

**Comment by dborovcanin** [comment]
Closing, because it is done in #1407.
