### ISSUE TITLE
make run failed

### ISSUE THREAD

**Issue by iot-lorawan** [absmach/magistrala#1446]
Hi,
   I git clone and check out to v0.12.1, it raise error when run make run cmd,
   log is listed:

ubuntu@ubuntu:~/mainflux$ git checkout tags/0.12.1 -b 0.12.1
Switched to a new branch '0.12.1'
ubuntu@ubuntu:~/mainflux$ make run
docker-compose -f docker/docker-compose.yml up
WARNING: The MF_NGINX_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_NGINX_SSL_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_NGINX_MQTT_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_NGINX_MQTTS_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_DB_USER variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_DB_PASS variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_DB variable is not set. Defaulting to a blank string.
WARNING: The MF_RELEASE_TAG variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_GRPC_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_LOG_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_DB_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_SECRET variable is not set. Defaulting to a blank string.
WARNING: The MF_JAEGER_URL variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_DB_USER variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_DB_PASS variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_DB variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_RESET_PWD_TEMPLATE variable is not set. Defaulting to a blank string.
WARNING: The MF_EMAIL_TEMPLATE variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_LOG_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_DB_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_EMAIL_HOST variable is not set. Defaulting to a blank string.
WARNING: The MF_EMAIL_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_EMAIL_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The MF_EMAIL_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The MF_EMAIL_FROM_ADDRESS variable is not set. Defaulting to a blank string.
WARNING: The MF_EMAIL_FROM_NAME variable is not set. Defaulting to a blank string.
WARNING: The MF_TOKEN_RESET_ENDPOINT variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_GRPC_URL variable is not set. Defaulting to a blank string.
WARNING: The MF_AUTH_GRPC_TIMEOUT variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_ADMIN_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The MF_USERS_ADMIN_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_DB_USER variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_DB_PASS variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_DB variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_LOG_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_DB_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_REDIS_TCP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_AUTH_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_AUTH_GRPC_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_JAEGER_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_JAEGER_FRONTEND variable is not set. Defaulting to a blank string.
WARNING: The MF_JAEGER_COLLECTOR variable is not set. Defaulting to a blank string.
WARNING: The MF_JAEGER_CONFIGS variable is not set. Defaulting to a blank string.
WARNING: The MF_DOCKER_VERNEMQ_ALLOW_ANONYMOUS variable is not set. Defaulting to a blank string.
WARNING: The MF_DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL variable is not set. Defaulting to a blank string.
WARNING: The MF_MQTT_ADAPTER_LOG_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The MF_MQTT_ADAPTER_MQTT_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_MQTT_ADAPTER_WS_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_NATS_URL variable is not set. Defaulting to a blank string.
WARNING: The MF_MQTT_BROKER_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_MQTT_BROKER_WS_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_AUTH_GRPC_URL variable is not set. Defaulting to a blank string.
WARNING: The MF_THINGS_AUTH_GRPC_TIMEOUT variable is not set. Defaulting to a blank string.
WARNING: The MF_HTTP_ADAPTER_PORT variable is not set. Defaulting to a blank string.
WARNING: The MF_COAP_ADAPTER_LOG_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The MF_COAP_ADAPTER_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker/docker-compose.yml' is invalid because:
services.auth.expose is invalid: should be of the format 'PORT[/PROTOCOL]'
services.auth.ports contains an invalid type, it should be a number, or an object
services.auth.ports contains an invalid type, it should be a number, or an object
services.http-adapter.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.nginx.ports contains an invalid type, it should be a number, or an object
services.things.ports contains an invalid type, it should be a number, or an object
services.things.ports contains an invalid type, it should be a number, or an object
services.things.ports contains an invalid type, it should be a number, or an object
services.users.ports contains an invalid type, it should be a number, or an object
services.coap-adapter.ports contains an invalid type, it should be a number, or an object
services.coap-adapter.ports contains an invalid type, it should be a number, or an object
services.jaeger.ports contains an invalid type, it should be a number, or an object
services.nginx.ports value [':', ':', ':', ':'] has non-unique elements
services.things.ports value [':', ':', ':'] has non-unique elements
services.auth.ports value [':', ':'] has non-unique elements
services.jaeger.ports value [':/udp', ':', ':', ':'] has non-unique elements
make: *** [Makefile:103: run] Error 1
ubuntu@ubuntu:~/mainflux$ ls
ADOPTERS.md  auth.proto    cli        CONTRIBUTING.md  go.mod    LICENSE      Makefile  pkg        scripts  users
api.go       bootstrap     cmd        doc.go           go.sum    logger       metrics   provision  things   uuid.go
auth         certs         coap       docker           http      lora         mqtt      readers    tools    vendor
auth.pb.go   CHANGELOG.md  consumers  env.go           internal  MAINTAINERS  opcua     README.md  twins    version.go
ubuntu@ubuntu:~/mainflux$ git branch
  0.12.0
* 0.12.1
  master
ubuntu@ubuntu:~/mainflux$

![图片](https://user-images.githubusercontent.com/30143031/129288443-a88ee34e-19d4-48c5-87cf-e90e8a5cca11.png)

Best Regards,

**Comment by drasko** [comment]
Use higher `docker-compose` version which will look for `.env` in `docker` dir.

Example:
```bash
drasko@Mando:~/go/src/github.com/mainflux/mainflux$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

**Comment by iot-lorawan** [comment]
Hi drasko，
     Thanks for your  quickly response.
     now it is work well when upgrade the dock-compose version to 1.29.2
![图片](https://user-images.githubusercontent.com/30143031/129294934-545f2192-1f25-4d59-9225-93af75a25063.png)


Thanks,

**Comment by nmarcetic** [comment]
> Use higher `docker-compose` version which will look for `.env` in `docker` dir.
> 
> Example:
> 
> ```shell
> drasko@Mando:~/go/src/github.com/mainflux/mainflux$ docker-compose --version
> docker-compose version 1.29.2, build 5becea4c
> ```

@drasko We should update [prerequisites section](https://github.com/mainflux/mainflux#prerequisites)
