### ISSUE TITLE
Bumping up versions of protobuf

### ISSUE THREAD

**Issue by buraksekili** [absmach/magistrala#1455]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - tests
   - code refactor
   - documentation
   - research
   - tooling

Bumping up versions of `protobuf`. The current version of `protobuf` (e.g. in [CI script](https://github.com/mainflux/mainflux/blob/master/scripts/ci.sh)) should be updated. It needs an update.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
nice-to-have

**Comment by drasko** [comment]
@rodneyosodo can this be closed?
