### ISSUE TITLE
Various small bugs in the bin scripts

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#147]
**BUG REPORT**

1. What were you trying to achieve?
I tried to compile Mainflux from source with the scripts in the bin folder and to run the dockerized versions.

2. What are the expected results?
* the source code compiles and installs with bin/mainflux-install.sh, Mainflux can be started with bin/mainflux-launch.sh
* bin/mainflux-docker.sh starts and stops the Mainflux server

3. What are the received results?
* when compiling from source the build directory is not cleared up before and after the compilation and installation. The build directory is also not added to .gitignore
*  bin/mainflux-launch.sh starts the CoAP client (mainflux-coap) as well. The CoAP client was removed from the Makefile with #105
* when bin/mainflux-docker.sh is started without an attribute throws an error./mainflux-docker.sh: line 163: $1: unbound variable:
* the link to the contribution guide in README.md was not updated after the CONTRIBUTING.md was moved to .github with the commit f30c972
* in the README.md it is written that the install script will guide the user how to setup the infrastructure
for running Mainflux, but there is no description on which Cassandra keyspacess are needed and how to create them.

Best Regards,
Jovan

**Comment by drasko** [comment]
@chombium https://github.com/mainflux/mainflux/pull/154 helps cleaning of existing containers.
