### ISSUE TITLE
Add health check API endpoint

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#152]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Need health check API endpoint for Manager and HTTP adapter (at least).

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

should-have

**Comment by mijicd** [comment]
All services provide health check endpoint. Currently this endpoint displays only the deployment version, but it can be expanded (`version.go`) to provide even more information (e.g. health of service dependencies). Closing this for now.
