### ISSUE TITLE
Add CoAP to docker composition

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#153]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

CoAP is mature enough to be started in basic docker composition. It is in experimental state, but it will be good to include it in dev environments ASAP so we can have feedback and discover the bugs early.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Should-have

**Comment by chombium** [comment]
I was thinking to do as part of the correction for #148, but you can added as well

**Comment by drasko** [comment]
@chombium please add this as correction of #148, reference the issue an we'll close both upon your PR.

**Comment by chombium** [comment]
@drasko you can close this issue as well as I've added the CoAP service to the docker composition

**Comment by drasko** [comment]
Fixed by https://github.com/mainflux/mainflux/commit/7723b92ba71d5bdbd9a9db996eadb49e762741b2
