### ISSUE TITLE
Update the README.md of the CoAP adapter

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#156]
The [README.md](https://github.com/mainflux/mainflux/blob/master/coap/README.md) is too short and does not describe how the CoAP adapter should be configured and deployed.
I think we need a better description in the README.md similar to the one for the [HTTP adapter](https://github.com/mainflux/mainflux/blob/master/http/README.md)

Best Regards,
Jovan

**Comment by drasko** [comment]
@chombium sure. There is a work needed on CoAP as it it in experimental phase. We also need to schedule some work in integrating [LoRa Adapter](https://github.com/mainflux/lora-adapter) into monorepo...

**Comment by mijicd** [comment]
@drasko CoAP adapter needs to be refactored anyhow. Perhaps this is an opportunity to do that.

**Comment by drasko** [comment]
Fixed by https://github.com/mainflux/mainflux/pull/167
