### ISSUE TITLE
Export normalize method from writer service inside cassandra package

### ISSUE THREAD

**Issue by bojanbla** [absmach/magistrala#157]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

    Need to export `normalize` method from `writer` service inside `cassandra` package to be able to reuse it in [rules-engine](https://github.com/MainfluxLabs/rules-engine/) microservice. This microservice subscribes on the same `NATS` topic as `mainflux-writer`, so reusing code should reduce the number of bugs after potential changing message structure. [Issue](https://github.com/MainfluxLabs/rules-engine/issues/11) from `rules-engine` depends on this request.  
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

    should-have

**Comment by drasko** [comment]
@bblagojevic94 LGTM. Will you be sending PR?

**Comment by bojanbla** [comment]
Thanks, I will. @drasko
