### ISSUE TITLE
Add MQTT adapter

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#165]
Create scalable Go-based MQTT broker that can be used form Mainflux system, but also as an independent product.

[SurgeMQ](https://github.com/surgemq/surgemq) has been discontinued, no good open-source Go implementation exists.

Erlang MQTT brokers ([VerneMQ](https://vernemq.com/) and [EMQ](http://emqtt.io/)) show good scalability (easy clustering due to Elang) and big number of concurrently connected MQTT clients (again, due to Erlang proceses). However, performance levels (throughput, MPS) is questionable.

Go implementatation should offer high performance, but should also support big number of concurrent connections (leveraging on Go concurrency model).

In the next phase, clustering should be made as easy as possible, probably via RAFT.

**Comment by drasko** [comment]
Repo created: https://github.com/mainflux/fluxmq

**Comment by chombium** [comment]
This looks very cool.
Which MQTT version are we going to implememt 3.1.1 or the upcomming 5.0?
Will there also be support for MQTT-SN?
I see that everyone is assigned on this, but don't hesitate to ping me if you need help as I've worked on few MQTT projects already.

Best Regards,
Jovan

**Comment by drasko** [comment]
@chombium I think this will be a big task, but we it is getting hard for us to support NodeJS MQTT broker, so going towards 1.0 we would prefer Go version.

I propose that we make it as simple as possible in the beginning, no MQTT-SN support for now, add this eventually later. Let's start with 3.1.1, and I do not think that it would be a problem to switch to 5.0. Since it is a new broker from scratch we do not have a special need to be backward compatible, I am only afraid of existing clients, as I think that using Paho clients would be the best approach.

Regarding the design, I went though SurgeMQ and NATS code to see how brokers are designed. I like the SurgeMQ design, just that we agree do we put `Session` in a separate struct (https://github.com/surgemq/surgemq/blob/master/sessions/session.go#L29), and how will we handle the code organization. I will try to write a small doc on GoogleDocs that we can share and comment.

Any help is more than welcome, and I expect that if we can do this well, we will have a help from community, because I think that Go MQTT broker is needed - it can run well both in the cloud but also on the gateways (especially if we add MQTT-SN support later).

**Comment by drasko** [comment]
@mijicd @chombium @nmarcetic I am trying to advance with FluxMQ: https://github.com/mainflux/fluxmq. It does not compile yet, but I think we can take whole protocol part in the sense of message dissecting from SurgeMQ: https://github.com/surgemq/message. This is only implementation of the standard (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/mqtt-v3.1.1.html), so I put it temporarily here: https://github.com/mainflux/fluxmq/tree/master/message, and we'll see what changes will be needed.

What I am most concerned now is that SurgeMQ has the notion of `Service`: https://github.com/surgemq/surgemq/blob/master/service/service.go#L48, and also `Session`: https://github.com/surgemq/surgemq/blob/master/sessions/session.go#L29

Both are created on new client connection. I.e. server creates new service for each client, and then within this service it creates the session.

I am wondering if this is needed, seems to complicated for me at this point. My opinion is that we only need to create one `Session` object every time the client is connected, and then keep all client's connection state within this object. We probably do not need this additional layer that he calls `Service` (and it is also confusing for me to have one "service" per client connection).

What is your opinion, how should we progress on this?

**Comment by drasko** [comment]
@Maxpeng92 we are working exactly on this ;).

As you can observe on PRs for WS and CoAP - https://github.com/mainflux/mainflux/pulls - they are now mapping `channels` to NATS topics and re-using NATS PUB/SUB brokering and scalability. Equally - with new changes to `http` adapter, `channels` are mapped to NATS subjects. Everything will be aligned.

Even the recent changes in NodeJS `mqtt` adapter, `channels` are mapped to NATS subjects (https://github.com/mainflux/mqtt-adapter/commit/f4d8d71e6f0f97e74ce68ab84e3e383df31cab59#diff-7489da7b58ea7b1260188b9c87d2693cR129)

So - yes - new MQTT adapter written in Go will be just a thin protocol adapter layer around NATS and relay completely on nats for brokering, performance, scalability, etc...

This simplified the design of the whole system and I think added a tight and high quality architecture.

**Comment by Maxpeng92** [comment]
@drasko I'm really glad that we are on the same page!

**Comment by Maxpeng92** [comment]
@drasko One use case I would highly suggested is that other than senml+json format data. An important use case of IoT system would be sending executable to edge devices to update. The current protobuf node module cannot handle this, unless we encode .exe or zip it up.

**Comment by drasko** [comment]
@Maxpeng92 actually, support of `octet-binary` will be also included with this contribution.

**Comment by drasko** [comment]
@Maxpeng92 @chombium PR https://github.com/mainflux/mainflux/pull/217 posted as WIP. Help is needed.

**Comment by mijicd** [comment]
Pull request #217 will be closed due to the long effort needed to ship it. We have merged the old version of javascript adapter into the monorepo, and we will continue polishing that implementation, since we need MQTT adapter as soon as possible.

**Comment by mijicd** [comment]
Resolved by #285
