### ISSUE TITLE
Raise the test coverage

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#170]
We have tests only for the mainflux/manager and mainflux/manager/api. I think we should write more tests in order to be able to change things without worrying that we'll break something.

I will start writing some tests. and I want to start with the http and writer services. I will use the same tools/packages for testing which are used in the [manager_test.go](https://github.com/mainflux/mainflux/blob/master/manager/manager_test.go).

What do you think about this? Are there any parts that it does not make sense to write tests for?

Best Regards,
Jovan

**Comment by drasko** [comment]
Totally agreed.

We need both unit and e2e tests.

@mijicd mentioned this today, I thought that he will open an issue for this task, to that we can have a reminder.

**Comment by mijicd** [comment]
@chombium absolutely agreed. During the next period I'll start working on that as well. We can utilize [Docker test](https://github.com/ory/dockertest) as well.

**Comment by chombium** [comment]
I've recently heard of  [Pact](https://docs.pact.io/). It provides [Consumer-Driven Contracts](https://martinfowler.com/articles/consumerDrivenContracts.html) testing. It is basically a kind of testing which makes sure that the APIs and the communication flow between the consumers and the providers stay in sync. I still haven't got the time to try it but it looks very interesting.

Here are some links:
[Pacts to the Rescue! Making your microservices play nicely together - Beth Skurrie](https://www.youtube.com/watch?v=kz3YI2YGODs)
[Verifying Microservice Integrations with Contract Testing](https://www.atlassian.com/company/events/summit-us/watch-sessions/2016/build-deploy/verifying-microservice-integrations-with-contract-testing)

**Comment by mijicd** [comment]
@chombium I am familiar with the Pact for quite a while. If you want to use it for verifying our API contracts, I don't have anything against it. Nevertheless, I wouldn't skip the aforementioned. Also, I think this entire ticket is more of an "epic" than an "issue", therefore, it should be submitted in multiple PRs.

**Comment by chombium** [comment]
@mijicd yes, I agree that this is more like an epic. Let's decide what kind of test are we going to write and what technology are we going to use and write some example (template) tests which we can use it as a starting point for writing the other tests.
Let's make a list of all possible technologies with which we can write the tests, do an evaluation and decide what are we going to use and how are we going write and run the tests

**Comment by drasko** [comment]
@chombium agreed. We can use this issue for discussion abut technologies, and then break task into several issues.

**Comment by mijicd** [comment]
In the last couple of pull requests we have introduced dockertest and improved our existing tests significantly. We have decided to use Pact for specifying our API contracts and @anovakovic01 will start working on it soon.

**Comment by chombium** [comment]
@mijicd This is great news. I would only suggest that we open separate issues for each needed test and the test configuration or a single issue with a list of all test and things that have to be done, so that we can track the progress better. This way in case someone wants to help, we would avoid overlapping

**Comment by mijicd** [comment]
@chombium I agree completely, though I must say I would let @anovakovic01 create an initial PR, which we can use as foundation for further work.

**Comment by mijicd** [comment]
Based on discussion with @anovakovic01 a decision has been made to drop Pact testing in favor of `httptest`-based "native" tests. No additional benefit comes from using Pact for an API like ours. Moreover, @anovakovic01 will take care of integrating codecov with the platform.

**Comment by chombium** [comment]
@mijicd @anovakovic01 agreed, we should keep the things simple. We should only ensure that the clients and the servers use the same api specification and to have a mechanism to detect api changes and incompatibilities as soon as possible.
Other thing to think about is where and how are going to run integration tests as part of the whole CI pipeline
