### ISSUE TITLE
Wrap the usage of external logger in our own implementation

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#174]
Instead of directly using a logger provided by `go-kit`, implement Mainflux logger that depends on it (technically it can depend on any other 3rd party logger). 

**Acceptance criteria:**
- all logs are JSON formatted and emitted to stdout
- all logs must contain an UTC timestamp field named `ts` as ISO-8601 string
- logger should expose 3 methods: `Info`, `Warn`, `Error` (each of these will set `level` field)
- ensure that all services are using only our implementation

**Comment by chombium** [comment]
I, think a Debug logging level which will be used for diagnostic information (i.e. logging of request data) should also be added.

Best Regards,
Jovan

**Comment by mijicd** [comment]
@chombium the reason I did not specify it as part of the acceptance criteria is because my goal with this ticket is to define some common logging standards and abstract away the underlying logger implementation. Later on, I would definitely go for adding more log levels and dropping the log messages based on their level (e.g. no `DEBUG` in production).

**Comment by chombium** [comment]
@mijicd  thanks for the clarification
