### ISSUE TITLE
docker-compose fails

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#179]
`docker-compose us` is running out-of-order dockers.

Without a backoff and re-try with timeour in services themselves, we can forget about using `docker-compose` and we must fallback to previous starting script.

```
drasko@Marx:~/go/src/github.com/mainflux/mainflux/docker$ docker-compose up
Creating mainflux-manager ... 
Creating mainflux-nats ... 
Creating mainflux-postgres ... 
Creating mainflux-normalizer ... 
Creating mainflux-manager
Creating mainflux-nginx ... 
Creating mainflux-nats
Creating mainflux-normalizer
Creating mainflux-nginx
Creating mainflux-nats ... done
Creating mainflux-http ... 
Creating mainflux-mqtt ... 
Creating mainflux-mqtt
Creating mainflux-mqtt ... done
Attaching to mainflux-manager, mainflux-nats, mainflux-normalizer, mainflux-postgres, mainflux-nginx, mainflux-http, mainflux-mqtt
mainflux-manager | {"error":"dial tcp: lookup postgres on 10.20.0.1:53: no such host","ts":"2018-03-13T02:17:55.877664432Z"}
mainflux-nats   | [1] 2018/03/13 02:17:56.008535 [INF] Starting nats-server version 1.0.2
mainflux-nats   | [1] 2018/03/13 02:17:56.008625 [INF] Starting http monitor on 0.0.0.0:8222
mainflux-normalizer | {"error":"Failed to connect: nats: no servers available for connection","ts":"2018-03-13T02:17:56.16486139Z"}
mainflux-nats   | [1] 2018/03/13 02:17:56.008662 [INF] Listening for client connections on 0.0.0.0:4222
mainflux-nats   | [1] 2018/03/13 02:17:56.008666 [INF] Server is ready
mainflux-postgres | The files belonging to this database system will be owned by user "postgres".
mainflux-postgres | This user must also own the server process.
mainflux-postgres | 
mainflux-nats   | [1] 2018/03/13 02:17:56.134986 [INF] Listening for route connections on 0.0.0.0:6222
mainflux-nginx  | 2018/03/13 02:17:56 [emerg] 1#1: host not found in upstream "mainflux-manager:8180" in /etc/nginx/nginx.conf:58
mainflux-postgres | The database cluster will be initialized with locale "en_US.utf8".
mainflux-http   | {"error":"nats: no servers available for connection","ts":"2018-03-13T02:17:56.689929955Z"}
mainflux-nginx  | nginx: [emerg] host not found in upstream "mainflux-manager:8180" in /etc/nginx/nginx.conf:58
mainflux-postgres | The default database encoding has accordingly been set to "UTF8".
mainflux-postgres | The default text search configuration will be set to "english".
mainflux-postgres | 
mainflux-postgres | Data page checksums are disabled.
mainflux-postgres | 
mainflux-manager exited with code 1
mainflux-postgres | fixing permissions on existing directory /var/lib/postgresql/data ... ok
mainflux-postgres | creating subdirectories ... ok
mainflux-postgres | selecting default max_connections ... 100
mainflux-postgres | selecting default shared_buffers ... 128MB
mainflux-postgres | selecting dynamic shared memory implementation ... posix
mainflux-postgres | creating configuration files ... ok
mainflux-normalizer exited with code 1
mainflux-postgres | running bootstrap script ... ok
mainflux-postgres | performing post-bootstrap initialization ... sh: locale: not found
mainflux-postgres | 2018-03-13 02:17:56.543 UTC [29] WARNING:  no usable system locales were found
mainflux-postgres | ok
mainflux-postgres | syncing data to disk ... ok
mainflux-postgres | 
mainflux-postgres | Success. You can now start the database server using:
mainflux-postgres | 
mainflux-postgres |     pg_ctl -D /var/lib/postgresql/data -l logfile start
mainflux-postgres | 
mainflux-postgres | 
mainflux-postgres | WARNING: enabling "trust" authentication for local connections
mainflux-postgres | You can change this by editing pg_hba.conf or using the option -A, or
mainflux-postgres | --auth-local and --auth-host, the next time you run initdb.
mainflux-postgres | waiting for server to start....2018-03-13 02:17:56.858 UTC [34] LOG:  listening on IPv4 address "127.0.0.1", port 5432
mainflux-postgres | 2018-03-13 02:17:56.858 UTC [34] LOG:  could not bind IPv6 address "::1": Address not available
mainflux-postgres | 2018-03-13 02:17:56.858 UTC [34] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
mainflux-postgres | 2018-03-13 02:17:56.865 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mainflux-postgres | 2018-03-13 02:17:56.883 UTC [35] LOG:  database system was shut down at 2018-03-13 02:17:56 UTC
mainflux-postgres | 2018-03-13 02:17:56.887 UTC [34] LOG:  database system is ready to accept connections
mainflux-postgres |  done
mainflux-postgres | server started
mainflux-mqtt   | {"pid":1,"hostname":"2bc75be03e01","level":30,"time":1520907476986,"msg":"listening","address":"::","family":"IPv6","port":8880,"protocol":"http","v":1}
mainflux-mqtt   | {"pid":1,"hostname":"2bc75be03e01","level":30,"time":1520907476988,"msg":"listening","address":"::","family":"IPv6","port":1883,"protocol":"tcp","v":1}
mainflux-mqtt   | events.js:165
mainflux-mqtt   |       throw err;
mainflux-mqtt   |       ^
mainflux-mqtt   | 
mainflux-mqtt   | Error: Uncaught, unspecified "error" event. (Could not connect to server: Error: getaddrinfo ENOTFOUND nats nats:4222)
mainflux-mqtt   |     at Client.emit (events.js:163:17)
mainflux-mqtt   |     at Socket.<anonymous> (/node_modules/nats/lib/nats.js:405:14)
mainflux-mqtt   |     at emitOne (events.js:96:13)
mainflux-mqtt   |     at Socket.emit (events.js:188:7)
mainflux-mqtt   |     at connectErrorNT (net.js:1025:8)
mainflux-mqtt   |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
mainflux-mqtt   |     at process._tickCallback (internal/process/next_tick.js:104:9)
mainflux-nginx exited with code 1
mainflux-http exited with code 1
mainflux-postgres | CREATE DATABASE
mainflux-postgres | 
mainflux-postgres | CREATE ROLE
mainflux-postgres | 
mainflux-postgres | 
mainflux-postgres | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
mainflux-postgres | 
mainflux-postgres | waiting for server to shut down....2018-03-13 02:17:57.224 UTC [34] LOG:  received fast shutdown request
mainflux-postgres | 2018-03-13 02:17:57.228 UTC [34] LOG:  aborting any active transactions
mainflux-postgres | 2018-03-13 02:17:57.229 UTC [34] LOG:  worker process: logical replication launcher (PID 41) exited with exit code 1
mainflux-postgres | 2018-03-13 02:17:57.229 UTC [36] LOG:  shutting down
mainflux-postgres | 2018-03-13 02:17:57.262 UTC [34] LOG:  database system is shut down
mainflux-postgres |  done
mainflux-postgres | server stopped
mainflux-postgres | 
mainflux-postgres | PostgreSQL init process complete; ready for start up.
mainflux-postgres | 
mainflux-postgres | 2018-03-13 02:17:57.335 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mainflux-postgres | 2018-03-13 02:17:57.335 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mainflux-postgres | 2018-03-13 02:17:57.343 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mainflux-postgres | 2018-03-13 02:17:57.370 UTC [47] LOG:  database system was shut down at 2018-03-13 02:17:57 UTC
mainflux-postgres | 2018-03-13 02:17:57.378 UTC [1] LOG:  database system is ready to accept connections
mainflux-mqtt exited with code 1
```

**Comment by mijicd** [comment]
@drasko I have already discussed the issue of having retries. Let me state that one more time: **we won't introduce that**. @nmarcetic is already working on fixing this.

**Comment by Maxpeng92** [comment]
If you don't create virtual network by commenting out network_mode and delete "/" from 152 from nginx.conf, you compose file would work.

**Comment by drasko** [comment]
@Maxpeng92 can you please send a PR?

**Comment by nmarcetic** [comment]
@Maxpeng92 You are right about network_mode and nginx.conf `/` at the end of proxy_pass URL. 
  Thanks a lot! 
We are struggling a lot with compose and  never works properly, because the service order is not guaranteed (depends_on and links not solving this) and this is obvious on [Docker official documentation](https://docs.docker.com/compose/startup-order/) . You can test this by implementing your suggestions/fix and try to run/stop composition few times, sometime will start but in most cases some service which has dependency to postgres for example will exit.
There are some hacks with some wait scripts etc... but its really ugly and hacky. The whole idea about composition was to provide people easy way to spin Mainflux composition in single command, but as you can guess this was not so easy with compose.

In order to solve this, we was talking to switch to Docker Swarm [there are plenty reasons for this](https://docs.docker.com/engine/swarm/), maybe the most important is fact that compose is almost deprecated and it was never planed for production environments (it was more like a development tool, the son of good old project Fig). The version 3 is released to enable smooth and easy migration to docker stack (swarm mode). Second, Swarm mode is now available in Docker engine 1.2 + out of box, so you don't need third party tools like docker-compose and it knows how to parse docker-compose.yml v3 files, so we can actually switch to Swarm immediately (WIP status).

@drasko ^

Best

**Comment by chombium** [comment]
As I already [commented](https://github.com/mainflux/mainflux/issues/135#issuecomment-363418273) the best way to do this is to adjust the services so that they survive outages of the services that depend on and to advertise their health status accordingly.

With Docker Swarm you can not define dependencies between the services like with compose with depends_on, but the services will be restarted if they fail. That means on start up if a service starts before a service it depends on and fails (exits with non zero error code) it will be restarted till it works properly. 

IMHO, as we need to adjust the start up scripts (docker compose) and we already have not zero exit codes in case of errors for all of the services, Docker Swarm would be the solution with lowest effort for this problem.

so +1 for Docker Swarm

**Comment by Maxpeng92** [comment]
@drasko @nmarcetic I created a PR for fixing nginx config issue. Since you mentioned you prefer Docker Swarm as your deployment strategy, I would just leave the current docker compose file as it is. And I totally agree that Docker Swarm would be better when you consider high availability. I would like to help but I properly cannot commit anything for a new feature. Also, I would suggest consider Kubernetes as another option.

**Comment by drasko** [comment]
@Maxpeng92 thanks for the PR, @nmarcetic will take a look at this one.

**Comment by nmarcetic** [comment]
@chombium Totally agree with you, except :) As you probably know `depends_on` does not guarantee that your dependency service is actually ready, as you mention. Using scripts like wait-for or dockerize are little bit hacky (even if they are [recommended by official documentation](https://docs.docker.com/compose/startup-order/)). The health check feature looks good, maybe we can do a quick fix using it ? What do you think ? 

`With Docker Swarm you can not define dependencies between the services like with compose with depends_on, but the services will be restarted if they fail. That means on start up if a service starts before a service it depends on and fails (exits with non zero error code) it will be restarted till it works properly.`
 Exactly but this is not the only reason to switch to Swarm. There is a plenty reasons as I already mention. Restart after exit can be solved with compose and `restart: on-failure` but its still compose :) As I mention almost deprecated tool + not even close to any production env.

If you want to give a try to PR using helthchecks that would be great :) 

Also we should support Swarm as a production ready orchestration. I agree about Kubernetes @Maxpeng92  is must , but keep in mind that K8 is complicated for peoples who are not very familiar with devops, so IMHO the Swarm is awesome solution for them ;) 

So my proposal is 
1. Try to fix docker-compose as temporary solution
2. Support Swarm
3. Support Kubernetes 

Best

**Comment by drasko** [comment]
@nmarcetic if we are fixing `docker-compose` as a temporary solution, then it would be best if @Maxpeng92 can send a PR that fixes it.

@Maxpeng92 can you please shoot us your PR that you mentioned previously?

**Comment by Maxpeng92** [comment]
@drasko Remove network_mode won't fully fix the issue. You'll need to start the failed started containers individually if there is any. But at least, I successfully ran all containers on AWS by this change. However, I'm not sure if you guys satisfy this temporary solution?

**Comment by cashflow4me** [comment]
Hello,
I am trying to run the compose after commenting out network_mode and deleting "/" from 152 from nginx.conf, as said early, but my mainflux-manager doesn't run.

I tried to run it manually with:
docker run -it --rm --name=mainflux-manager -e MF_MANAGER_DB=mainflux mainflux/manager:latest --verbose
but the response is:
{"error":"dial tcp 127.0.0.1:5432: getsockopt: connection refused","ts":"2018-03-16T09:19:56.560986737Z"}

What could it be?

Thanks

**Comment by anovakovic01** [comment]
@cashflow4me Was your postgres container running while you tried to start mainflux-manager?

**Comment by nmarcetic** [comment]
@cashflow4me @anovakovic01 @Maxpeng92 @drasko I pushed possible fix to new branch [fix/composition](https://github.com/mainflux/mainflux/tree/fix/composition) Can I ask you all to checkout and try to run composition. Before you run it, pls remove all already created Mainflux containers if any.
Please let me know if is working. 

@Maxpeng92 @chombium  This fix is a combo of your proposals about restart etc...

**Comment by drasko** [comment]
@nmarcetic why not just merging it on master - what's currently on master does not work anyway.

**Comment by drasko** [comment]
@nmarcetic why not just merging it on master - what's currently on master does not work anyway.

**Comment by nmarcetic** [comment]
Agree, but I wanted to avoid garbage commits into master. Its the same :) checkout new fix branch try, confirm if is working we will merge. Agree ?

**Comment by anovakovic01** [comment]
@nmarcetic Your fix works for me.

**Comment by chombium** [comment]
@nmarcetic cool I will test it tonight and give my feedback

**Comment by nmarcetic** [comment]
@chombium Thanks! I sent PR it will be probably merged by tonight :)  But we will not close this issue, until you confirm.

**Comment by cashflow4me** [comment]
Hi all,

Thanks for the last merge, it works!
But then the first command - Create User (docs: http://mainflux.readthedocs.io/en/latest/getting-started/) failed. Can someone point me where to start? or how to check?

Thanks

**Comment by cashflow4me** [comment]
Here is state of docker:

CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
103a439c8948        mainflux/http:latest           "/exe"                   10 minutes ago      Up 10 minutes       8182/tcp                                                           mainflux-http
98cbd284919a        mainflux/mqtt-adapter:latest   "node mqtt.js"           10 minutes ago      Up 10 minutes       1883/tcp, 8880/tcp                                                 mainflux-mqtt
44a9276a8bc3        postgres:10.2-alpine           "docker-entrypoint.s…"   10 minutes ago      Up 10 minutes       5432/tcp                                                           mainflux-postgres
d53cd499cd7f        nats:1.0.2                     "/gnatsd -c gnatsd.c…"   10 minutes ago      Up 10 minutes       4222/tcp, 6222/tcp, 8222/tcp                                       mainflux-nats
104f9b96617d        mainflux/normalizer:latest     "/exe"                   10 minutes ago      Up 10 minutes       8181/tcp                                                           mainflux-normalizer
c722aeea6989        mainflux/manager:latest        "/exe"                   10 minutes ago      Up 10 minutes       8180/tcp                                                           mainflux-manager
6b683380f90a        nginx:1.13-alpine              "nginx -g 'daemon of…"   10 minutes ago      Up 10 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8883->8883/tcp   mainflux-nginx

Running curl:

curl -s -S -i -X POST -H "Content-Type: application/senml+json" localhost:8180/users -d '{"email":"john.doe@email.com", "password":"123"}'

Result:
curl: (7) Failed to connect to localhost port 8180: Connection refused

**Comment by cashflow4me** [comment]
Thanks, but now the request redirected to https

curl -s -S -i -X POST -H "Content-Type: application/senml+json" localhost/users -d '{"email":"john.doe2@email.com", "password":"123"}'
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.13.9
Date: Fri, 16 Mar 2018 17:20:04 GMT
Content-Type: text/html
Content-Length: 161
Connection: keep-alive
Location: https://localhost/users

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.13.9</center>
</body>
</html>

**Comment by cashflow4me** [comment]
I found a solution by looking for a docker IP address
https://stackoverflow.com/questions/17157721/how-to-get-a-docker-containers-ip-address-from-the-host

docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mainflux-manager

==> response: 172.19.0.2

and 
curl -s -S -i -X POST -H "Content-Type: application/senml+json" 172.19.0.2:8180/users -d '{"email":"john.doe@email.com", "password":"123"}'
==>
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
Date: Fri, 16 Mar 2018 16:54:23 GMT
Content-Length: 0

It worked, but I understand that this is call directly to the manager container, without proxy-pass through nginx, right?

**Comment by Maxpeng92** [comment]
@cashflow4me There a couple of solutions. You can either re-config your own nginx to make the reverse proxy work or bind 8180 of manager container to the node which would be in an insecure mode.

**Comment by chombium** [comment]
Hi,

I tested  the docker composition and for most cases with decent network connection it will work with the default docker-compose parameters.
I also did few tests running  GNU/Linux from a USB Stick (a bit extreme :P, but I wanted to test with slower hardware/network connection) and with the default docker-compose parameters (COMPOSE_HTTP_TIMEOUT=60) and I managed to get the composition fail:
```
....
....
....
ERROR: for mainflux-nats  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mainflux-postgres  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mainflux-manager  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mainflux-normalizer  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mainflux-nginx  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for nats  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for postgres  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for manager  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for normalizer  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for nginx  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

Than I deleted the containers and the images and started the composition with:
```
$ COMPOSE_HTTP_TIMEOUT=300 docker-compose up
```
Everything went well and Mainflux started properly.

I think maybe we could add few comments in the [README.md](https://github.com/mainflux/mainflux/blob/master/README.md) and the [getting-started.md](https://github.com/mainflux/doc/blob/master/docs/getting-started.md) that in case of timeouts the users should raise the value of the  COMPOSE_HTTP_TIMEOUT envvar.
On the other hand, that already comes as an error from docker-compose, so If the users follow the logs they can get Mainflux up and running.

If we want ot be nice we could add a troubleshooting section in our docs, but I don't think that this is a must, because if the users follow the logs they can solve all the issues with the timings.

Best Regards,
Jovan

**Comment by drasko** [comment]
Thanks @chombium for this great work!

Can you please push the PR here: https://github.com/mainflux/doc, feel free to add `Troubleshooting` or whatever section.

**Comment by mijicd** [comment]
Thanks everyone for their work. Closing this issue.
