### ISSUE TITLE
Bump Docker nodejs version

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#18]
I think we can bump up nodejs docker version here: https://github.com/Mainflux/mainflux/blob/master/Dockerfile#L6. I can see here: https://hub.docker.com/_/node/ that latest is 4.1.2

**Comment by nmarcetic** [comment]
Agree! I will set the new version.

**Comment by drasko** [comment]
Please do, send PR and do not forger to reference this issue ID in the PR comment.

**Comment by drasko** [comment]
Fixed by https://github.com/Mainflux/mainflux/commit/ef00dac107a4fedaeb3424190c87eca22ad5d16f.

NodeJS version 4.2.3 was selected as this is LTS version (https://github.com/nodejs/LTS/).
