### ISSUE TITLE
Grouping clients to a channel doesn't work

### ISSUE THREAD

**Issue by Maxpeng92** [absmach/magistrala#182]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?
I was trying to group clients by connecting them on channels.

2. What are the expected results?
Clients to be added to an existed channel as specified.

3. What are the received results?
I got a 500 server side error. Also, I entered the postgres container checked the table, which was empty. And even I added the relationship in client_channel table manually, it would be shown in dashflux.

4. What are the steps to reproduce the issue?
Either use dashflux to reproduce or use curl to make the same request.

5. In what environment did you encounter the issue?
I have a running mainflux instance on Aws.

6. Additional information you deem important:
Other operations like create user, create device/app and create channel are working except this one.

**Comment by mijicd** [comment]
@Maxpeng92 dashflux is not updated with the latest API changes, therefore it is not able to create such relationship. This is a work in progress, and I expect it to be up & running in a couple of days. Until then, CURL (or any other HTTP client) will be the only available way to interact with the platform, as shown in the following snippet:

```bash
// client
curl -XPUT "localhost:8180/channels/a4a64f3f-33a3-4f87-9633-336c215e1778/clients/2a1cc8b6-7c35-452a-9b76-5bd558a26293" -H'Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjEwNzc4OTQsImlhdCI6MTUyMTA0MTg5NCwiaXNzIjoibWFpbmZsdXgiLCJzdWIiOiJkZWphbi5tamNAZ21haWwuY29tIn0.Q7uQTU46yW-evLNqBiplOdfduK-NcbEaQVReSXATv-o'

// service log
{"channel":"a4a64f3f-33a3-4f87-9633-336c215e1778","client":"2a1cc8b6-7c35-452a-9b76-5bd558a26293","error":null,"key":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjEwNzc4OTQsImlhdCI6MTUyMTA0MTg5NCwiaXNzIjoibWFpbmZsdXgiLCJzdWIiOiJkZWphbi5tamNAZ21haWwuY29tIn0.Q7uQTU46yW-evLNqBiplOdfduK-NcbEaQVReSXATv-o","method":"connect","took":"4.912486ms","ts":"2018-03-14T15:42:41.749899765Z"}
```

**Comment by Maxpeng92** [comment]
@mijicd I worked around by manually adding it to the client_channel table. But thank you for providing the curl script. I kinda like your previous API to add group of clients with one request more.
