### ISSUE TITLE
Grouping clients by channel with invalid request returns status code 500

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#183]
**BUG REPORT**

1. What were you trying to achieve?
I tried to add clients to a channel with request with invalid JSON body.

2. What are the expected results?
Status code 400 (Bad Request).

3. What are the received results?
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Date: Wed, 14 Mar 2018 16:35:33 GMT
Content-Length: 0
```

4. What are the steps to reproduce the issue?
Send following request with valid `user_token`, `channel_id` and `client_id`:
```
curl -s -S -i --noproxy localhost -X PUT -H "Content-Type: application/senml+json" -H "Authorization: <user_token>" localhost:8180/channels/<channel_id> -d '{"name":"mychan", "connected": ["<client_id>"]}'
```

5. In what environment did you encounter the issue?
I run mainflux locally on OS X, Postgres 9.6, NATS v1.0.4.

**Comment by Maxpeng92** [comment]
@anovakovic01 Refer to this #182

**Comment by anovakovic01** [comment]
@Maxpeng92 Thanks for the link, but this issue is referring to the fact that mainflux is returning status code 500, instead of 400 for invalid request. I am aware that this request shouldn't work, as it doesn't. Still, I think that there shouldn't be a case where client receives status code 500. This indicates that there is an error that is not handled properly.
