### ISSUE TITLE
Manager container is broken

### ISSUE THREAD

**Issue by Maxpeng92** [absmach/magistrala#195]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?
Run stack deploy

2. What are the expected results?
Containers are successfully up and running

3. What are the received results?
Mainflux-manager container is broken. 'standard_init_linux.go:195: exec user process caused "no such file or directory"'

4. What are the steps to reproduce the issue?
Run docker compose

5. In what environment did you encounter the issue?
Deploy docker swarm on AWS

6. Additional information you deem important:

**Comment by mijicd** [comment]
@drasko Please fix the build.

@Maxpeng92 Just verified that the image version `0.1.2` (or earlier) works as expected.

**Comment by drasko** [comment]
@Maxpeng92 @mijicd working on it...

**Comment by drasko** [comment]
Fixed by #196
