### ISSUE TITLE
POST /channels creates multiple channels with the same name

### ISSUE THREAD

**Issue by MilesDuke-Keysight** [absmach/magistrala#209]
1. What were you trying to achieve?

I was trying to ensure a channel for a given topic was provisioned and ready for use.

2. What are the expected results?

I expected a POST to /channels to return 201 or 409, the same way a POST to /users does, and to provide the Location in the results in either case.

3. What are the received results?

POST always returns 201, creating a new channel with a new ID, even if a channel with the same name (and different ID) already existed.  A subsequent GET on /channels returns an array where multiple lines in the array have the same value for 'name'.

4. What are the steps to reproduce the issue?

Issue two POST requests to channels, using the same json payload { "name" : "myTopicName" }

5. In what environment did you encounter the issue?

Mainflux manager running in three-cluster mode using NGINX load balancer.  (I suspect the same thing would happen with a single mainflux manager.)

6. Additional information you deem important:

I have worked around this issue by doing a GET on /channels and scanning the results.  This could get time-consuming if there were a large number of channels, and this is vulnerable to a race condition, if two entities tried to ensure a given channel was provisioned at roughly the same time.

**Comment by mijicd** [comment]
Instead of expecting something that is not supported, please refer to the [service API documentation](https://github.com/mainflux/mainflux/blob/master/manager/swagger.yaml).

**Comment by MilesDuke-Keysight** [comment]
It is still a bug that this service API can create multiple duplicate records for the same topic name (or no topic name at all).  The ambiguity of topic names dilutes the value of the mainflux message bus.

If this ambiguity is not important enough for the core contributors to resolve, you might at least give a hint about how others might resolve the problem.

**Comment by mijicd** [comment]
@MilesDuke-Keysight channel name is a convenience, not an identifier of a topic. Not a single duplicated topic is created under the hood.

**Comment by mijicd** [comment]
To elaborate slightly more on my previous comment: channel's name was introduced for sole purpose of being UI convenience. It was never intended to serve as channel identifier. As you already saw, both through using the API and in the API documentation, the only channel identifier is an auto-generated one, which you can obtain both through the `Location` header, and through single- and multi-channel retrieval endpoints.
