### ISSUE TITLE
Unable to create User when deploying by docker compose

### ISSUE THREAD

**Issue by hpham04** [absmach/magistrala#219]
I used docker compose to start mainflux in my local pc, output is below:
c3e72d2454ee        mainflux/mqtt-adapter:latest   "node mqtt.js"           2 hours ago         Up 2 hours          0.0.0.0:1883->1883/tcp, 8880/tcp                                   mainflux-mqtt
670a6a464866        mainflux/http:latest           "/exe"                   2 hours ago         Up 2 hours          8182/tcp                                                           mainflux-http
76398187a3c8        nginx:1.13-alpine              "nginx -g 'daemon of…"   2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8883->8883/tcp   mainflux-nginx
5b46a4095a4b        nats:1.0.2                     "/gnatsd -c gnatsd.c…"   2 hours ago         Up 2 hours          4222/tcp, 6222/tcp, 8222/tcp                                       mainflux-nats
46bfee10fa81        mainflux/normalizer:latest     "/exe"                   2 hours ago         Up 2 hours          8181/tcp                                                           mainflux-normalizer
67bb97ec13db        mainflux/manager:latest        "/exe"                   2 hours ago         Up 2 hours          8180/tcp                                                           mainflux-manager
8ba69c632e31        postgres:10.2-alpine           "docker-entrypoint.s…"   2 hours ago         Up 2 hours          0.0.0.0:5432->5432/tcp                                             mainflux-postgres

Then I tried to create user according to this guideline: http://mainflux.readthedocs.io/en/latest/getting-started/
curl -s -S -i --cacert docker/ssl/certs/mainflux-server.crt --insecure -X POST -H "Content-Type: application/senml+json" https://localhost/tokens -d '{"email":"john.doe@email.com", "password":"123"}'

And the output looks like below:
 curl -s -S -i --cacert docker/ssl/certs/mainflux-server.crt --insecure -X POST -H "Content-Type: application/senml+json" https://localhost/tokens -d '{"email":"john.doe@email.com", "password":"123"}'
HTTP/1.1 415 Unsupported Media Type
Server: nginx/1.13.11
Date: Tue, 10 Apr 2018 06:29:32 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 0
Connection: keep-alive

**Comment by anovakovic01** [comment]
@hpham04 Current Mainflux doc is deprecated and there are things that are wrong from the beginning. Manager service was never meant to support senML format. You should always send request with header `Content-Type: application/json; charset=utf-8` in order for it to work. If you have any more problems with these requests, please report.

**Comment by hpham04** [comment]
@anovakovic01 
I just tried to change the content type but problem still occurs:

curl -s -S -i --cacert docker/ssl/certs/mainflux-server.crt --insecure -X POST -H "Content-Type: application/json; charset=utf-8" https://localhost/tokens -d '{"email":"john.doe@email.com", "password":"123"}'
HTTP/1.1 403 Forbidden
Server: nginx/1.13.11
Date: Tue, 10 Apr 2018 06:59:05 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 0
Connection: keep-alive

Can you please help to advise

**Comment by anovakovic01** [comment]
@hpham04 Have you registered user with these credentials before trying to login? If you haven't, you should send same request with different path: `https://localhost/users`. After this, try to login.

**Comment by hpham04** [comment]
@anovakovic01 
Ah, I see. Just tried to replace https://localhost/tokens by https://localhost/users, it works now
Thank you so much
The request should look like this:
curl -s -S -i --cacert docker/ssl/certs/mainflux-server.crt --insecure -X POST -H "Content-Type: application/json; charset=utf-8" https://localhost/users -d '{"email":"john.doe@email.com", "password":"123"}'
HTTP/1.1 201 Created
Server: nginx/1.13.11
Date: Tue, 10 Apr 2018 07:12:51 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 0
Connection: keep-alive
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Headers: *
