### ISSUE TITLE
Docker Node should be in production mode

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#22]
Docker images are used for production:
- we should install Mainflux with `--production` flag here: https://github.com/Mainflux/mainflux/blob/master/Dockerfile#L23 to avoid installing Node `devDependencies`.
- we should set correct ENV variable here: https://github.com/Mainflux/mainflux/blob/master/config/config.js#L4

**Comment by nmarcetic** [comment]
No. Docker Node should be in development mode. This docker image and compose script is only for development.

**Comment by drasko** [comment]
Please elaborate - why Docker (with Compose) is not good for deployment and what are better strategies?

**Comment by nmarcetic** [comment]
It's ok for deployment, and its mainly used. But this image (this docker file) is writen for development purpose only (with gulp support etc..). It's too early for production image (we don't know the full stack requirements yet).

**Comment by drasko** [comment]
OK, then closing this one. But we must not forget to add `--production` flag to final production Docker images to avoid NodeJS development dependencies from being installed.
