### ISSUE TITLE
Emit non-SenML messages

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#239]
The current implementation of `normalizer` consumes all messages from `msg.*`, normalizes the ones formatted as SenML and publishes them to the `normalized` subject, while it discards the other ones.

In order to support any additional post-processing by vendor-specific consumers, `normalizer` service should emit the non-SenML messages on a separate subject. Below is the proposed subject naming scheme:

| Current name    | New name     |
|-----------------|--------------|
| normalized         | out.senml      |
| N/A                     | out.[type]      |
| channel.[ID]       | channel.[ID]  |

**Comment by drasko** [comment]
@chombium every single content type can be recognized, because it is held in `Content-Type` header of HTTP or CoAP. For MQTT we'll probably have to do something like `channels/<channel_id>/messages/<content_type>` in the API (topic name) itself.

@mijicd would it make a sense that we can consider filtering content type directly in adapters and publishing on a good topic, in order to avoid re-publishing for `normalizer` (which in that case catches only SenML messages)?

Additionally we can have a special `out.all` topic that would contain all messages (of all types) intermixed, in case just one output topic i needed (but I am not sure that we need this).

**Comment by chombium** [comment]
@drasko good point, forgot about the content type header :-/
Content type division might be useful, but I think that the information is what matters, not the format in which it is presented. Everyone knows what kind of devices are connected and in which format the messages are sent, so they can build proper consumers.

On the other hand, the ```normalizer``` should normalize SenML messages. Do we want to add a routing capabilities to it? We should think about separation of concerns here. Adding content type filters in the adapters can be cleaner solution, but once again I think that might be too much responsibility which might have consequences on the performance. Of course we can and should test that.

**Comment by mijicd** [comment]
@chombium `Content-Type` filter is present in the adapters. Normalizer receives messages with provided content type, based on which it makes a decision whether to normalize (if it is SenML), or "forward" if it's not. Keep in mind that the current setup **ignores** all non-SenML messages, forcing you to consume from multiple channels (possibly data in different and unknown format) which is not good.

@drasko content type is present as part of the information in "raw" messages. It is deduced from the header provided, as you said, which needs to be polished for MQTT (we'll discuss on this). Thus being said, adapters are already filtering data, just not directly, but providing enough meta information for it to be separated in later phases. There is no value in having `out.all`.

**Comment by mijicd** [comment]
@chombium Quoting your first message:

```
How will the messages be different from what comes on in.[adapter], except that they will be duplicated and published on a new subject?
```

Yes, it would be a duplicate. The difference is that it will be "triaged" by the normalizer, and it'll let the subscribers consume the data without breaking. Bear in mind that subscribing directly to, for example, `in.http` does not mean that only SenML JSON will be published there, and the subscriber might expect just that.

```
Wouldn't it be better if we only keep it as it is and ship Mainflux with a normalizer for SenML messages only and let everyone else write it's own normalizer based on the message payload that they have?
```

This is exactly what I want to achieve.

```
I understand the idea that it would be nice if we can divide the messages on those that Mainflux can process (SenML) out of the box and the others which need extra processing (non-SenML), but I don't think that we can detect every single type of the message payload so that we can characterize the messages.
```

We cannot guess every single message payload. This is deduced based on the information provided by clients as described above.

**Comment by chombium** [comment]
@mijicd understood, thanks for the clarification.

Having in mind that most of the questions in Gitter are exactly how do I read/subscribe (to) the messages, we would also need good documentation and examples on how the message separation and publishing works.

**Comment by mijicd** [comment]
@chombium documenting these is must-have part of this ticket. However, i think the new naming is much more straightforward than the old one.
