### ISSUE TITLE
How to get mainflux user interface after installation?

### ISSUE THREAD

**Issue by DhurjatiGodavarthi** [absmach/magistrala#253]
I have followed the main flux official documentation and I have got the following out put in the terminal:
dhurjati@dhurjati-VirtualBox:~/Desktop/mainflux-master$ sudo docker-compose -f docker/docker-compose.yml up -d
mainflux-normalizer is up-to-date
mainflux-postgres is up-to-date
mainflux-nginx is up-to-date
mainflux-manager is up-to-date
mainflux-nats is up-to-date
mainflux-mqtt is up-to-date
mainflux-http is up-to-date

After this how to open the UI page?

**Comment by drasko** [comment]
1. Use Markdown to format the code in the GitHub comments
2. This is not an issue so use either mailing lists or Gitter IRC chat
3. Study the architecture before posting any questions
4. There is obviously no UI in this Docker composition, as `dashflux` has not been relesed yet
