### ISSUE TITLE
Replace JWT with plain string tokens in things service

### ISSUE THREAD

**Issue by mijicd** [absmach/magistrala#268]
The current implementation falsely relies on extracting the thing identifier from JWT without checking whether the token exists in the database. Due to this, the usage of UUID as primary key is enforced. 

**Acceptance criteria:**
- replace JWT with plain string access key (e.g. UUID)
- enforce new key's uniqueness in the database schema
- check the token's existence via DB query

**Comment by drasko** [comment]
How will apps (UI, browser, mobile) handle this security, as JWT is something pretty standard in this world.

Will we log-out the users and force re-generation of the key (i.e. something similar to JWT expiration period) in order to mitigate security breaches?

Because of the need for revoking, our JWTs are statefull anyway - but short TTL is something written into the JWT, and here I guess we'll have to track it through the DB.

@nmarcetic any opinions here?

**Comment by mijicd** [comment]
> How will apps (UI, browser, mobile) handle this security, as JWT is something pretty standard in this world.

In most of the cases it's just a matter of setting the appropriate HTTP request headers (i.e. `Authorization`). I don't see the impact of swapping the type of the access key.

> Will we log-out the users and force re-generation of the key (i.e. something similar to JWT expiration period) in order to mitigate security breaches?

The current implementation does not use expiration. Moreover, it has even bigger flaw with it, since there's not a single check whether that token is really associated with client in the DB.

> Because of the need for revoking, our JWTs are statefull anyway - but short TTL is something written into the JWT, and here I guess we'll have to track it through the DB.

Once again, no TTL is written in the current implementation.

**Comment by nmarcetic** [comment]
In one moment we must drop JWT, as @mijicd said we do not track/save and we can't those JWT's.
They are standard, that's true and very nice for clients such is browser, mobile etc... But not so friendly for IoT, size, revoke, we can' track, etc... We spoke about this.
I like this `UUID` even with a combination with JWT or as additional key (when you call API you are providing 2 keys, I saw this on other IoT platforms). But considering the fact that X509 is on our road map, replacing JWT with Bearer token make sense as temporary solution.

**Comment by mijicd** [comment]
As @nmarcetic pointed out in private chat, please note that this addresses *only* the clients service, hence all our clients - devices and applications. Moreover, note that applications are in fact 3rd part systems connecting to our platform, not the individual installations/users.
