### ISSUE TITLE
MQTT Benchmark

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#295]
MQTT benchmark should be made to estimate state of NodeJS MQTT broker and it's integration in Mainflux.

Some of the tools:
- https://github.com/takanorig/mqtt-bench
- https://github.com/hareeqi/mqtt-benchmark
- https://github.com/krylovsk/mqtt-benchmark

It would be interesting to follow free RAM on the instance and it's behavior in dependance of connected clients.

Two thing to take care about:
1. Messages per second
2. Number of simultaneously connected clients

Various strategies can be tried, as brokers do not behave the same if there is many publishers and one subscriber (all messages go on one topic, firehose) and when there are many publishers and many subscribers (messages spread over several topics).

Some ideas:
- https://github.com/surgemq/surgemq#performance
- https://github.com/surgemq/surgemq/tree/master/benchmark

**Comment by windbender** [comment]
I'd like to suggest going away from the notion of "messages per second" and using the idea of PUBLISH messages (a specific meaning in MQTT ) per second.  

Also related is the number of SUBSCRIBE messages per second.  I have seen brokers perform poorly in this area as the complexity of the subscription topics requested went up.

**Comment by nmarcetic** [comment]
Depends on #378 and new MQTT broker.

**Comment by mfinley3** [comment]
Back when I was doing load testing I found this article:  
https://dzone.com/articles/load-testing-of-mqtt-servers-using-java-maven-and
They created a Gatling MQTT plugin that I felt like was sufficient. It seemed to cover both points `Messages per second` and `Number of simultaneously connected clients`. 
If you wanted to keep using Gatling, this might be an option! 

Link to plugin: https://github.com/thingsboard/gatling-mqtt

**Comment by drasko** [comment]
@mfinley3 yes - Gatling would be great choice!

Our load tests fro HTTP and WS are already using Gatling: https://github.com/mainflux/mainflux/tree/master/load-test - so you can add them there.

I think @nmarcetic used so far [Malaria](https://github.com/remakeelectric/mqtt-malaria) and [mqtt-stresser](https://github.com/inovex/mqtt-stresser) for stress tests and had over 100k mps on a single instance of MQTT broker on his PC.

**Comment by nmarcetic** [comment]
@drasko Can this one be closed, due to #817 ?

**Comment by drasko** [comment]
I propose that we keep it until VerneMQ is fully deployed and all measurents are done on typical Kubernetes setup and published here and on our web site.

**Comment by drasko** [comment]
Closed via https://github.com/mainflux/benchmark/pull/6
