### ISSUE TITLE
Setup Let's Encrypt certificate for Mainflux Kubernetes cluster

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#301]
Go through the procedure of set-up [Let's Encrypt](https://letsencrypt.org/) TLS certificate for Mainflu Kubernetes cluster.

Document the procedure.

**Comment by nmarcetic** [comment]
#378 Should close this one.

**Comment by drasko** [comment]
@nmarcetic what's the status of this one? As it is deployment related, I would move it to `1.0`

**Comment by drasko** [comment]
This is DevOps specific, removing from core.
