### ISSUE TITLE
HTTP and WS benchmark

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#304]
Execute HTTP benchmark and document results.

Use Mainflux Kubernetes deployment and inspect auto-scaling feature.

**Comment by nmarcetic** [comment]
Depends on #378 We will do benchmark with new K8 setup.

**Comment by drasko** [comment]
We should move away from Scala-based Gatling to either Go (https://github.com/tsenart/vegeta)  or Erlang-based (https://github.com/satori-com/mzbench) testing tools.

**Comment by drasko** [comment]
We should consider MzBench for this kind of test.

**Comment by blokovi** [comment]
We have new repo now just for benchmarks. There are different testing scenarios for MZbench with results on kubernetes deployment:
https://github.com/mainflux/benchmark
