### ISSUE TITLE
Influx Writer not picking up messages

### ISSUE THREAD

**Issue by matt0x6F** [absmach/magistrala#332]
**BUG REPORT**

1. What were you trying to achieve?

Writing data to InfluxDB from MQTT

2. What are the expected results?

SenML is sent and data is stored in InfluxDB with appropriate field keys

3. What are the received results?

No data is stored in InfluxDB

4. What are the steps to reproduce the issue?

  * Launch a cluster in Google Kubernetes Engine from the k8s config
  * Use any MQTT client and send a message 
    * **example**:`mosquitto_pub -u 1 -P 74aac4b8-702c-44d6-b907-cbad8987e51f -t channels/1/messages -h 35.239.154.92 -p 1883 -m '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]'`
  * `kubectl exec -it mainflux-influxdb /bin/bash`
  * `influx`
  * `use mainflux`
  * `show field keys`

5. In what environment did you encounter the issue?

Google Kubernetes Engine

6. Additional information you deem important:

Notices NATS logs errors with these messages.

```console
I  {"v":0,"pid":1,"msg":"authorized publish","hostname":"mqtt-adapter-8fcddd74d-8rwsx","level":30,"name":"mqtt"} 
I  {"hostname":"mqtt-adapter-8fcddd74d-8rwsx","level":30,"name":"mqtt","v":0,"pid":1,"msg":"disconnect client mosqpub|17049-matt-desk"} 
E  [1] 2018/07/01 00:11:05.439853 [TRC] 10.20.6.10:38770 - cid:2 - <<- [MSG channel.1 2 179]
 
E  [1] 2018/07/01 00:11:05.439714 [TRC] 10.20.6.10:38770 - cid:2 - ->> MSG_PAYLOAD: [mqtt*�[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]]
 
E  [1] 2018/07/01 00:11:05.439147 [TRC] 10.20.6.10:38770 - cid:2 - ->> [PUB channel.1 179]
 
I  Method can_access for channel 1 and thing 1 took 4.752408ms to complete without errors. 
I  Method identify for key 74aac4b8-702c-44d6-b907-cbad8987e51f and thing 1 took 1.968838ms to complete without errors. 
I  {"qos":0,"topic":"","retain":false} 
I  {"msg":"disconnected","hostname":"mqtt-adapter-8fcddd74d-8rwsx","client":{"id":"mosqpub|17049-matt-desk"},"level":30,"v":1,"pid":1} 
I  {"msg":"connected","hostname":"mqtt-adapter-8fcddd74d-8rwsx","client":{"id":"mosqpub|17049-matt-desk"},"level":30,"v":1,"pid":1} 
```

**Comment by drasko** [comment]
Running `docker-compose` with:
```
docker-compose -f docker/docker-compose.yml -f docker/addons/influxdb/docker-compose.yml up -d
```
would make all containers be on the same network and see each other.

This way `writer` will see NATS and connect to it instead of restarting in a loop.

**Comment by dborovcanin** [comment]
As far as I can see, there is no problem with writer itself. I've tried to reproduce this error using docker-compose and everything works just fine. Have you tried to run compose as @drasko suggested? I'm not saying that problem does not exist, just saying that I can't reproduce it on local composition, which made me think that problem is on the cluster configuration side, not on the services themselves. I've tested it with HTTP adapter, not MQTT. A useful article could be found at https://medium.com/mainflux-iot-platform/mainflux-open-source-iot-platform-set-up-and-usage-70bed698791a. Please inform us if you realize what the problem is and if you manage to solve the problem.

**Comment by drasko** [comment]
@dusanb94 @mattouille confirmed that `docker-compose` is working when started as explained. His problem is now k8 setup.
