### ISSUE TITLE
ws swagger.yaml file is missing 

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#337]
I've noticed that we have a [dead link](https://github.com/mainflux/mainflux/blob/master/ws/swagger.yaml) in the [WS Readme](https://github.com/mainflux/mainflux/blame/master/ws/README.md#L57)

We should add the swagger.yaml file or delete the link in the readme file

**Comment by anovakovic01** [comment]
We should remove link to `swagger.yml`, because it was deleted.

**Comment by chombium** [comment]
Now that we have better [description](https://github.com/mainflux/mainflux/blob/master/docs/getting-started.md#basic-nodejs-example) how the ws service is used in the getting started guide we can link it in the Usage paragraph instead of the deleted swagger.yaml file
