### ISSUE TITLE
Thing Model: rename the Payload Field to Metadata

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#343]
As discussed in #342 the [Payload](https://github.com/mainflux/mainflux/blob/master/things/things.go#L13) field  in the Thing model should be renamed to Metadata.

Definition of done:
- [x] all occurrences of Things.Payload are changed to Things.Metadata
- [x] all tests are adjusted and are still passing. Please note that there are some occurrences in the Dasflux's code for which we don't have tests like [here](https://github.com/mainflux/mainflux/blob/master/dashflux/src/app/components/things/things.component.html#L20) and [here](https://github.com/mainflux/mainflux/blob/master/dashflux/src/app/components/things/thing-dialog/thing-dialog.component.html#L26)

**Comment by drasko** [comment]
@chombium not a problem at all, on the contrary - thanks for proposing. Ivan (@blokovi) will take both of these.
