### ISSUE TITLE
influxdb-writer doesn't use the correct host

### ISSUE THREAD

**Issue by ks156** [absmach/magistrala#346]
Trying to follow this tutorial : https://medium.com/mainflux-iot-platform/how-to-connect-raspberry-pi-to-mainflux-fbef303e480c, I have noticed that, in addition to this issue https://github.com/Mainflux/mainflux/issues/345, the host declaration for influxdb-writer is not correct.

I have changed this line : https://github.com/mainflux/mainflux/blob/master/docker/addons/influxdb/docker-compose.yml#L35 
```
--- MF_INFLUX_WRITER_DB_HOST: influxdb
+++ MF_INFLUX_WRITER_DB_HOST: mainflux-influxdb
```

Dunno if it is correct, but at least, it works now.

**Comment by dborovcanin** [comment]
@ks156 Thank you for your effort. We can confirm this behavior and this issue will be resolved as soon as we resolve #345. It is correct, you should use `mainflux-influxdb` here.
