### ISSUE TITLE
Examine Envoy and Istio as a potential NginX replacement

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#352]
[Envoy](https://www.envoyproxy.io/docs/envoy/latest/) proxy and [Istio](https://istio.io/) look like mature enough modern way to handle microservices, and might be better fir for Mainflux project.

Some research is needed to see wha't the effort and benefits from switching to Istio.

Take care especially on the binary size and cross-compiling complexity, as Mainflux should be runnable on ARM IoT gateways as well.

**Comment by nmarcetic** [comment]
It would definitely be a better fit. I took a quick look, there are lot of benefits (they are both intended for distributed systems).  Looks very interesting I will help with research :+1:

**Comment by sking2600** [comment]
EDIT: I got confused by the istio docs and conflated istio/k8s ingress.

While I totally support using envoy to create a service mesh, wouldn't you need to use contour (which is built on envoy) in order to replace nginx as an ingress controller? 

https://github.com/heptio/contour

**Comment by nmarcetic** [comment]
@sking2600 This is good suggestion, worth of considering. 
I am currently checking [Istio project](https://github.com/istio/istio) Which is also built on top of envoy and can be used together with Kubernetes. There is no doubt if Istio is good or not, I am more investigating benefits and downsides of usage in current Mainflux stack. 
More lean and light solution would be to just replace nginx with envoy and use K8 ingress such as contour.
