### ISSUE TITLE
Create SDK

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#354]
SDKs can be created to facilitate programmatic interactions with the platform.

`Go` and `Python` can be used for both platform administration (HTTP drivers) and device messaging (4 protocols).

Pure `C` driver can be used for microcontroller SDK - some examples can be found [here](https://github.com/mainflux/proxy/tree/master/examples).

**Comment by nmarcetic** [comment]
WIP for Go version #357

**Comment by drasko** [comment]
Go SDK has been created and published in `0.7.0`
