### ISSUE TITLE
LWM2M support in mainflux

### ISSUE THREAD

**Issue by akansal1** [absmach/magistrala#371]
LWM2M standard by open mobility alliance already has a good support in embedded side (like zephyr, mbed OS by ARM etc)  for device management and data packet with IPSO alliance etc. 

Considering mainflux is targeting at IOT infrastructure on edge. Is there a plan to have LWM2M support in mainflux ?

**Comment by drasko** [comment]
@sking2600 #374 was opened to bring back CoAP adapter into Mainflux.

@akansal1 LwM2M demands lot of work, it is not immediate priority - but we would accept LwM2M contribution as a Mainflux adapter.

**Comment by akansal1** [comment]
Understood, I was exploring LWM2M as a common spec  for devices with and without gateway. 

I thought, that both OCF and OMA efforts are being merged under OMAspecworks (my interpretation). But, considering there is too much noise in M2M (OneM2M, WOT etc) space, I felt LWM2M could be a good start.
