### ISSUE TITLE
Switch to ingress nginx on k8s setup

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#378]
Current k8s setup uses nginx service for proxy. We should switch to [ingress-nginx](https://github.com/kubernetes/ingress-nginx) instead.

**Comment by drasko** [comment]
Related to https://github.com/mainflux/mainflux/issues/352 - maybe this is also to be considered.

@chombium any opinions?

**Comment by anovakovic01** [comment]
@drasko I would suggest this just as a first step towards enhancing k8s setup. Later we can switch to some other ingress. We can look into replacing it with Istio or Envoy, as you suggested #352. I think that we need stable solution ASAP.

**Comment by chombium** [comment]
@drasko,  I would have also suggested considering [traefik](https://traefik.io) for it's ease of configuration and integration with Lets Encrypt, but having in mind that we are going in Envoy/Istio direction, I agree completely with @anovakovic01.

One thing that we have to consider is that if some one uses a k8s provider with load balancer (gcp for example) and want to use it, we might have to document the routing rules separately in the docs

**Comment by drasko** [comment]
Moving towards Istio/Envoy for gRPC LB, it would be most probably interesting to use [Ambassador](https://www.getambassador.io/) as a GW API.

UDP support for Envoy is still missing, but is being worked upon: https://github.com/envoyproxy/envoy/issues/492

Related to https://github.com/mainflux/mainflux/issues/352 and https://github.com/mainflux/mainflux/issues/387

**Comment by drasko** [comment]
@anovakovic01 what's the status of this one? We need it for `0.7`
