### ISSUE TITLE
gRPC Load Balancing between http-adapter and things

### ISSUE THREAD

**Issue by nwest1** [absmach/magistrala#387]
**BUG REPORT** 

1. What were you trying to achieve?
Targeted TPS load testing against http-adapter and a failure scenario

2. What are the expected results?
balanced, self-healing connections between mainflux components

3. What are the received results?
gRPC not being load balanced, and when a pod is killed, these connections are not rebalanced

4. What are the steps to reproduce the issue?
- Run a load test in kubernetes with multiple replicas (http-adapter is using the `things` service name as url)
- Note that the majority of transactions are running through a single `things` pod and not load balanced
- Kill the `things` pod that's receiving the majority of transations
- Note the error rate spikes and connections from adapter to things remain in error and are not rebalanced.

5. In what environment did you encounter the issue?
kubernetes 

6. Additional information you deem important:
This might be slightly out of scope, as it's possible to solve this with Istio/Linkerd or some k8s ingress that is aware of gRPC. But want to bring it up as it looks like you're exploring similar replacements for nginx.

**Comment by drasko** [comment]
@nwest1 thanks for filing this one.

**Comment by drasko** [comment]
@nwest1 we've analyzed this one, and surely there is a missing LB part for gRPC. Problem is that although k8 adds LB in front of the services, gRPC pass via HTTP/2 and is more like a stream and not balanced via L7 LB. For gRPC we need L4 LB, and most often used is [Istio](https://istio.io/) approach with [Envoy](https://www.envoyproxy.io/)

This is explained well in this video: https://www.youtube.com/watch?v=F2znfxn_5Hg

Additional info:
- https://grpc.io/blog/loadbalancing
- https://blog.bugsnag.com/envoy/

We already wanted to go this route, please consult issue https://github.com/mainflux/mainflux/issues/352.

Although there is a way to avoid using Envoy and LB gRPC on client side, we feel that Envoy approach will be better.

@janko-isidorovic already started integration of Istio/Envoy in our k8 scripts and we should have something working before end of week.

One more approach that can be taken is using NATS and it's [Request-Replay mode](https://nats.io/documentation/concepts/nats-req-rep/) with internal NATS LB in [Queue mode](https://github.com/nats-io/go-nats#queue-groups) + new feature of `Drain` for downscaling: https://medium.com/@derekcollison/nats-resilient-systems-and-drain-mode-a764d4968711. This could eventually make system simpler, but we are not sure would it make easier to debug (i.e. o figure out where the messages come from in the case of error), and we are not sure about perfs of NATS with all these modes enabled. Let's try first Isto/Envoy solution.

**Comment by nmarcetic** [comment]
#378 Closes this issue.

**Comment by nmarcetic** [comment]
@drasko Yes and its related to #378

**Comment by drasko** [comment]
I agree that this depends only on deployment strategy (k8 in this case) and is not at all Mainflux issue. Let's see what is the best way to approach this, we should stay generic and not impose a specific deployment strategy and we need to understand how does this fall in Mainflux project scope.

**Comment by anovakovic01** [comment]
Resolved with #378.
