### ISSUE TITLE
Create Helm package for Mainlfux Kubernetes

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#388]
A [Helm](https://helm.sh/) package needs to be created for Mainflux [k8s](https://github.com/mainflux/mainflux/tree/master/k8s) to facilitate Kubernetes deployments.

**Comment by exocode** [comment]
Maybe I missed it: is the Mainflux helm chart available somewhere? That would be awesome

**Comment by drasko** [comment]
@exocode this issue is a feature request.

There is pending PR waiting for reviews and tests: https://github.com/mainflux/mainflux/pull/550

If you can review and test it it would be awesome.

**Comment by exocode** [comment]
@drasko, of course, I will do what I can :-)

**Comment by nmarcetic** [comment]
All DevOps related stuff is moved to a separate repository [mainflux/devops](https://github.com/mainflux/devops). There are working and tested charts there.
