### ISSUE TITLE
Introduce thing groups

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#397]
The current implementation handles access policies via the connections table. While this is perfectly fine for refining permissions on per-thing basis, it should be noted that most clients share permissions.

Thus being said, we should introduce an entity called group that would enable "bulk" permission handling. Note that every thing will be a member of at least one group, while each group will have at least one thing. Things should inherit permissions from their groups, and override (or expand) them via their own permissions (as in the current implementation).

Acceptance criteria:

- Specified and implemented group API
- Updated the database schema
- Implemented data access layer

**Comment by drasko** [comment]
Related to https://github.com/mainflux/mainflux/issues/931

**Comment by drasko** [comment]
@mteodor please leave here a detailed description (doc) how Thing Groups are currently implemented (what is the latest design decision).

Please do not save words, take @darkodraskovic's [description](https://github.com/mainflux/mainflux/issues/643#issuecomment-687634002) as an example.

**Comment by mteodor** [comment]
Mainflux Thing Groups have a hierarchy and various metadata. Thing Groups can have parents and children, and queries for traversing relationship trees can be implemented.
Thing can be assigned to multiple groups.
Example:
![thing groups](https://user-images.githubusercontent.com/7990113/100599793-c13dc700-3300-11eb-895e-7a2c39c123fe.jpg)

# Thing Groups

- Create, describe or delete a group.
- When creating a group it can have one parent assigned.
- Add a thing to a group, or to more than one group.
- Remove a thing from a group.
- List/Tree view of groups you have created.
- List/Tree view  of all child groups of a group (its direct and indirect descendants.)
- List the things in a group.
- List/Tree view of all ancestor groups of a group (its direct parents.)
-


# Limitations

- You can't change a group's parent or name later. 
- Thing group names must comply to regexp `^[A-Za-z0-9]+[A-Za-z0-9_-]*$`
- A group can have at most one direct parent.
- You can delete a group that has child things, but any permissions granted to the things by membership in the group will no longer apply. 

With policy introduction groups will play a role in attaching policy to a group and thus applying access policy to a group of things.

**Comment by mteodor** [comment]
closed by #1259
