### ISSUE TITLE
Improve MQTT broker logging

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#400]
We need to verify if our MQTT broker logs everything correctly.

**Comment by manuio** [comment]
Remove MQTT broker heartbeat: `mainflux-mqtt   | {"level":20,"time":1545384814228,"msg":"published","pid":1,"hostname":"139dee9c7b36","message":{"topic":"$SYS/1WsM_KnPd/heartbeat","qos":0,"retain":false},"v":1}`
