### ISSUE TITLE
Should things and channels entity ID be UUIDv4?

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#403]
Currently we use Postgres serial sequece number. This ensures consistence (no-conflicting UUID) but is not generic enough - i.e. switching to another DB like CockroachDB is changing the format of ID field.

Should we introduce UUIDv4 here, knowing the drawbacks: https://rclayton.silvrback.com/do-you-really-need-a-uuid-guid, or find some other solution in which we can keep ID derived broth from Postgres and Cockroach.

Also interesting article: https://rob.conery.io/2014/05/28/a-better-id-generator-for-postgresql/

**Comment by drasko** [comment]
@chombium @nmarcetic @anovakovic01 @dusanb94 @srados @blokovi what are your comments on this?

**Comment by drasko** [comment]
@robconery UUIDv4 I mentioned are of type `string`, and unrelated to Postgres - generated by this package for example: https://github.com/satori/go.uuid. I am not sure that other DBs would have `uuid` type (but I am not really DB ninja), and idea here is to have possibility to eventually support other DBs.

TBH, for Mainflux is is not likely to happen, Postges here works just fine and it's a good use-case. We thought that metadata (identities) here needed strong consistency, although it might turn out in the future that people are ready to trade this consistency for easier scalability and flexibility of easily changing data models without complicated migrations.

The only thing that we did try and had very good results is replacing Postgres with CockroachDB v2, which is 1:1 replacement - we did not change one line of code. Cockroach is really easy to scale, and in our Kubernetes deployment it was behaving quite nice. BUt it generated different serial IDs than Postgres (non-icremental). As a note - we use `int64` AFAIK to store these indexes - and it works fine with both Postgres and Cockroach.

Generating UUIDv4 with [aforementioned library](https://github.com/satori/go.uuid) might in some rare cases lead to inconsistency - i.e. conflicts. This is why Twitter created project _Snowflake_:

- https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake.html
- https://developer.twitter.com/en/docs/basics/twitter-ids.html

which was later [archived](https://github.com/twitter-archive/snowflake).

Another interesting article: https://preparingforcodinginterview.wordpress.com/2017/03/21/unique-id-generation-in-distributed-systems/

This project looks very interesting: https://github.com/segmentio/ksuid

There is also this: https://github.com/ericelliott/cuid

@robconery from what I see both `ksuid` and `cuid` are strings. Do you know how this would affect performance in Postgres?

**Comment by anovakovic01** [comment]
This change will be done by resolving #475.
