### ISSUE TITLE
Values of zero are being omitted

### ISSUE THREAD

**Issue by mfinley3** [absmach/magistrala#407]
**(Semi) BUG REPORT**

Noticed this when the value field wasn't being written out onto a kafka topic. 
This may be more of an issue with what protoc generates but I believe Mainflux should account for this. So I wanted to just make sure you all were aware it. 

1. What were you trying to achieve?
Sending a message where the value is zero.

2. What are the expected results?
That the `value` field does not get omitted and contains a value of zero when the message that is sent contains 0.

3. What are the received results?
The value field gets omitted and is non-existent rather than zero

4. What are the steps to reproduce the issue?
The way I found easiest to visualize this, was through subscribing to the NATS channel where the normalized messages are written to (out.senml for example) and then decoding the messages.
- Sub to out.senml and capture the output.
- Send a message containing a zero for the value for example: 
```
[  
   {  
      "bn":"MVP-mikes-fridge-sensor:",
      "bt":1537822790,
      "bu":"degC",
      "bver":5,
      "n":"Temperature",
      "u":"degC",
      "v":0
   }
]
```
- Decode that output using protoc and although a value was sent, it does not appear 

What I am seeing when I do this:
<img width="1467" alt="example" src="https://user-images.githubusercontent.com/9580064/46226475-067d9d00-c322-11e8-9520-396c5b009e64.png">

5. In what environment did you encounter the issue?
Kubernetes 

6. Additional information you deem important:
I believe that a Zero value should be valid and not get omitted anywhere in Mainflux.  Since things like refrigerators/freezers can send temperatures that are 0. 

The issue probably truly lies in protoc/go since protoc generates message.pg.go:
```
type Message struct {
        ...
	Value                float64  `protobuf:"fixed64,6,opt,name=Value,proto3" json:"Value,omitempty"`
        ...
}
```
Due to a combination of omitempty getting added and zero being considered empty in go, the `Value` field does not get populated. 

Let me know thoughts about this!

**Comment by anovakovic01** [comment]
Judging from this [issue](https://github.com/grpc/grpc-go/issues/481) I would say that for message serialization and deserialization we should use `http://github.com/golang/protobuf/jsonpb` instead of standard `encoding/json` lib.
