### ISSUE TITLE
Change CLI commands output

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#419]
**FEATURE REQUEST**

It would be nice to change the CLI output (probably to JSON) so it's easy to parse it.

Example use case is:

- create user
- extract user token
- create channel (by using user token)
- create thing (by using user token)
- extract thing token
- connect thing to channel (by using user token)
- publish message (using thing token)

The commands above need to have the output which is easy to parse in order to make scripting/command piping simple.

I think this is a should-have feature

**Comment by anovakovic01** [comment]
Resolved by #504.
