### ISSUE TITLE
Allow custom certificate authorities to be optionally specified in any grpc.Dial

### ISSUE THREAD

**Issue by nwest1** [absmach/magistrala#426]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

We're running into errors when a grpc client calls into an ssl-enabled grpc things or users endpoint. I was thinking about adding something like an optional `CA_CERTS` environmental variable. When set, will try to read the file path provided, and provide `grpc.credentials.createSsl(root_certs)` to the `grpc.Dial` function. 

A quick search reveals a few places where the insecure connection exists:
- [ ] `cmd/cassadra-reader/main.go`
- [ ] `cmd/http/main.go`
- [ ] `cmd/influxdb-reader/main.go`
- [ ] `cmd/mongodb-reader/main.go`
- [ ] `cmd/things/main.go`
- [ ] `cmd/ws/main.go`
- [ ] `mqtt/mqtt.js`

Open questions:
- Does this seem like a reasonable approach?
- Should I include a pem of CAs by default? If so, where should that come from?

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
For us it's a must-have.

We've tested out these changes successfully, but want to get feedback and make it properly configurable.

**Comment by drasko** [comment]
@nwest1 in current implementation we protect the whole Mainflux system only by NginX edge proxy and we consider that everything behind this proxy is on the private and secure network. I.e. no encryption is needed between Mainflux components themselves.

This is why your approach is totally untested by us. In theory it should work.

@anovakovic01 can we provide some example for `grpc.credentials.createSsl(root_certs)` cert set-up - did we do something similar for SDK?

**Comment by anovakovic01** [comment]
@nwest1 We use these `gRPC` endpoints only for internal communication. That's why we haven't exposed it to the outside world and haven't protected it. If you want to use certs, we recommend doing that on nginx (or some other proxy) level.

**Comment by drasko** [comment]
I agree with this recommendation from @anovakovic01 - let's keep Mainflux code simple and if needed for specific cases where it is deployed over insecure network - then reverse proxy with TLS termination could protect a specific microservice.

@nwest1 would this work for you?

**Comment by chombium** [comment]
@nwest1 @mainflux/contributors  envoy can also do tls termination. As we already discussed the usage of envoy for the k8s deployments, we could use it for tls termination as well and harden the . There is probably something similar for the docker deployments as well.

Adding tls termination in the services would be the safest thing to do, but we should also take care about debugging and message traceability in case of problems. For easier troubleshooting and development, it would be nice if the tls encryption can be somehow switched off or if we add better logging and log all the messages. Having a tls switch or log with all of the messages sounds a bit scary and bad security practice, but in order someone to switch the tls off or read the logs he/she needs access on the machine (s)/cluster and that's already too late to defend anything.

I think we should also start a discussion about the security of our deployments in general.

What do you think about this?

**Comment by drasko** [comment]
@chombium I do agree, and our proposal is to let @nwest1 and his team proceed with securing traffic between microservices. We will accept PRs and help with integration.

Idea is to have this inter-microservice TLS encryption as an option (not mandatory), and what is left is also to find the best way to manage certificates - probably through [Vault](https://www.vaultproject.io/).

We are also working on specs for certificate-driven auth, some brainstorming can be found here: https://github.com/mainflux/mainflux/issues/367, and I think Vault can help us generate these certs. I do support all discussions and improvements on security, I think that it it crucial part of Mainflux functionality.

**Comment by sking2600** [comment]
+1 for the suggestion to use envoy/istio from @chombium. It'd require little to no modifications to application code and istio citadel can handle certs.

**Comment by nwest1** [comment]
For us, it would be enough to enable clients to be configured with a list of trusted certificates. We don't necessarily need to terminate TLS at each service.

I'll get a PR out and we can discuss.

**Comment by ghost** [comment]
I think having TLS termination at the service level is a good option to have. If someone doesn't want it, he/she would be able to turn it off .

**Comment by drasko** [comment]
@nwest1  can this one be closed now?

**Comment by nwest1** [comment]
Hello! Sorry about the delay :) 🎅 🎄
