### ISSUE TITLE
Add DTLS support for NginX

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#428]
CoAP is UDP-based protocol, and needs DTLS (instead of TLS for MQTT).

Mainflux TLS/DTLS termination is done on NginX, but NginX has still experimental DTLS support.

It is needed to enable this experimental support (by adding patches) and try the implementation.

- https://twitter.com/nginxorg/status/865227991718043648
- http://mailman.nginx.org/pipermail/nginx/2017-May/053838.html
- http://nginx.org/patches/dtls/
- https://github.com/linaro-technologies/gateway-containers/tree/master/nginx
- https://www.eclipse.org/lists/leshan-dev/msg00796.html

NginX Plus R16 includes official DTLS support: https://www.nginx.com/blog/nginx-plus-r16-released/#r16-udp

This issue is low priority for now, as Mainflux CoAP is still experimental, and it would be good not to patch and recompile NginX - but rather use official DorckerHub container image.

**Comment by ghost** [comment]
There is a pure golang DTLS having in the pions GitHub org.
It's being done for webrtc.

Should help heaps..

**Comment by drasko** [comment]
@gedw99 I was referring to official support: https://github.com/golang/go/issues/13525

Anyway, since we do TLS termination on reverse proxy, I think it would me more important to make NginX DTLS work.

**Comment by ghost** [comment]
but the golang team have put it off.

The pions crew are doing well on it here:
https://github.com/pions/dtls

Also abstracting the webrtc transport to a standard golang dialer here: https://github.com/pions/dcnet

Pleae let me know if this all helps ?

**Comment by drasko** [comment]
Will be solved via https://github.com/mainflux/mainflux/issues/1175 (we'll move TLS/DTLS implementation on our Go code).
