### ISSUE TITLE
Add SSL encryption to the MongoDB, InfluxDB and Cassanda readers

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#442]
The  MongoDB, InlfluxDB and Cassandra reader's message endpoints work over unencrypted HTTP connections.

It would be nice if we secure them with SSL (TLS) and use HTTPS as in the other services.

**Comment by chombium** [comment]
Closed via #459 
Kudos to @anovakovic01

**Comment by anovakovic01** [comment]
@chombium #459 only adds support for gRPC clients on reader services, we still don't have TLS secured HTTP endpoints, so I will reopen this one.
