### ISSUE TITLE
Native deployment

### ISSUE THREAD

**Issue by nguyen-phuoc-dai** [absmach/magistrala#446]
**FEATURE REQUEST**
is it possible to deploy the mainflux on native without docker? If yes, please give me the link or document how to do that

Thanks

**Comment by drasko** [comment]
This is what `make rundev` target does: https://github.com/mainflux/mainflux/blob/master/Makefile#L77 and the script

You should follow [Developer's Guide](https://mainflux.readthedocs.io/en/latest/dev-guide/) to understand how to install dependencies - like Postgres, Redis, etc...

**Comment by nguyen-phuoc-dai** [comment]
I will give it a try
Thanks for your advise
