### ISSUE TITLE
Give option to connect to Postgres with SSL (Things & Users)

### ISSUE THREAD

**Issue by mfinley3** [absmach/magistrala#448]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

Might be related/similar to #442 - Feel free to close this and I can add to that issue if that is prefered.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

The postgres connection string for Things and Users currently does not have an option for picking between disable, require, etc while connecting to the DB. This would add a flag such as: 
```
| MF_THINGS_DB_SSL_MODE | SSL mode to connect to the database with | disable        |
```
Allowing someone to pick the ssl mode.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

This is a must have for us as any db we can connect to, at minimum, requires ssl making disable not an option. 

I currently have this implemented in a way that supports both disable and require but not verify-ca or verify-full. If it makes sense, I can open a PR now that supports disable and require as a first step towards fully supporting this and we can come back to verify-ca and verify-full. 

 https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters

**Comment by mfinley3** [comment]
I'd suggest keeping this one open and using it as the issue to now also allow connections using `verify-ca` and `verify-full`. 

@anovakovic01 had mentioned that it might be best to add separate env vars for the config that is required for those options. 

From the brief look I took at pq docs, it looks like there would need to be three config options to do this:
```
sslcert - Cert file location. The file must contain PEM encoded data.
sslkey - Key file location. The file must contain PEM encoded data.
sslrootcert - The location of the root certificate file. The file must contain PEM encoded data.
```

There is also the possibility of leveraging the other cert env vars, but I agree and also think it might be best to keep them separate as well.

**Comment by drasko** [comment]
@anovakovic01 @mfinley3 any updates on this one?

**Comment by mfinley3** [comment]
@drasko Not yet, I've had some other issues appear on my plate. I am still willing to tackle this, I need to finish up what I am working on and then should have a cycle to get a PR out (_maybe_ end of the week). If it's needed sooner we can figure that out. - just let me know!

edit 12/10 - Working on this now @anovakovic01 & @drasko
