### ISSUE TITLE
PSK ( Pre Shared Key ) authentication for Devices

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#462]
Hello, 

We want to create a PSK ( Pre Shared Key ) mechanism for our devices. However, the key field of things table has a unique constraint. Also, it's used to identify the device uniquely. So it seems impossible implementing the PSK in this condition. 

- As a scenario, device manufacturer come with 100.000 predefined passwords of devices and they want to on-board devices on the platform, but the uniqueness of the password field may prevent this because these devices passwords can overlap with previous devices on the system 
           
-  Also, we have some security concerns about the unique small tokens. Because, if somebody knows that password exist on the system, other device security could be vulnerable.  

How could PSK be implemented to the system? Can PSK auth mechanism be added as a new feature to main-flux? 

Thanks for your help
Emre Yavuz

**Comment by drasko** [comment]
@EmreYavuz216 thanks for opening the issue. @dusanb94 is currently working on onboarding procedure and we will need this feature.

We are thinking rather about having a separate `bootstrap` server or API endpoint so that devices with the same password can do onboarding.

Regarding password length - would you suggest that just longer passwords would solve the issue?

**Comment by drasko** [comment]
It should also be noted that Google IoT Cloud has practically the same approach to AuthN/AuthZ: https://cloud.google.com/iot/docs/how-tos/mqtt-bridge

_The username is ignored, and the password field must contain the JWT. Note that some MQTT client libraries will not send the password field unless the username is specified. For best results, supply an arbitrary username like unused or ignored._

**Comment by drasko** [comment]
Realed to https://github.com/mainflux/mainflux/issues/539

**Comment by drasko** [comment]
Bootstrap Service has been merged into Mainflux. Closing this one because of inactivity. Please reopen if needed.
