### ISSUE TITLE
Add a correlation ID for debugging/tracing

### ISSUE THREAD

**Issue by nwest1** [absmach/magistrala#477]
**FEATURE REQUEST**

The ability to trace and correlate a message would be helpful for debugging / tracing.

I'm not sure if this makes sense to be a full opentracing implementation - especially with the multitude of adapters, but a correlation ID (passed-in or generated, and also included in the output) would be valuable.

This would be a nice-to-have.

**Comment by anovakovic01** [comment]
We have this one on roadmap already. Closing this one as it's duplicate of [this issue](https://github.com/mainflux/mainflux/issues/399).

**Comment by nmarcetic** [comment]
@nwest1 Let's continue discussion here #399

**Comment by drasko** [comment]
Yes, @nwest1 please tell us if you need some specific format, or propose some specific implementation. As @nmarcetic we can brainstorm around this on #399.
