### ISSUE TITLE
Enable channels and devices corresponding lists in backend

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#483]
Currently devices connected to channels are kept in a `channel` entity list. It poses however the problem for apps and UI to get a list of channels to which one device is connected to, as devices do not keep corresponding list.

**Comment by chombium** [comment]
are we going to add `things/{thing_id}/channels` endpoint and the  /things response will contain the channels as well?

As one thing can be connected with many channels, it may happen that the response is too big and in some cases contains not needed data. It would be nice if we add a parameter to all exposed apis which will define which entity fields should be contained in the response. I'll create an issue about this

**Comment by drasko** [comment]
I was thinking at one point maybe to have a separate entity `connection` that would be just a mapping table of `things` and `channels` that are inter-connected... But maybe this is an overkill.

**Comment by asifiqbal-ai** [comment]
I am not sure it is bug or not but i recently installed recent version i.e 0.7.0. I have created two users and channel information is exposed among different Users. Although user cannot add or delete devices from channel but I think it suppose to stick with user and should not expose to other users.

**Comment by chombium** [comment]
@drasko adding separate entity would be ok. IMO adding a separate endpoint like `/connections/{thing_id}` would be an overkill, except in cases where the user wants to get all his/hers connections.
I think most of the time the questions are: Which channels is this thing connected to? and Which are the zhings connected to this channel?

I think the best way to solve this is to add a new endpoint to the things and channels as follows:
* /things/{thing_id}/connections
* /channels/{channel_id}/connections
