### ISSUE TITLE
Add bulk provisioning via CSV files

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#484]
An API endpoint should be added so that we can send a CSV file and do automatic provisioning of a series of entities.

This provisioning should be done in a transaction, so that we can roll-back the changes in the case of error.

**Comment by nwneisen** [comment]
I'd like to take a look at this. 

From what I've gathered so far, provisioning using a CSV file is already implemented in the CLI and now needs to be added as an SDK endpoint.  The CLI should probably be changed over to use this endpoint so this issue would involve moving the CLI code to the SDK and then making the CLI call the SDK code.

**Comment by drasko** [comment]
@nwneisen implementation in CLI is pretty naive - just a sequence of commands. This is not done in transaction and has no roll-back procedure.

It was put there temporary until backend implements this feature.

@nmarcetic and @anovakovic01 can confirm, but this CSV bulk provisioning should be done in transaction.

**Comment by nwneisen** [comment]
@drasko Yes, definitely add transactions with rollbacks and look for additional optimizations.  I see that sqlx has a couple of functions for creating transactions that can be committed or rolled back.

**Comment by nwneisen** [comment]
I have this working in #889 for things.  Looking for feedback while I make the changes to channels as well.

I'm curious about how strict the requirements are to upload the CSV file.  A cleaner implementation might be to have the endpoint accept JSON and then have SDK functions which accept different file formats and convert them to JSON.

**Comment by drasko** [comment]
@nwneisen fantastic!

I would say that requirements are not at all strict regarding CSV, that was just one thing that we saw most used traditionally.

I imagine a following scenario - an engineer gets a list of devices from factory / HW supplier in an Excel sheet, and then it would be easy to convert it to CSV and provision.

But yes - if we can do this conversion CSV->JSON on the fly and expose REST API that accepts JSON - why not.

I would like to hear opinions form other @mainflux/maintainers.

@nmarcetic @anovakovic01 @dusanb94 @manuio @srados

**Comment by ghost** [comment]
yes, CSV is not a strict requirement, it's just what people often use for this kind of stuff, I guess.

**Comment by manuio** [comment]
@drasko @nwneisen I agree to have an endpoint that accept JSON or that at least accept JSON and CSV. From an UI it's easy to convert any format to JSON.

**Comment by chombium** [comment]
@drasko @nwneisen The important thing is that we have some machine readable format for bulk provisioning. I don't mind if it's JSON or CSV. It would be nice if we add validation of the upload files at least that all required fields are filled. The other option would be to do best effort to import as much "records" as possible and report the failed once.

I agree with @srados that the CSVs are the most used for this, but it would be nice if we have both JSON and CSV.

**Comment by ghost** [comment]
JSON format can be made different issue. This one says csv

On 19 October 2019 11:34:19 CEST, Jovan Kostovski <notifications@github.com> wrote:
>@drasko @nwneisen The important thing is that we have some machine
>readable format for bulk provisioning. I don't mind if it's JSON or
>CSV. It would be nice if we add validation of the upload files at least
>that all required fields are filled. The other option would be to do
>best effort to import as much "records" as possible and report the
>failed once.
>
>I agree with @srados that the CSVs are the most used for this, but it
>would be nice if we have both JSON and CSV.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mainflux/mainflux/issues/484#issuecomment-544120410

-- 
Sava Radoš
E-mail: sava@bitsfactory.com
Mobile: +381 64 130 11 60

**Comment by nwneisen** [comment]
@chombium The entities are added in a transaction so if one fails or there is another error then they will all be rolled back.  This does make me think to try and send the record containing the error in the response.  Hunting down a bad value in a CSV containing thousands doesn't sound like much fun...

@srados @chombium I've switched the PR to use JSON with the endpoint rather than uploading a file.  This cleaned up the code and made it match the patterns of other endpoints.  Reading from a CSV or JSON file is done within the SDK and is setup so additional file types, such as XML, would be easy to add in the future.

**Comment by drasko** [comment]
@nwneisen this approach looks good to me - JSON support in backend, let frontends support various transformations `<format>2JSON`.

**Comment by nmarcetic** [comment]
I agree about JSON only, It would be nice to have both as @chombium suggested, but it's more for end-user then m2m. I vote for JSON only and SDK support CSV->JSON for other clients, let them do a conversion on their side and consume our JSON API.

**Comment by manuio** [comment]
@drasko @nmarcetic After to think about I agree with having only JSON. Specially to simplify the validation of metadata. Let people do this conversions and validations in their apps.

**Comment by nmarcetic** [comment]
@nwneisen I did a review of #889 Good job, really. 

I was thinking, maybe you can add bulk connect later in separate PR :) To fully bulk automate provision process. Because if you create things and channels by batch call, but you must manually connect them hm... you have pain, right? What if have an endpoint where I can pass a list of channels and things that I want to connect, would that be useful, what do you think @mainflux/contributors ?

**Comment by drasko** [comment]
@nmarcetic I think this is a great idea.

I was thinking that we'll solve this with groups, but I think that this can also be very useful!

@nmarcetic can you please go on and open a new issue for this?

**Comment by nmarcetic** [comment]
@drasko Ok I will open an issue.

**Comment by manuio** [comment]
@drasko @nmarcetic I agree with the idea of connection. However, I think that this should be done at the same time that you create your things and channels. Otherwise you will have to fill in the connect CSV with names or IDs and this can also be very painful.

**Comment by drasko** [comment]
@manuio these operations are independant and should be implemented independently.

We should not force user to create things to benefit from batch-connect.

**Comment by manuio** [comment]
@drasko It's not a question of forcing people. Let the bulk endpoints as they are but for the connect one consider creating things and channels before. Otherwise you force people to fill in a CSV with Things and Channels IDs. If you have thousand or millions, good luck :)

Maybe I can comment this in the new issue.

**Comment by nmarcetic** [comment]
@manuio I agree with @drasko   We dunno what people want to connect and how and if they want to connect at all (maybe not in same action, rather later). Maybe they don't want channels at all, just things. I think its good to keep it as separate actions. I understand your concern but for this, you will have zero-touch provisioning (e.g plug and play).

**Comment by manuio** [comment]
@nmarcetic I agree. My comment was about issue #898
