### ISSUE TITLE
Unify `thing` entity - remove `device` and `app` types

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#488]
Initcially `thing` entity had two types: `device` and `app`. Main reason for this was that apps had short TTL JWT token, while devices had JWTs that never expire.

Since our tranistion to simpler API key (in UUIDv4 format) - which was mostly needed because of CoAP lenght of `Option` header that carries bearer token and is limited to 256B -  this division becomes artificial.

We should remove `thing` types and have all things of a single type - simply `thing`.

Later we can introduce different types of tokens that can be associated to a `thing`, but there is no reson to have a device with expiting and rotating key, as well as application with permanent key - so this kid of division we have today does not make sense.

**Comment by chombium** [comment]
@drasko could you please clarify if we are going to remove the "type" field or we gonna set "thing" as default value for type?

After reading the description few times it seems to me we should delete the field

**Comment by drasko** [comment]
Yes, the field `Type` is not needed and should be deleted.

**Comment by drasko** [comment]
@anovakovic01 please note that `Metadata` has to be JSON map, searchable in PostgreSQL, so that we can reause it if we need different thing types and other struct members.

**Comment by anovakovic01** [comment]
@drasko Metadata already has JSON type in DB. We don't need map in `things` service, because you don't know what metadata will contain, and you'll probably never access that content from inside `things` service.

**Comment by anovakovic01** [comment]
This one should be resolved later as it depends on design of new Auth service.

**Comment by manuio** [comment]
For now there is no difference between types but users have to specify one. It can be confusing. I propose to preset type `device` on thing creation and don't communicate about until there is a clear solution.

**Comment by manuio** [comment]
Finally, we agree to remove `type` field and to just have `Things`. Eventually Thing `metadata` can be used to specify this type.
In the future if we really need it we will think about how to introduce Applications in the system as a separated entity.

**Comment by manuio** [comment]
Fixed here: https://github.com/mainflux/mainflux/pull/718
