### ISSUE TITLE
Issues in docker demployement

### ISSUE THREAD

**Issue by asprakash** [absmach/magistrala#49]
After I docker-compose up, the micro services are started running. I can see the 'mainflux' welcome text logo. However, I am getting the following error, 

Error: Uncaught, unspecified "error" event. (Could not connect to server: Error: connect ECONNREFUSED 127.0.0.1:4222)
mainflux-ws      |     at Client.emit (events.js:144:17)
mainflux-ws      |     at Socket.<anonymous> (/mainflux-ws/node_modules/nats/lib/nats.js:389:14)
mainflux-ws      |     at emitOne (events.js:77:13)
mainflux-ws      |     at Socket.emit (events.js:169:7)
mainflux-ws      |     at emitErrorNT (net.js:1253:8)
mainflux-ws      |     at doNTCallback2 (node.js:441:9)
mainflux-ws      |     at process._tickCallback (node.js:355:17)
mainflux-ws      | [09:53:57] [nodemon] app crashed - waiting for file changes before starting...

Also not sure how to view/access IOT platform on the browser. No such getting started document available on the wiki page. 

TIA,
Prakash.

**Comment by drasko** [comment]
@asprakash yes, there is tones of issues now with Docker as we are switching to Go (from NodeJS).

It should be stabilized once @janko-isidorovic and @nmarcetic take care of https://github.com/Mainflux/mainflux/issues/43 and  especially https://github.com/Mainflux/mainflux/issues/44.

If you have some knowledge and you want to give them a hand, every help is highly appreciated!

**Comment by drasko** [comment]
@asprakash this whould be fixed now.

Can you please re-test and tell us if it works.
