### ISSUE TITLE
Searchable metadata field

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#499]
In order to provide better usability of the data stored in the metadata fields
of the Mainflux's entities, we should enable the users to search for entity instances
based on the data in the metadata field.

## Features
* the metadata will be stored as a searchable JSON;
* the user can set one or more search parameters (key/value pairs) by which he/she filter the entity instances. The keys/value pairs are key/value pairs in the metadata JSON;
* As we don't know what will the structure of the metadata JSON be, to enable faster search, we must provide an API for creating indexes

## API Design

* `<entity>/search`

 __Methods__:
   * GET - returns the metadata from all entity instances or from a specified entity instance

__Parameters__:
    

1.  `metadata_fields` - specifies which metadata fields should be returned. If the metadata is too big it would be good to have an option to specify which part of it should be returned.
Example : `<entity>/search?metadata_fields=field1,field2,field3...`

2.  `field1=value1&field2=value2` - adding field name and field value pairs trigger filtering (search) by these values. The field names are the key names in the metadata JSON.
Example: `<entity>/search?field1=value1&field2=value2&field3=value3...`

3. `limit=X&offset=Y` - pagination of the results
Example: `<entity>/search?limit=X&offset=Y`

Example:
`/things/search?metadata_fields=type,name,location&type=app&location=floor0&limit=10&offset=0`

* `<entity>/metadata_fields`

  Methods:
    * GET returns union of all the metadata fields (JSON keys) from all entity instances.

* `<entity>/metadata_indexes/:index_id` -  indexes for the metadata
  Methods:
   - GET returns all indexes set for the metadata or a single index if the index_id is set
   - POST creates an [GIN](https://www.postgresql.org/docs/current/gin-intro.html) index
   - DELETE deletes an index

## Technical implementation

* All of the metadata fields in the database will be converted to [PostgreSQL JSONB](https://www.postgresql.org/docs/current/functions-json.html), because it is indexable and optimized for searching inside the JSON contents. Database migrations should be implemented.
* A new Metadata entity will be introduced which will wrap all the DB calls and will expose a standardized internal API for use by the all other Mainflux entities which will have a metadata field
* all existing entities which use metadata will use the new Metadata entity
* all existing entities which use metadata will have to implement the defined APIs for Metadata searching.

### Useful links:
1. [Explanation of JSONB introduced by PostgreSQL](https://stackoverflow.com/questions/22654170/explanation-of-jsonb-introduced-by-postgresql)
2. [Replacing EAV with JSONB in PostgreSQL(perfomance comparison JSON vs JSONB and different JSONB query styles)](http://coussej.github.io/2016/01/14/Replacing-EAV-with-JSONB-in-PostgreSQL/)
3. [Handling JSONB in Go Structs](http://coussej.github.io/2016/02/16/Handling-JSONB-in-Go-Structs/)
4. [Faster Operations with the JSONB Data Type in PostgreSQL](https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/)
5. [When To Avoid JSONB In A PostgreSQL Schema](https://heapanalytics.com/blog/engineering/when-to-avoid-jsonb-in-a-postgresql-schema)

## Open questions

1. Should we call the single data properties in the metadata fields (as entity fields) or should we keep them in sync with the "JSON vocabulary" and call them keys instead?
2. What to do if for different instances in the metadata fields there are keys which are the same, but they have different structure: in one entity it's a string, number or object in another?
3. Should there be combined filtering by metadata key/values and other field values filters from the entity?
4. Should we add selector for the returned field for all other entities as well(this would be another ticket)?
5. Should we add search for all other entities like Channel etc. (this would be another ticket)?

**Comment by anovakovic01** [comment]
@chombium I don't like the idea of exposing internal structure. If someone wants to use this `metadata` field, there are other ways to do that. One of them is fetching `metadata` from Redis streams. One can fetch these events and store `metadata` inside some other DB (e.g. ElasticSearch). This way one can have service that is dedicated to metadata searching without any impact on core Mainflux services.

**Comment by chombium** [comment]
@anovakovic01  I understand your concerns, but at the moment for the metadata field we don't have any restrictions except it's format that has to be JSON. There is no exposure of internal data srtucture except for the structure of the metadata JSON which is already user defined. On the other hand our project is open source, so the one who can read the code, can see what the internal structure looks like ;)

I proposed this solution because it does not use any extra components and it can be done completely in code, but I agree that depending on the number of the devices and the different possible queries it can be a bit slow. I like your proposal of using ElasticSearch. We can start using it for metadata/device search and then expand the indexers to support all our entities.

I'll open another ticket for the metadata/device search using ElasticSearch and start doing some tests.

**Comment by anovakovic01** [comment]
@chombium Sorry for not being clear enough. By exposing internal structure I meant that our choice of DB and our API would be too coupled. If we decide one day that we want to replace PostgreSQL with something else, we will have to break our API which would be PostgreSQL specific. One way to avoid this is to design our own query API, and our own indexing API. But still, this could cause performance downgrade in some cases. So I agree with you that we should add separate service that will be able search and index this `metadata`.

**Comment by drasko** [comment]
@chombium just FYI, we are examining Redis as a potential PostgreSQL alternative. We will keep support for Postgres, but new redis has great features, is more lightweight and more suitable for the edge.

**Comment by chombium** [comment]
@anovakovic01 once again, thanks for the clarification. I proposed the changes with keeping the API stable in mind without taking care what the data store would be. The whole service would have been implemented so that the only thing that changes would be the data store would be. The only specific thing to each data store would have been the querying and creating indexes. It would have had an interface for CRUD  and create and drop index whose implementation would have been data store specific.

@drasko Thanks for the info. I guess we should talk more often ;)
I know that I'm so to speak one of the few long term contributors which are not employed by the Mainflux company, but I think it would be nice if there is a roadmap which describes the project vision and direction or even a (bi)weekly call free to join for everyone who's interested in which the future plans will be discussed. Even an informal list of decisions and project directions (with exclusive right to change by the Mainflux employees) would be useful, so that we all now what's expected from the project to be and where it goes in order not to spend to much time and energy on trying to implement things which will not be needed/accepted.

If we move to Redis we have to be careful not to force the users to use its enterprise version. Supporting different data stores would be also interesting, but we'll have to refactor all of our services and implement some kind of DAO layer or ORM which will  bring the support for different DBs.

**Comment by anovakovic01** [comment]
@chombium Yes, this is also one of the possible solutions, but we should be careful. I'm not sure that we can make good API spec that will be independent from DB choice in this case. I would like to see some suggestions for this API, so if you have time to start this spec, it can be of great help. Also, we have `repository` interface, so all you need to do in order to switch DB is to implement it and set this implementation in `main.go`. And this goes for every service that communicates with DB. This means that we already have good foundation for adding multiple repository implementations and adding support for multiple DBs.
Regarding roadmap, I agree with you. Maybe we can add this to `README.md`? @drasko what do you think?

**Comment by drasko** [comment]
@chombium yes, definitely we need more coordination. Since more and more comapnies start to use Mainflux in their enterprise and commercial products and depend on open-source support, I would like to introduce a montly call (maybe later chanegd to biweekly) so that we can discuss on the roadmap and developemnt.

I will send an e-mail on mailing lists and announce this meeting soon.

It should be also announced on README - I like how guys from harbour project did this: https://github.com/goharbor/harbor

@anovakovic01 I always thought that Reoadmap must be clearly communicated on README.

**Comment by chombium** [comment]
@drasko could you please send me a link to the mailing list as I'm not subscribed to it and I could not find anything in the repo?
