### ISSUE TITLE
Store and visualization multiply SenML messages (multiply values, measured at the same time) in Mainflux

### ISSUE THREAD

**Issue by akakiev** [absmach/magistrala#502]
I have created measurement system with Mainflux and measurement device. I use InfluxDB to store data and Grafana to visualization my measurements. My measurement device sent multiply SenML messages to Mainflux. It looks like:
```
[{"bn":"cashier-1-:","t":1544457886,"n":"fVBeg","v":1,"u":"dl"}, {"t":1544457886,"n":"fVInc","v":12,"u":"dl"},{"t":1544457886,"n":"fVSld","v":34,"u":"dl"},{"t":1544457886,"n":"fVAccd","v":220,"u":"dl"},{"t":1544457886,"n":"fVOv","v":340,"u":"dl"},{"t":1544457886,"n":"fFiscVol","v":999,"u":"dl"}]
```
There is a problem in Mainflux:
in InfluxDB (`SELECT * FROM "messages"`) at time 1544457886 saved only last value 999 but as you can see from my multiply SenML message at time 1544457886 there are 6 values – 1, 12, 34, 220, 340, 999.
I want these six values to be saved in database and I want it to display in Grafana.
From multiply values, measured at the same time, Mainflux saved only last value, but not all values. 
How to solve the problem ?

**Comment by dborovcanin** [comment]
Hi, @akakiev. As of #501, you can use the `name` field to differentiate records.

**Comment by drasko** [comment]
@dusan I think we need to push `latest` Docker images to DockerHub ASAP.

**Comment by rpolitex** [comment]
@dusanb94 
Hi, 
As I understand from  @akakiev comment, he asked about the problem, when **different** SenML records that have the **same** "t" field are not properly stored (only the last record is stored replacing the previous one in the DB). 

Please correct me and clarify do the #501 fix this behavior?

Thanks for your awesome work.

**Comment by drasko** [comment]
@rpolitex yes - this is solved by #501 because currently recods on the same channel and the same published form one InfluxDB tagset - so when time fields are same one value overwrites other. Now `name` is [added to a tagset](https://github.com/mainflux/mainflux/blob/master/writers/influxdb/messages.go#L129).

Just to mention - this was not a bug. It really depends how you want to write your messages in InfluxDB, and we provide just one reference implementation which you can change to suit your needs.

You can read more about this [here](https://github.com/mainflux/mainflux/issues/454).

**Comment by rpolitex** [comment]
@dusanb94
Understand. Thanks for a great explanation and for your outstanding product. 
Guys you’re awesome!

**Comment by dborovcanin** [comment]
@rpolitex You're welcome! Thanks for the feedback. As @drasko explained, this really depends on the way you want to store your data. If you are familiar with Go (and even if you're not), it's really simple to customize InfluxDB writer moving Message fields from the tag set to field set and vice versa. 
@akakiev If what @drasko and I wrote answers to your question, should we close this issue and mark as resolved?

**Comment by rpolitex** [comment]
@dusanb94
I see.  I’m not too familiar with Go, but code in Writer is very straightforward, so customization is really nice idea.
 Could you advice, should I recompile whole platform from scratch after such customization? Is there any documentation for compilation process. 
Thanks again.

**Comment by dborovcanin** [comment]
No, not at all. You only need to recompile a specific service and restart it. You can use our Makefile for that, simply `make influxdb-writer` and binary will be updated in `build` directory. You probably should also do cleanup in your InfluxDB. If you use Docker, you'll need to update docker image using `make docker_influxdb-writer`.
You can find more info here: https://mainflux.readthedocs.io/en/latest/dev-guide/.

**Comment by rpolitex** [comment]
Cool, thanks.
I wish you a greate success!

**Comment by akakiev** [comment]
@dusanb94 Do you push` latest ` Docker images to DockerHub (https://hub.docker.com/u/mainflux/) ?
If so, you may close this  issue and mark it as resolved.
Thank you for help.

**Comment by manuio** [comment]
@akakiev yes we did it, Dockerhub images are up to date. Thank you for your help. I close this issue.

**Comment by dborovcanin** [comment]
@akakiev You're welcome. Thanks for the feedback.
