### ISSUE TITLE
Dashflux: NGINX returns 405 method not allowed when trying to login or signup 

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#505]
**BUG REPORT**

It seems that we have some problem with Dashflux when using Docker.

1. What were you trying to achieve?
- Login with an existing user or Signup in Dashflux

2. What are the expected results?

Successful login or signup

3. What are the received results?

I receive 405 method not allowed http error from NGINX

4. What are the steps to reproduce the issue?

* open Dashfux
`http://localhost:3000/app/login` or `http://localhost:3000/app/signup`

* open dev tools, try to login or signup and check the requests sent:
`http://localhost:3000/tokens` or `http://localhost:3000/users`

* they both return 405 method not allowed from NGINX. The body of the response is:
```html
<html>
  <head>
    <title>405 Not Allowed</title>
  </head>
  <body bgcolor="white">
    <center>
      <h1>405 Not Allowed</h1>
    </center>
    <hr>
    <center>nginx/1.13.12</center>
  </body>
</html>

```
5. In what environment did you encounter the issue?
docker, Mainflux v0.7.0 with the images from dockerhub

Can someone please check this?

Best Regards,
Jovan

**Comment by drasko** [comment]
@chombium Dashflux is pretty unmaintained, and we will probably abandon it for now. We have another UI prepared, based on [ngx-admin](https://github.com/akveo/ngx-admin), but even this one looks complex. Actually - anything in Angular looks complex and hard to maintain, so we started looking inetsively at [elm](https://elm-lang.org/). Probably this will be a maintainable solution of Mainflux UI.

**Comment by chombium** [comment]
@drasko that's good to now, but we should at least also add a comment in the Dashflux's read me.
I'll see what I can do for this one if I can fix it

**Comment by drasko** [comment]
This will be fixed by ne UI in `elm`.
