### ISSUE TITLE
Readers should return the newer messages

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#506]
Readers should return newer messages instead of older ones because of the pagination (`LIMIT` condition in DB queries). Otherwise, without setting the offset it always fetch older messages and to fetch newer messages you need to know how many messages you already stored and adjust the offset, which doesn't make sense.

 It's easy as add `ORDER BY time DESC` in DB queries.

Also, from the UI perspective it will be much more easy to manipulate messages.

**Comment by drasko** [comment]
This makes sense to me - fetch starting from latest.

@anovakovic01 @dusanb94 @nmarcetic opinions?

**Comment by dborovcanin** [comment]
Yes, it makes sense to me also.

**Comment by manuio** [comment]
Fixed here: https://github.com/mainflux/mainflux/pull/510
And here: https://github.com/mainflux/mainflux/pull/514
