### ISSUE TITLE
Prevent ws client from publishing and receiving messages if the channel access is revoked

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#508]
**FEATURE REQUEST**

It would be good to forcefully disconnect ws client, or otherwise prevent it from sending/receiving once the access to the channel has been revoked.
Currently, once the ws client is connected, no additional checks are done, so it can keep sending/receiving indefinitely.

I think this is a must have feature from security perspective.

**Comment by dborovcanin** [comment]
This issue was probably resolved long ago, but let's test it before closing it.

**Comment by JeffMboya** [comment]
@dborovcanin yes, tests confirm that this was resolved.
