### ISSUE TITLE
Prevent mqtt client from receiving messages if the channel access is revoked

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#509]
It would be good to forcefully disconnect mqtt client, or otherwise prevent it from receiving messages once the access to the channel has been revoked.
Currently, after the mqtt client is connected, its access is checked on each attempt to publish a message, but not on receiving a message, so it can stay connected and receive indefinitely even if it's access to the channel has been revoked

I think this is a must have feature from security perspective.

**Comment by drasko** [comment]
Looks like NginX do not have this feature - once connection is open it remains even though certificate is revoked (@dusanb94 please confirm that this relates to NginX and not to MQTT broker),

This can be probably done via https://github.com/mainflux/mainflux/issues/415

**Comment by dborovcanin** [comment]
@1998-felix Please check this one and close it if it's resolved.

**Comment by arvindh123** [comment]
This possible when MQTT subscribes to Things disconnect event.

**Comment by arvindh123** [comment]
To implement this ticket, we need to modify the mProxy and not the Magistrala .

Client subscribes to broker with **SUBSCRIBE** packet type.

The client will receive message from broker as **PUBLISH** packet type

At present we check for Authorization  when client publish packet (packet type: publish) to server
at here https://github.com/absmach/mproxy/blob/main/pkg/session/stream.go#L61-L66
```go
if dir == Up {
	if err = authorize(ctx, pkt, h); err != nil {
		errs <- wrap(ctx, err, dir)
		return
	}
}
```

When packet goes from client to server, we do authorization check 
We don't do any authorization for server to client

In order make this ticket work, we need to do the  Authorization  when server messages (which is publish packet type) to client , i.e when server sends subscription message to client

I guess, at here https://github.com/absmach/mproxy/blob/main/pkg/session/stream.go#L61-L66 , some thing like below will work

```diff 
- if dir == Up {
+ if dir == Up || dir == Down {
	if err = authorize(ctx, pkt, h); err != nil {
		errs <- wrap(ctx, err, dir)
		return
	}
}
```

@absmach/maintainers 
Why we are having Authorization only for client to server direction and not for server to client direction ? Just trying to understand the reason behind the decision and not to make same mistakes.

**Comment by dborovcanin** [comment]
Condition `if dir == Up || dir == Down` makes no sense since those are only two options . However, we do not want to call authorization on all the packets, but only selected ones (such as CONN, which we are using at the moment).

**Comment by arvindh123** [comment]
An another way to do in Magistrala side.
But i don't know it will work full or not .
We can use session interceptor at here  `cmd/mqtt/main.go` in Magistrala https://github.com/absmach/magistrala/blob/main/cmd/mqtt/main.go#L192


```go
type Interceptor interface {
    // Intercept is called on every packet flowing through the Proxy.
    // Packets can be modified before being sent to the broker or the client.
    // If the interceptor returns a non-nil packet, the modified packet is sent.
    // The error indicates unsuccessful interception and mProxy is cancelling the packet.
    Intercept(ctx context.Context, pkt packets.ControlPacket, dir Direction) (packets.ControlPacket, error)
}
```
https://github.com/absmach/mproxy/blob/main/pkg/session/interceptor.go#L13-L19


Session Interceptor can intercept mqtt packets and they can reject them if channel is disconnected

**Comment by dborovcanin** [comment]
Let's stick to mProxy.

**Comment by arvindh123** [comment]
May be can check only PUBLISH packet for authorization `Down` i.e from Server to Client
