### ISSUE TITLE
Mainflux CLI

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#51]
A command line interface should be developed so we can test HTTP/MQTT and other protocol access. CLI program should be capable to send all commands to the Mainflux system that we are currently sending with `curl` or Postman.

**Comment by drasko** [comment]
This looks interesting: https://github.com/spf13/cobra

**Comment by drasko** [comment]
@nmarcetic would you like to take this one? Looks like a good `Go` training session :)

**Comment by drasko** [comment]
I added https://github.com/Mainflux/mainflux-cli to get us started.

**Comment by drasko** [comment]
Hmm... on the second thought I think thart REPL shell (something like `mongo` cli` would be more adequate. That reminds me that Telefonica has created one for Fiware IoT Agent: https://github.com/telefonicaid/iotagent-node-lib#-iot-library-testing - I could enter in the interactive shell and send commands to IoT Agent Server - i.e. tell where the host is, send provisioning commands, inspect resources, etc...

However - for `Go` I could not find anything better than this: https://github.com/abiosoft/ishell

**Comment by drasko** [comment]
This one should be postponed until we figure out should we use [EMQTT](http://emqtt.io/), as it has it's own CLI that we can potentially re-use.

**Comment by drasko** [comment]
@manuIO can you please take a look at this dev, tell us what is needed.

@mijicd I've used https://github.com/spf13/cobra, but now I am not 100% sure that this is the best approach. Do you think that having an interactive shell (like MongoDB or Emqtt have) would be better?

I do not know how this can be achieved, the best I have found is this: https://github.com/abiosoft/ishell

**Comment by manuio** [comment]
@drasko I did a little research. As you, I think that ishell seems to be the best option and there are not many others...

Otherwise if it's only for an internal purpose we can do a simple interface with fmt and bufio pkgs and use net/http pkg to send requests, no?

**Comment by drasko** [comment]
Python seem to have more mature libraries. This one: https://github.com/jonathanslenders/python-prompt-toolkit, or even in stdlib: https://docs.python.org/3/library/cmd.html and extension: https://github.com/python-cmd2/cmd2

Installing CLI with Go:
- You wget binary - we must compile for Linux, MacOS and Win
- You intall Go and then you build yourself (it is not common that people have Go on their machines yet)

With Python:
- You already have Python (most probably)
- `pip install`

@nmarcetic @mijicd opinions?

**Comment by drasko** [comment]
OK, we'll try to do it in Go. Let's see how it goes ;).

**Comment by drasko** [comment]
Done in https://github.com/mainflux/mainflux-cli. Closing the issue.
