### ISSUE TITLE
Change service default ports

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#512]
**FEATURE REQUEST**

All adapters default ports are 8180 for http and 8181 for gRPC.
If someone tries to run couple of those adapters locally on his machine, with default settings, there is a port clash. It would be nice to have default ports different, so it would work without any need to set those ports.
Another thing that would be nice is to have ports split by protocol. Something like the example below:

7000 - users grpc
7001 - things grpc

8000 - ws adapter

9000 - users http
9001 - things http
9002 - http adapter

Please note that this change would affect docker compose configuration as well as run.sh script

**Comment by chombium** [comment]
We should also document this change and announce it loud as we would probably brake something on the users side

**Comment by dborovcanin** [comment]
The proposed idea is good, but let's use default protocol ports for adapters (8000, 1883, 5683...).
