### ISSUE TITLE
Add WS support to SDK

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#517]
Add WS messaging support to SDK.

**Comment by nmarcetic** [comment]
@drasko I am not sure this is something that would be handy, together with #515 and #516 
I agree that SDK should support messaging and I would pick MQTT as mostly used M2M communication protocol. We can wrap paho library, support both MQTT and MQTTS and just expose you pub/sub methods.  Even this is redundant IMHO, but OK let's support messaging with SDK.

**Comment by drasko** [comment]
@nmarcetic this can be post `1.0`. Really low-priority, not needed for `1.0` IMHO. Acutally, nothing more than we have now regarding SDK messaging is needed.

**Comment by drasko** [comment]
Let's remove this redundancy. Closing the issue.
