### ISSUE TITLE
Discussion: Refactor lora-adapter to utilize redis as a cache and postgres as persistence

### ISSUE THREAD

**Issue by nwest1** [absmach/magistrala#518]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

I would like to get everyone's thoughts on `lora-adapter` following the `things` pattern of utilizing redis as a cache and postgres as persistence layer instead of the current strategy of using redis as the only persistence layer.

I like the simplicity of having only one datastore, but the environment that we deploy in currently doesn't support redis persistence. There are plans to enable this, but timelines are unknown.  

Which patterns make the most sense?
- postgres as persistence + redis as cache
- postgres as persistence + redis cache, redis as persistence
- redis as persistence, no postgres (not sure this makes sense due to relational modeling) 

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
discussion

I don't think any of these - more of what is preferred?

**Comment by drasko** [comment]
This is not on our current timeline.

Redis as a cache for access (keeping thing tokens) should be used with care. First - because of security reasons. Second - only one microservice (probably `Things`) should write into it, if any other microservice should use it - it should be only for reading.
