### ISSUE TITLE
New Feature Request- Need an API to retrieve old Password 

### ISSUE THREAD

**Issue by kanchandebnath** [absmach/magistrala#532]
Request an API  Interface  so that the User can retrieve old password when forgotten

**Comment by chombium** [comment]
Fo security reasons we can not send the current or an old password to the user.
We can  either:
1.  do the normal "forgotten password flow" with sending a n email with a link to a reset password page, let the user change the password on some webpage and send a password update confirmation email or
2. create a new api enpoint for password reseting and send an email with password reset link with one time token for resetting the password. The payload would be the new password.
If we go with the first suggestion, we'll have to wait for the new UI to be finished.

@mainflux/contributors what do you think about this?

**Comment by kanchandebnath** [comment]
For Now if you can  provide  the first option ( 1) that  would be  great

**Comment by nmarcetic** [comment]
@kanchandebnath There is a work in progress #873

**Comment by manuio** [comment]
Fixed in #873
