### ISSUE TITLE
Consider CI platform change

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#543]

**Comment by drasko** [comment]
Semaphore 2, Travis and/or CircleCI allow .yaml file to reside in the repo and it is readable documentation of what happens in CI process.

Semaphore open-source plan offer twice the resource than competitors. However, Semaphore 2 version is still in early Beta, so CLI is needed to create and configure project still (UI is in dev).

**Comment by nmarcetic** [comment]
Github recently introduced [Githu Actions](https://github.com/features/actions) 
I enable it on a repository, we need to try it.

**Comment by nwneisen** [comment]
@nmarcetic I'm curious to try out the new Github Actions.  I've got a few other issues I think I should finish up first but afterwards I'd be glad to make a branch to test them out.

**Comment by drasko** [comment]
I am not sure that we want to use this for CI.

```Included minutes
Free
2,000
minutes per month

Additional hosted runner minutes
Linux
2 cores, 7GB
$0.008
per minute
```

Our CI can be quite long and time consuming - can we guarantee the we'll not spend all free minutes?

Semaphore is free for open-source projects and it's quite powerful (we can compare builder machines to what GitHub will offer with Free plan, but when I was comparing to Travis and CircleCI it was 2 times more powerful)

**Comment by rodneyosodo** [comment]
> I am not sure that we want to use this for CI.
> 
> ```
> Free
> 2,000
> minutes per month
> 
> Additional hosted runner minutes
> Linux
> 2 cores, 7GB
> $0.008
> per minute
> ```
> 
> Our CI can be quite long and time consuming - can we guarantee the we'll not spend all free minutes?
> 
> Semaphore is free for open-source projects and it's quite powerful (we can compare builder machines to what GitHub will offer with Free plan, but when I was comparing to Travis and CircleCI it was 2 times more powerful)

GitHub Actions is free for public repositories. They charge for private repositories - https://github.com/features/actions#pricing-details

**Comment by dborovcanin** [comment]
GitHub Actions are chosen, this issue is not relevant anymore.
