### ISSUE TITLE
Change metadata format from JSON string to JSON object

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#549]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
There is no existing issue for this.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Currently metadata field must be JSON, but it is returned in string format. This should be changed so that metadata field is returned as plain JSON object.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is should-have feature in my opinion.

**Comment by chombium** [comment]
@anovakovic01  thanks for the clarification
