### ISSUE TITLE
Add metadata fields to Bootstrap Channels

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#551]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
There is no issue addressing this request.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Copying metadata field from Mainflux channel to Bootstrap service is desirable. This field represents JSON formatted data that can be used from the Thing to separate one channel from another since UUIDs don't provide enough information (from UUID it's not possible to see what's the purpose of the channel).

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a should-have feature.

**Comment by anovakovic01** [comment]
I think that you can use event sourcing in order to copy channel data.

**Comment by dborovcanin** [comment]
I'll create a separate issue for using event sourcing to keep Bootstrap service in sync with Mainflux.
