### ISSUE TITLE
Normalizer is not passing messages that cannot be normalized

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#560]
**BUG REPORT**

1. What were you trying to achieve?
Send non-SenML messages using mainflux, and receive them on `out.unknown` subject.

2. What are the expected results?
To receive non-SenML messages on `out.unknown` channel.

3. What are the received results?
Messages aren't received on `out.unknown` channel.

4. What are the steps to reproduce the issue?
Just try to send non-SenML message using MF and receive it on NATS `out.unknown` subject.

5. In what environment did you encounter the issue?
I was running docker composition.

**Comment by nmarcetic** [comment]
Closed with #573
