### ISSUE TITLE
Add basic UI in elm

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#571]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
A basic UI should be added for Mainflux system that has the functionalities equivalent of CLI today. UI should be writtent in [elm](https://elm-lang.org/) language to be aligned with Mainflux ideas of simplicity, lean implementaion and correct execution provided by typed language.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by nmarcetic** [comment]
Closed with #632
