### ISSUE TITLE
creating new things

### ISSUE THREAD

**Issue by caztial** [absmach/magistrala#572]
When you add a new thing via post, include the thing id, key, name and type in the response body, otherwise need to get all the things and find the correct one from the list.

**Comment by drasko** [comment]
This does not make sense. If your app is adding the thing, it knows what is the `name` and `type`. ID is auto-generated and returned in the `Location` header, and then you can query by `thingID` and get what you need.

**Comment by caztial** [comment]
Thank you to pointing out ID is returned in Location response header.  normally you give the created resource details in a successful POST response
