### ISSUE TITLE
CoAP and MQTT Normalizer issue

### ISSUE THREAD

**Issue by caztial** [absmach/magistrala#589]
I have tried sending message to the coap and mqtt after inspecting the adapter logs and normalizer docker logs I got the following 

**coap adapter log**
`{"level":"info","message":"Method publish to channel 30b1dee5-25d4-4dee-9ea6-0a5cbab541fd took 14.229µs to complete without errors.","ts":"2019-02-12T11:11:24.031558782Z"}`

**normalizer log** 
`{"level":"warn","message":"Method normalize took 8.41µs to complete with error: invalid character '\\'' looking for beginning of object key string.","ts":"2019-02-12T11:11:24.033307959Z"}`

and the payload I sent was
`[{"bn":"some-base-name:","bt":1549968701, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]`

**above payload get successfully normalized in http adapter**. 
any idea what I'm doing wrong here

**Comment by caztial** [comment]
Suspect this is due to windows and Linux line endings

**Comment by dborovcanin** [comment]
@caztial Can you give us more info about the environment in which you encountered this error?

**Comment by drasko** [comment]
@dusanb94 it might be some CoAP CLI from Windows... @caztial maybe you should try Copper plugin: https://github.com/mkovatsc/Copper4Cr

**Comment by drasko** [comment]
Closing this one, reopen if needed.

**Comment by caztial** [comment]
> @dusanb94 it might be some CoAP CLI from Windows... @caztial maybe you should try Copper plugin: https://github.com/mkovatsc/Copper4Cr

Yes it was due to line endings. but guy you might need to fix this later

**Comment by drasko** [comment]
Which fix? This is related to a test tool you are using, not Mainflux.
