### ISSUE TITLE
Add subtopic to RawMessage

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#596]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
NA
2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Add subtopic to [RawMessage](https://github.com/mainflux/mainflux/blob/master/message.proto#L12) in order to propagate channel subtopics described in #429. It will also affect #565 

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must have

**Comment by drasko** [comment]
You can also replace `Channel` field by `ChannelID` - which will impact probably all services connected to NATS at this time.

**Comment by nmarcetic** [comment]
Duplicated #642

**Comment by drasko** [comment]
@nmarcetic this is an issue, not a PR. Please do not close it until PR is merged ;).

**Comment by nmarcetic** [comment]
Closed by #659
