### ISSUE TITLE
Not able to connect things with channels

### ISSUE THREAD

**Issue by exocode** [absmach/magistrala#626]
**BUG REPORT**

1. What were you trying to achieve?
Assign Things to Channels

2. What are the expected results?
Assignments should be visible

3. What are the received results?
None

4. What are the steps to reproduce the issue?
- clone master repo
- cd into it
- run `docker-compose -f docker/docker-compose.yml -f docker/addons/influxdb-reader/docker-compose.yml -f docker/addons/influxdb-writer/docker-compose.yml up -d`
- run `mainflux-cli -m http://192.168.99.100 provision test`
- Login into Dashflux with received credentials
- Try to assign Things to Channels

5. In what environment did you encounter the issue?
MacOS 10.13.6 (17G4015)
Docker version 18.09.2, build 6247962
Mainflux "0.7.0"

6. Additional information you deem important:
Screen record of the issue:
https://drive.google.com/file/d/1XJ_ISWhASB4xJrVOLL3DHQClCPn0pkDO/view

**Comment by drasko** [comment]
Dashflux is not functional. A PR for new UI has been sent today to a master

**Comment by exocode** [comment]
Is the app itself "production ready"? Or still in any kind of "beta stadium"?
