### ISSUE TITLE
Improve Elm UX

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#634]
- Don't display modals after to add an entity.
- Add a list of connected Channels in Things modals.
- In Connections page pre-check corresponding Things and channels if they're already connected.

**Comment by drasko** [comment]
@manuio I think we should break this list into smaller issues, one per feature. Also, @blokovi had a list of demanded features, he should add this list here first, and then we should just break them in different issues - so that PRs are short and sweet.

**Comment by manuio** [comment]
@drasko I moved style points to a new issue. For the rest I would not split this issue.

**Comment by blokovi** [comment]
Here is the list of demanded issues, that Manu didn't point out:

* Highlight selected menu option
* Number of connected channels in thing’s list or details
* Social networks links in footer
* Add favicon

**Comment by drasko** [comment]
Also:
- No need for pagination when you have only one page

**Comment by nmarcetic** [comment]
@manuio @drasko @darkodraskovic @blokovi Plese open new issue for bigger ones and move smaller ones to #635 or create one issue for multiple smaller ones (don't put just `Add favicon` in one). 
Please don't forget to add `UI` label, its very important to separate UI stuff from the core logic and avoid confusion. Closing this one.
