### ISSUE TITLE
Improve Elm UI  style

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#635]
Style must be improved. Starting by:
- Add Mainflux logo on the menu.
- Improve buttons. Use same style, padding, margin, etc etc Use same position on the page, for example top-right.
- Improve the menu: Menu should be a nav-bar and not a button group. Try to add boostrap menu here.
- Fix pagination. Numbers should be centered on the bottom of the tables. An external package can maybe help here.

**Comment by blokovi** [comment]
This issue is splitted in three new issues:
#661 #662 #664
