### ISSUE TITLE
error 415 when posting to /tokens with content-type appended charset=utf-8

### ISSUE THREAD

**Issue by tony-ward** [absmach/magistrala#639]
Sending the following POST request will generate a 415 Unsupported Media Type error and fail

**Steps:**
POST request:
POST http://URL/tokens
accept: application/json
content-type: application/json;charset=utf-8

{"email":"tony@lucidtron.com","password":"123"}

**Expected results:**
HTTP/1.1 201 Created

**Received results:**
HTTP/1.1 415 Unsupported Media Type

**workaround**
do not append charset=utf-8 to content-type:

POST request:
POST http://URL/tokens
accept: application/json
content-type: application/json

{"email":"tony@lucidtron.com","password":"123"}

**Comment by tony-ward** [comment]
@chombium suggests:
@drasko I guess we have to adjust the HTTP users api https://github.com/mainflux/mainflux/blob/effade00aa34b62e54328063407201e0164a234f/users/api/http/transport.go#L64 and split on semicolon before checking the content type. There is an explicit check in our code

**Comment by tony-ward** [comment]
I believe this problem may be duplicated in the following code:
things/api/http/transport.go line 151,164
bootstrap/api/transport.go line 108,
users/api/http/transport.go line 64

I want to use something like this, can somebody please comment?
```
	s := r.Header.Get("Content-Type")
	ss := strings.Split(s, ";")
	for i := 0 ; i <= len(ss) ; i++ {
		if i == len(ss) {
			return nil, errUnsupportedContentType
		}
		if strings.Contains(ss[i], contentType) {
			break;
		}
	}
```

**Comment by anovakovic01** [comment]
@tony-ward you can just use `strings.Contains` function instead of current `==`.

**Comment by chombium** [comment]
The other question is how are we processing and storing the data if the encoding is not UTF-8. Currently we are using UTF-8 as default encoding for everything (services and db), but we should also at least test what would happen if the data comes in another encoding and if we should possibly convert (something like [this](https://stackoverflow.com/a/32518698)) it to UTF-8 in order not to store "garbage" in the system.

@mainflux/contributors what do you think about this? Has someone experience with such case?

**Comment by tony-ward** [comment]
> @tony-ward you can just use `strings.Contains` function instead of current `==`.

Thanks, updated.  I still need some help to commit this...

**Comment by drasko** [comment]
@tony-ward just one question - you told us that React lib enforces appending `utf-8` to content-type. Also, that separator is `;`. 

Can you please point us to that lib, it is still hard to understand why this feature can not be switched-off, and is this an isolated feature or a bug in this particular library or things like this appear in many libraries.

**Comment by tony-ward** [comment]
it looks to be quite isolated, I didn't find wide ranging issues, it seems react native 3rd party libraries when used with fetch.  Several of the guys have had a look at this and it really does appear there is no way to turn it off...

https://github.com/facebook/react-native/issues/14445
https://github.com/facebook/react-native/issues/8237
