### ISSUE TITLE
Clean up the Contribution guide

### ISSUE THREAD

**Issue by alwindoss** [absmach/magistrala#640]
**BUG REPORT**

Contribution guide has a few grammar mistakes and certain sentences could be rephrased to make it sound better.

**Comment by alwindoss** [comment]
Can we close this issue based on the PR: https://github.com/mainflux/mainflux/pull/641

**Comment by anovakovic01** [comment]
@alwindoss FYI, you can close issues automatically by writing `Closes #<issue_no>` in PR description.

**Comment by anovakovic01** [comment]
Closed by #641.
