### ISSUE TITLE
Add configuration of UI NginX serving port via ENV var

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#663]
NginX can read ENV variables via `nginx.conf`. Please use ENV variable to define serving port rather than hardcoding it here: https://github.com/mainflux/mainflux/blob/master/ui/docker/nginx.conf#L2

If necessary use OpenResty.

Examples:
- https://stackoverflow.com/questions/21866477/nginx-use-environment-variables
- https://serverfault.com/questions/577370/how-can-i-use-environment-variables-in-nginx-conf
- https://blog.doismellburning.co.uk/environment-variables-in-nginx-config/

**Comment by kanozec** [comment]
I am into this issue.
I found this [article](https://medium.com/code-build/docker-environment-variables-and-nginx-93d7173f19ec) and [this](https://hackerbox.io/articles/dockerised-nginx-env-vars/)

According to the article, I should add this 

**load_module "modules/ngx_http_perl_module.so";
env NGINX_PORT;**

and

**perl_set $port 'sub { return $ENV{"NGINX_PORT"}; }';**

to the nginx.conf file.

Where should I set up  NGINX_PORT value ?
In the docker/docker-compse.yaml [this line](https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml#L142) ???

**Comment by chombium** [comment]
Hi @kanozec,

I don't see any work going on by @darkodraskovic in his fork, so I guess you can start working on this. Please check our contribution guide.

@darkodraskovic, @drasko is that ok with you guys?

**Comment by darkodraskovic** [comment]
@chombium Actually, I was only setting up the elm GUI internal baseURL handling so that GUI makes requests by default via `localhost:80` and not via `localhost:8000`. Eventually, it's independent thing from the UI NginX serving port. I'm not planning to tackle the latter issue.

**Comment by drasko** [comment]
@kanozec first - I do not see need for Perl module - looks to me that NginX can read ENV vars without Perl.

Second - yes, ENV var must be passed to `ui` container, but you should change the `nginx.conf` of the NginX running in the `ui` container to take this ENV var in the account here: https://github.com/mainflux/mainflux/blob/master/ui/docker/nginx.conf#L2

**Comment by kanozec** [comment]
@drasko 
I found the nginx usage sample in 
https://docs.docker.com/samples/library/nginx/#using-environment-variables-in-nginx-configuration

It uses the "envsubst" to pass the env value.  Is that what you are talking about ??

**Comment by nmarcetic** [comment]
Closed by #770
