### ISSUE TITLE
Improve style

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#664]
Improve style of UI, including but limited to:

- Add logo
- Add footer with social media links
- Use same position for buttons on the page, for example top-right

**Comment by manuio** [comment]
* Login page should be centered and with smaller name and password inputs.
* Profile menu (top-right) have an unnecessary margin on its right.

**Comment by manuio** [comment]
* Profile menu (top-right) have an unnecessary margin on his right.

**Comment by manuio** [comment]
Moving this one to new `MainfluxLabs/ui-elm` repo: https://github.com/MainfluxLabs/ui-elm/issues/2
