### ISSUE TITLE
Create pkg/utils for shared code

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#666]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
In order to share code over the project, we need to introduce pkg/utils module and extract functional stuff like parsing/checking content types, Regex validators for subtopics etc... which are used strictly for operational stuff. But be careful with domain/business logic and bounded context, we don't want to create a coupling & dependency chaos, keep things self-contained but without code duplication.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Nice to have.

**Comment by rugwirobaker** [comment]
I thought utils is an anti-pattern in Go??

**Comment by nmarcetic** [comment]
@rugwirobaker Not really, if you package your code well :) Not making circular dependencies and ant-patterns. More like [/internal philosophy](https://github.com/golang-standards/project-layout#internal)

**Comment by nmarcetic** [comment]
Related to #793

**Comment by drasko** [comment]
@nmarcetic in general `utils` is anti-pattern in Go, it avoids calling packages like `utils` because it does not describe much and is too generic. Suggested names for the packages are very specific in Go.

`/pkg` should hold packages with package names (like `things`, `users`, and so on).

**Comment by drasko** [comment]
As described in #844:
Based on [Go project-layout](https://github.com/golang-standards/project-layout), we should reorganize internal file and directory organization.

Move Mainflux services in `/internal`. Also, move Swagger docs in `/api`.

We need to see what packages whold be imported by other apps, and move these in `/pkg`

**Comment by nmarcetic** [comment]
Same as I said to @rugwirobaker here https://github.com/mainflux/mainflux/issues/666#issuecomment-513767656 The idea was to use  `/internal` 
`utils` is more like abstraction, the idea and the general naming :)

**Comment by manuio** [comment]
@nmarcetic Can we close this one? Looks like it was resolved here: https://github.com/mainflux/mainflux/pull/1191

**Comment by nmarcetic** [comment]
@manuio Yes we can, closing.
