### ISSUE TITLE
Add validation and display errors for unsuccessful actions

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#667]
- What are the steps to reproduce the issue?
- When create or edit thing/channel with metadata in non-json format action is not successful (return error is `400 Bad request`). 

Find the way to inform the user of returning error.
Also, validate inputs in such cases so request is not sent if input is in inappropriate format.

**Comment by chombium** [comment]
I haven't used Elm till now, but these things bug me as well. There is no validation for any action and not even hints what went wrong, only http status codes are returned. I was digging around to see how these things can be implemented and found the following:

* Validation: Really nice [blog post](https://medium.com/@l.mugnaini/forms-in-elm-validation-tutorial-and-examples-2339830055da) and the accompanying github [repo](https://github.com/lucamug/elm-form-examples)
* elm-bootstrap [alerts](http://elm-bootstrap.info/alert)
* elm-bootsrap [form](http://elm-bootstrap.info/form) help text

If no one objects, I will give it a try

**Comment by abay94** [comment]
Hello!
I need a help related to bootstrap service. It is the same as @blokovi  said There is bad request coming from the service, when i send post request to localhost:8200/things/configs, it responses 400 bad request. Which is malformed json but the body of request is the same as have to be, like
{
"external_id" : "88:e9:fe:52:98:6e",
"external_key":"0a:e9:fe:52:98:6e" ,
"name":"some",
"channels":["d7804d0b-af47-430a-a453-4c52d53ca1ba"],
"thing_id":"194f212e-81b6-4f66-a187-c2ed372c5923",
"content": "config"
}

**Comment by manuio** [comment]
Moving this one to new `MainfluxLabs/ui-elm` repo: https://github.com/MainfluxLabs/ui-elm/issues/3
