### ISSUE TITLE
Selecting page in pagination create bad request

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#674]
**BUG REPORT**

1. What were you trying to achieve?

Use pagination in list of channels or things

2. What are the expected results?

Getting diffrent pages of list

3. What are the received results?

Getting right pages of list, but UI also create some `GET` requests to `/things/` or `/channels/` with `400 Bad request` response. Bad requests are not visible in UI except in browser developer console.

4. What are the steps to reproduce the issue?

- Have list of things
- Open console in browser developer tools
- Go to diffrent pages 
- Look at error in console or see logs on server with `docker logs mainflux-nginx`

5. In what environment did you encounter the issue?

Local enviroment, Mainflux in docker, env.url = " url = "http://localhost:80/"

6. Additional information you deem important:

Same issue is on every page where is pagination

**Comment by blokovi** [comment]
This bug is not always reproducible. If you don't see it, try to connect  things to channels and then try again above steps.

**Comment by manuio** [comment]
Moving this one to new `MainfluxLabs/ui-elm` repo: https://github.com/MainfluxLabs/ui-elm/issues/4
