### ISSUE TITLE
Listing unconnected channels on message page 

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#675]
**BUG REPORT**

1. What were you trying to achieve?
Send message to connected channel

2. What are the expected results?
List only connected channels for selected thing on message page 

3. What are the received results?
If more then 10 channels are connected to thing, after using pagination for connected channels, all  channels are displayed (instead only connected to selected thing)

4. What are the steps to reproduce the issue?

- Create 12 or more channels
- On connect page, connect  11  channels to one thing
- On message page select that thing
- On right side (channels) after using pagination you will see all the channels, including that one you haven't connected to selected thing

5. In what environment did you encounter the issue?
Local enviroment, Mainflux in docker, `env.url = " url = "http://localhost:80/"`

6. Additional information you deem important:
Channel pagination on message page send request to server for getting all channels instead only connected one

**Comment by manuio** [comment]
Moving this one to new `MainfluxLabs/ui-elm` repo: https://github.com/MainfluxLabs/ui-elm/issues/5
