### ISSUE TITLE
After deleting thing, offset not updated on Connection and Messages page

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#680]
**BUG REPORT**

1. What were you trying to achieve?
Lists all Things on connection page

2. What are the expected results?
Lists all Things on connection page

3. What are the received results?
No Things listed

4. What are the steps to reproduce the issue?
- Create 11 Things
- On Connection page go to page 2 on Things side
- Go to Things page and delete one Thing
- Back on Connection page you don't see any Thing (because it's hanging on page 2 which no longer exists)

5. In what environment did you encounter the issue?
Local enviroment, Mainflux in docker, env.url = " url = "http://localhost:80/"

6. Additional information you deem important:
Same applies to channels on connection page

**Comment by manuio** [comment]
Moving this one to new `MainfluxLabs/ui-elm` repo: https://github.com/MainfluxLabs/ui-elm/issues/6
