### ISSUE TITLE
Use adapters/services graceful shutdown to close all underlying servers/clients used by adapters/services

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#701]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently, all services/adapters simply exit on SIGINT. I think that the servers(http/grpc) and all database clients should be allowed to finish their work and close connections before main exits.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

I think this is a must have because currently services can be interrupted in the middle of an operation thus not leaving the system in a clean state.

**Comment by drasko** [comment]
I did not check, but this should be well logged as well - if not done already.

**Comment by WashingtonKK** [comment]
Graceful shutdown has been implemented on all services/adapters to allow all operations to be stopped, ongoing operations completed before exiting and thus leave the system in a clean state.

**Comment by dborovcanin** [comment]
Resolved by #1548.
