### ISSUE TITLE
Remove gRPC and HTTP server interdependency in services

### ISSUE THREAD

**Issue by ghost** [absmach/magistrala#702]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently, all services have gRPC and HTTP servers started by main.go. If any of those 2 servers sends an err to errs channel, it will cause the whole service to terminate.
Maybe it would be better to rearrange the code, so for example the gRPC server error doesn't necessarily cause the whole service to terminate, thus leaving the HTTP server operational.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

I think this is a nice to have feature.

**Comment by drasko** [comment]
@nmarcetic @anovakovic01 @dusanb94 what is your opinion on this? Do we need just one server running, or would we prefer restarting whole service (to reinitialize the state)?

**Comment by nmarcetic** [comment]
@drasko No gRPC no healthy service (we use gRPC for internal logic, mostly for AutX and AutZ), no HTTP API no healthy service. IMHO does not make sense to keep service running with only one  healthy server.

**Comment by drasko** [comment]
@nmarcetic I agree. I always liked Erlang's philosophy "Let it crash". Rather restart the whole serive into a known state that try to recover from various errors. This especially comes actual today when k8s plays at some extent the role of Erlang's supervisor processes...

I will colose this issue, please re-open if needed.
