### ISSUE TITLE
Pagination is not updated on menu click

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#704]
**BUG REPORT**

Pagination is not updated on clicking menu item

1. What are the steps to reproduce the issue?
- Go to channels
- Add more than 10 channels through CLI (or some other way that is no UI)
- New page is not seen when you click on menu channels. Pagination is updated only after pagination click

2. In what environment did you encounter the issue?
Local enviroment, Mainflux in docker, env.url = " url = "http://localhost:80/"

3. Additional information you deem important:
same for things

**Comment by manuio** [comment]
Moving this one to new `MainfluxLabs/ui-elm` repo: https://github.com/MainfluxLabs/ui-elm/issues/7
