### ISSUE TITLE
Mark a Channel not to be normalized

### ISSUE THREAD

**Issue by bbokun** [absmach/magistrala#709]
1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
In case I need a channel where the sent data carries information for let's say an UI refresh, the structure of the data does not have necessarily to be in SenML format. But the normalizer is always triggered and results with an "cannot unmarshal object into Go value of type []senml.SenMLRecord" error.  
A channel which is marked as not to be normalized does not even have to be tried to be normalized.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Nice-to-have.
I did not dig into the code too much, but this could save a little bit of processing.

Greetings,
Boris Bokun
strictit d.o.o.
Beograd

**Comment by drasko** [comment]
@bbokun if you are not using SenML, then there is no need to be using Normalizer.

Maybe you are using both SenML and custom JSON, and then you need Normalizer, but only for smome channels (and not all)? In that case, this issue makes sense.

Normalizer should try to normalize only `application-senml-json` content-type.

**Comment by bbokun** [comment]
@drasko 
Right. I use dedicated channels for sending custom JSON for refreshing some graphical interface. These messages do not need to be normalized, as they will result with an error when being "normalized".
On the other side I use other channels which contain SenML.

Does Your comment mean, that in future I will have to set the content type of the message to "application-senml-json" for those messages which have to be normalized, and another content type (e.g. "application-json") for those messages which have to be ignored by the normalizer?

If I understood You well...this sounds as a good solution.

Thanks
Boris Bokun
strictit doo
Beograd

**Comment by nmarcetic** [comment]
Closed by #737
