### ISSUE TITLE
Send multiple messages in a row

### ISSUE THREAD

**Issue by blokovi** [absmach/magistrala#714]
**BUG REPORT**

1. What were you trying to achieve?
Send two messages in a row

2. What are the expected results?
Sent both messages

3. What are the received results?
Second message is not sent

4. What are the steps to reproduce the issue?
- go to messages in menu
- select thing that will send message, select channel where it will send message
- type message
- click send
- click send

Second message is not sent until you select thing and channel again (even if it's already selected)

5. In what environment did you encounter the issue?
Mainflux in docker

**Comment by manuio** [comment]
Moving this one to new `MainfluxLabs/ui-elm` repo: https://github.com/MainfluxLabs/ui-elm/issues/8
