### ISSUE TITLE
add filter to api channels

### ISSUE THREAD

**Issue by gesaleh** [absmach/magistrala#73]
Add a time frame to channels api 
To request `http://<mainfluxServer>:7070/channels/<channelId>?filter:starttime=xxxxx,endtime=yyyyy`
This should return a json with from channel id with entries only in the time frame given in the api

**Comment by drasko** [comment]
Sure, I am looking at this one right away!

**Comment by drasko** [comment]
Should be OK now. More info here: https://groups.google.com/forum/#!topic/mainflux/7aywImi0udw

I will close the issue, please re-open it if something is missing.
