### ISSUE TITLE
Thing digital twin concept 

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#730]
Considering digital twin concept, thinking about benefits and metadata search capabilities, world state vs known state, device status, queued messages/commands,  etc..

References:
[The Role Of Device Twins In Industrial IoT Solutions](https://www.forbes.com/sites/janakirammsv/2017/10/30/the-role-of-device-twins-in-designing-industrial-iot-solutions/#2b5d292c20ac)
[Understand Azure IoT Hub device twins](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins)

**Comment by nmarcetic** [comment]
WIP #855

**Comment by drasko** [comment]
For the reference:
- https://www.youtube.com/watch?v=NpC4ROGqwKc
- https://blog.bosch-si.com/developer/how-digital-twins-boost-development-in-the-iot/

**Comment by nmarcetic** [comment]
Its WIP #855
