### ISSUE TITLE
Database design - add ID to the User entity and use it in Owner fields of other entities

### ISSUE THREAD

**Issue by saeid-ir** [absmach/magistrala#739]
Looking at Users and Things services i discovered that database design can be improved.
Mainflux uses `Emails` as primary key that according to database design patterns and methods is not a good practice due to slower performance ( because of string comparison),scalability and ....
One other thing is that repeating email address as `Channels` and `Things` owner is not size efficient and of course using it as primary key together with channel and things IDs just cause system slower on finding matches in queries.
I looking forward to make a Pull request for design a more performant database for storing persistent datas.
please also Take a look at [Cockroachdb](https://www.cockroachlabs.com/) as a better alternative to Postgresql than can do more with the same query language.

**Comment by chombium** [comment]
Having email as primary key is not that bad. Of course, we should add indexes to the primary keys

**Comment by drasko** [comment]
@anovakovic01 @nmarcetic @dusanb94 @srados please comment on this.

**Comment by nmarcetic** [comment]
We spoke about this few times before, missing `ID` on user structure as we have with any other entity in the system. So YES huge :+1: from my side @saeidakbari

**Comment by anovakovic01** [comment]
I agree with @chombium. I think that email is good enough unless we plan to add support for an email field update. In that case, we must add `ID` as a primary key. @chombium made a good point regarding DB indexing, but AFAIK index is already added for primary keys and unique values. IMHO, there is no need to optimize `users` service too much (I don't expect it to be under heavy loads).

**Comment by nmarcetic** [comment]
@anovakovic01 I agree, it can stay like this,  but is it not better at least for sake of consistency to add `ID` as we did it for any other entity?

**Comment by drasko** [comment]
@anovakovic01 my opinion is also that `ID` can be useful here.

However - @saeidakbari and @nmarcetic ID we use is also a string - UUID. If I understood well @saeidakbari this will also suffer from a slower string comparison performance?

**Comment by saeid-ir** [comment]
@drasko Applications cannot use constructs like ```SEQUENCE``` or ```AUTO_INCREMENT``` and also expect horizontal scalability -- this is a general limitation of any distributed database.
In some databases like [Cockroachdb](https://www.cockroachlabs.com/) there is a type called ```SERIAL``` which is generates increasing but not necessarily contiguous values in numbers,so it is more efficient than string.
In Postgres however because of it is not a horizontally distributed system things get different and we cannot use ```SERIAL``` as an always unique identifier.instead many ones uses ```UUID``` that is a a built in PostgreSQL type.It's basically a 128 bit integer and should perform as an index just as well as any other large integer.
So if we want to compare emails which is string as identifier against ```UUID``` in Postgres which is integer, UUID would definitely wins.

**Comment by drasko** [comment]
@saeidakbari I was talking about [UUID v4 which we use](https://github.com/satori/go.uuid#example) (which is a string), not Prostgres UUD.

**Comment by saeid-ir** [comment]
@drasko It is not about the way you generating ```UUID```,it is about the way you store this.
When you create a column in Postgres with the data type of ```UUID```, Postgres automatically store it as a 128-bit Integer.

**Comment by drasko** [comment]
@saeidakbari we do not want to dependent on a particular DB. This is why we use UUID v4 - which is a string.

**Comment by drasko** [comment]
@nmarcetic are we still for [adding ID](https://github.com/mainflux/mainflux/issues/739#issuecomment-531748354) to the `User{}` struct?

If yes, we can add this to `0.12.0`

**Comment by manuio** [comment]
Add ID to the user entity resolved here: https://github.com/mainflux/mainflux/pull/1152

We will modify the owner and do the migration of DBs in a separate PR.

**Comment by manuio** [comment]
Duplicated issue: https://github.com/mainflux/mainflux/issues/1273

closing this one

**Comment by dborovcanin** [comment]
This issue is obsolete. Users have IDs and it's been like that for a long time.
