### ISSUE TITLE
LoRa Server <> Mainflux Adapter

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#74]
Proposition is to connect LoRa Server: https://github.com/brocaar/loraserver with Mainflux server.

When we observe this picture: https://camo.githubusercontent.com/1b77c3663a5f695f488d2e30d87a7e42dde00109/68747470733a2f2f7777772e676c696666792e636f6d2f676f2f7075626c6973682f696d6167652f31313031303333392f4c2e706e67 Mainflux will come in the place here where is an "application" (the little cloud on the bottom right).

But for `lora-app-server` to talk to Mainflux we need to insert a small adapter (server) between them that will translate from one API to another.

I think best option will be to use an additional MQTT broker and just process MQTT pubs, redirecting them to appropriate endpoints.

**Comment by drasko** [comment]
Implemented at https://github.com/mainflux/mainflux-lora-adapter

**Comment by dcolley** [comment]
What happened to https://github.com/mainflux/mainflux-lora-adapter? is there any documentation on the new implementation?

**Comment by manuio** [comment]
@dcolley lora-adapter is ihere: https://github.com/mainflux/mainflux/tree/master/lora
