### ISSUE TITLE
Mainflux-mqtt exiting after sending an HTTP POST request.

### ISSUE THREAD

**Issue by hashin** [absmach/magistrala#75]
When I tried this curl request as given in the tutorial, I got the output as follow:

Curl request:

`curl -s -S -i -X POST -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:7070/channels/fca48fe1-672a-424c-b219-a4fa6d62cc07/msg -d '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3987}]'`

Output:

```
mainflux-core    | [negroni] Started POST /channels/fca48fe1-672a-424c-b219-a4fa6d62cc07/msg
mainflux-core    | Msg written
mainflux-core    | [negroni] Completed 202 Accepted in 1.057578ms
mainflux-mqtt    | Received a message: {"topic":"mainflux/channels/fca48fe1-672a-424c-b219-a4fa6d62cc07","publisher":"","payload":"W3siYm4iOiJzb21lLWJhc2UtbmFtZToiLCJidCI6MS4yNzYwMjAwNzYwMDFlKzA5LCAiYnUiOiJBIiwiYnZlciI6NSwgIm4iOiJ2b2x0YWdlIiwidSI6IlYiLCJ2IjoxMjAuMX0sIHsibiI6ImN1cnJlbnQiLCJ0IjotNSwidiI6MS4yfSwgeyJuIjoiY3VycmVudCIsInQiOi00LCJ2IjoxLjN9XQ=="}
mainflux-mqtt    | /opt/mainflux-mqtt/mainflux-mqtt.js:86
mainflux-mqtt    | 		payload: Buffer.from(atob(m.payload)),
mainflux-mqtt    | 		                ^
mainflux-mqtt    | 
mainflux-mqtt    | TypeError: this is not a typed array.
mainflux-mqtt    |     at Function.from (native)
mainflux-mqtt    |     at Object.callback (/opt/mainflux-mqtt/mainflux-mqtt.js:86:19)
mainflux-mqtt    |     at Client.processMsg (/opt/mainflux-mqtt/node_modules/nats/lib/nats.js:892:11)
mainflux-mqtt    |     at Client.processInbound (/opt/mainflux-mqtt/node_modules/nats/lib/nats.js:824:14)
mainflux-mqtt    |     at Socket.<anonymous> (/opt/mainflux-mqtt/node_modules/nats/lib/nats.js:421:12)
mainflux-mqtt    |     at emitOne (events.js:77:13)
mainflux-mqtt    |     at Socket.emit (events.js:169:7)
mainflux-mqtt    |     at readableAddChunk (_stream_readable.js:146:16)
mainflux-mqtt    |     at Socket.Readable.push (_stream_readable.js:110:10)
mainflux-mqtt    |     at TCP.onread (net.js:523:20)
mainflux-mqtt    | 2017/01/16 10:59:18 Command exited with error: exit status 1
mainflux-mqtt exited with code 1
```

I tried the request with Postman (chrome extension) and got the same result. I have to restart the docker instance to get the mqtt up and running again. What might be the reason behind this? Thanks for all the help in advance.

**Comment by nmarcetic** [comment]
@hashin Thank you for reporting this one, we will check it ASAP. @darkodraskovic maybe related with nodejs version https://github.com/mainflux/mainflux-mqtt/blob/5a1818ad938c516d293f18255e74382662c46ca0/mainflux-mqtt.js#L60 http://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha 
In docker-compose version 4.x is defined , 6.9.4 is now LTS

**Comment by drasko** [comment]
@hashin can you please confirm you have adequate NodeJS version before we continue investigation.

**Comment by drasko** [comment]
@hashin can we close this one?

**Comment by hashin** [comment]
@drasko I am sorry I couldn't reply on time. I will test this out again and will comeback soon. Please bear with me. And thanks!

**Comment by drasko** [comment]
@hashin np. @nmarcetic can you please just spin a test on a fresh clone, tell us if everything is OK at your side?

**Comment by hashin** [comment]
@drasko @nmarcetic My nodejs version is 6.9.4. I just tested this out and the error haven't gone away. The error is exactly the same. Will it be the case that the docker setup is using another version instead of my system nodejs installation?

**Comment by drasko** [comment]
Argh: https://github.com/mainflux/mainflux-mqtt/blob/master/Dockerfile#L6

This must be bumped up!

**Comment by drasko** [comment]
@hashin we'll push the changes in a couple of hours and new MQTT server docker image will be ready on DockerHub with correct Node version. I'll give you a sign once it is there.

**Comment by drasko** [comment]
@hashin new version of NodeJS is used now: https://github.com/mainflux/mainflux-mqtt/blob/master/Dockerfile#L6

Can you please replace the docker image (I am not sure if pull will work, maybe `docker rmi` is needed) and tell us if it works now.

**Comment by hashin** [comment]
@drasko @nmarcetic I was a bit confused with docker, so I ended up removing all the images (with `docker rmi mainflux/mqtt` etc) and containers and then did `docker-compose rm` followed by a `docker-compose up`. But still the problem persists.

Is it that I am doing it wrong? Or is it something to do with docker?

**Comment by hashin** [comment]
To be sure, I did a `docker rmi mainflux/mainflux-mqtt` and then removed the container with `docker rm container-id`. Then I did a `docker pull mainflux/mainflux-mqtt` in which I got an output of `Status: Downloaded newer image for mainflux/mainflux-mqtt:latest`.

Then I did a `docker-compose rm` followed by a `docker-compose up`. And the error persists. Is there any other way of going about the issue? 

Thanks for your help. :)

**Comment by drasko** [comment]
@hashin I confirm the bug - you are sending the correct command, but something is wrong with the buffer. I am investigating it right now.

**Comment by drasko** [comment]
@hashin commit https://github.com/mainflux/mainflux-mqtt/commit/070043878ec905095b34701ea1677c087711e45a should fix the issue. Problem was in the message encoding format in the payload byte array - Go JSON decoder encodes/decodes byte arrays in Base64 format (as you can see here: https://golang.org/src/encoding/json/encode.go), while Aedes uses UTF-8 buffers by default.

**Comment by drasko** [comment]
Hello @hashin - is this working for you now? Can it be closed?

**Comment by hashin** [comment]
@drasco Sorry for my late reply. I tested it today and it is working fine. Thanks for the bug fix! I will close the issue.

Also, I have seen some small errors in the documentation and website. (Grammatical, link fixes etc) Can I send a pull request correcting them? :-)

**Comment by drasko** [comment]
@hashin thanks lot for the bug report and the test!

All the PRs are more than welcome!
