### ISSUE TITLE
not able to start using Docker compose on windows

### ISSUE THREAD

**Issue by akrv** [absmach/magistrala#77]
## Description of the problem or steps to reproduce
followed normal installation instructions for docker.
this is the last few lines of the output
there was no error from starting other containers
```
mainflux-core    |                 == Industrial IoT System ==
mainflux-core    |
mainflux-core    |                 Made with <3 by Mainflux Team
mainflux-core    | [w] http://mainflux.io
mainflux-core    | [t] @mainflux
mainflux-core    |
mainflux-core    | Magic happens on port 7070
mainflux-core    | [negroni] Started GET /
mainflux-core    | [negroni] Completed 404 Not Found in 72.1µs
mainflux-core    | [negroni] Started GET /favicon.ico
```

and then i get 404 error, what could the reason be?
## Specifications
PowerMac
Windows 10
Docker compose up command
### Version
latest git clonable version

**Comment by drasko** [comment]
From what I see you are trying to GET the unexisting resource - there is nothing at `GET /`. Look at Mainflux Core API reference: http://mainflux.io/api/ to discover the valid endpoints.

Try `GET /status` and tell us if that works.
