### ISSUE TITLE
mongodb-reader HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by renatomotorline** [absmach/magistrala#774]
Hi,

I execute the following commands:
```
docker-compose -f docker/docker-compose.yml up -d
docker-compose -f docker/addons/mongodb-reader/docker-compose.yml up -d
```
And after that, if I try to get a thing messages I get "HTTP/1.1 500 Internal Server Error".
If I try to get the messages of a thing with the token wrong or the channel id I get "HTTP/1.1 403 Forbidden".

Best regards.

**Comment by drasko** [comment]
@renatomotorline if you expect something to end up in the DB, you need to start a `Writer` service: https://mainflux.readthedocs.io/en/latest/storage/#writers

It will pick up messages from NATS and write them in MongoDB.

Regarding your problem with `Reader` - it might be some authorization issue. Do you have valid credentials (you need to provide `thing_token` provisioned for your app that reads messages)?

**Comment by renatomotorline** [comment]
Thanks @drasko, 

I just needed to start the Writer server and now it works fine.

Best regards.
