### ISSUE TITLE
Introduce API keys

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#778]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No
2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently there two entities in systems that are authenticated and authorized when accessing API or any of adapters: 

* User which is authX with JWT 
* Thing which is authX with thing key (bearer token) and authZ with thingID.

As a User I can :
* CRUD thing 
* CRUD channels 
* Connect thing to channel 

As I thing I can 
* I have access to all adapters so I can Send/Receive messages 

The problem arises when I want to build a third party app, consuming both provisioning API (used by a user) and adapters for messaging (used by things) or even just a provisioning API.

Let's say I want to consume provision API I don't have many options, except passing my user credentials like username/password or JWT (which have short expiration period 10h and it can't be changed)  to my custom application in order to do consume provisioning API. This is obviously a security risk and bad practice, especially because I can't change my credentials so if they are compromised (which is easy if you share it like this), I don't have a way to revoke them or change.

Another example wich addressing the same issue, let's say I have a custom app which list's all my things. I can send/receive messages and I can check message history (read messages from database). This means my custom app need all thing keys in order to do messaging or read messages. What if I have 1k things?

One more fact makes things more complicated when we are talking about custom apps or API consuming. Currently, the only thing can do messaging and the only user can do provisioning, we don't have a way to consume both API's (both provisioning and adapter's access) with same credentials/token. This makes building app's around Mainflux even harder.

Proposal: 

To make things simple and clean we can add API keys, which will be able to access both provision API and adapter's protocols. 
How it works,
As I user I can create API key, this key can be JWT (on creation request I can specify TTL) or our custom token, its a question of implementation, so let's forget it now.
I can create as much API keys as I want.
I can revoke/delete API key using HTTP API endpoint.
This key can do everything that I as I user can do + that any of my things can do (publish/subscribe to any channel). 
Those can be a simple slice of strings in user structure when authenticating with API key you send different Auth header so we can make a difference between JWT and API key or thing key and API key.  

In future when we introduce organizations #649 we can extend those API keys with permissions and access policies, so you can, for example, create API key which has permission to pub/sub to all channels and can update thing but can't delete it or create it. 
This is just an idea, but the point is to get API keys with access policies. Let's leave this for later.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must have!

**Comment by mteodor** [comment]
just to throw  some light on terminology

> API keys are for projects, authentication is for users
> Cloud Endpoints handles both API keys and authentication schemes, such as Firebase or Auth0. The main distinction between these two is:
> 
> API keys identify the calling project — the application or site — making the call to an API.
> 
> Authentication tokens identify a user — the person — that is using the app or site

https://cloud.google.com/endpoints/docs/openapi/when-why-api-key

**Comment by nmarcetic** [comment]
Good points @mteodor Thank you!

**Comment by drasko** [comment]
For the reference, here is how AT&T is appoaching the problem: https://m2x.att.com/developer/documentation/v2/overview#API-Keys

API key that can be used for messaging over the whole group of devices is a big risk, but I understand the importance. Additionally - when we have a device groups, this group will have only one key/token, so this problem can eventually be solved in that way.

Anyway, It would be also interesting to have inheritance with keys, i.e. chain of trust - something like NATS 2.0 did with Accounts and Users: https://medium.com/@KevinHoffman/introduction-to-nats-2-0-security-84098916d2

As mentioned in https://github.com/mainflux/mainflux/issues/377, Ory tools should be researched here (for policies).

@anovakovic01 researched [Ladon](https://github.com/ory/ladon) and [Keto](https://github.com/ory/keto), and concluded that they are very good candidates for this.

**Comment by nmarcetic** [comment]
Closed with #932
