### ISSUE TITLE
Getting Provisioning for the first time

### ISSUE THREAD

**Issue by ukicar** [absmach/magistrala#78]
I was using tutorial for running mainflux from here : http://mainflux.io/getting-started/#installation
Mainflux is running after "docker-compose up" but I can't get provisioning for device.

`macbook-pro-de-uros-2-1:~ ukicar$ curl -s -S -i -X POST -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:7070/devices | json | pygmentize -l json
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
Location: /devices/9bd13b96-5eaa-42ca-8b5b-1a8e835f9b07
Date: Thu, 13 Apr 2017 10:47:50 GMT
Content-Length: 0`

I'm not getting response from server, content-length is zero. Please help

**Comment by drasko** [comment]
Provisioning is working well, doc is wrong. Please refer to the https://github.com/mainflux/mainflux-core/issues/11
 
Apparently device 9bd13b96-5eaa-42ca-8b5b-1a8e835f9b07 was created successfully. You can do GET on `/devices` to verify.

I also advise you to use CLI - http://mainflux.io/cli/ - it will maybe be easier than curl ;).

I'll keep the bug open as a reminder to change the doc :).

**Comment by nmarcetic** [comment]
@ukicar  Can we close this one ?
