### ISSUE TITLE
Remove the year from the license comment

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#788]
Remove the year from the license comment. This should be done in order to simplify maintenance.

**Comment by drasko** [comment]
Use opportunity to condense them also:

```
//
// Copyright (c) 2019
// Mainflux
//
// SPDX-License-Identifier: Apache-2.0
//
```

should  become:

```
// Copyright (c) Mainflux
// SPDX-License-Identifier: Apache-2.0
```

Just to lines on the top, lean and as simple as possible.

**Comment by drasko** [comment]
Inspired by Libra: https://github.com/libra/libra/issues/20

**Comment by nwneisen** [comment]
I went ahead and got this done in #876.

**Comment by drasko** [comment]
Great initiative @nwneisen, thanks!
