### ISSUE TITLE
Length of an email validation 

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#798]
The email validation introduced with #795 has some problems.

According to the [rfc3696 section 3.](https://tools.ietf.org/html/rfc3696#section-3) the maximum length of an email address is A@B A(local part)=64 characters and B(domain part)=255 characters.
The minimal length is three because a valid email address has the form "a@b" and the smallest length for a and b is one.

The email user (the local part) and the host (the domain part) can also have non ASCII UTF-8 characters. These regex expressions will make them invalid.
Do we want to enable email addresses which have UTF-8 characters as well?

@mainflux/contributors any thoughts on this?

**Comment by nmarcetic** [comment]
@anovakovic01 @drasko What do you think ^?

**Comment by anovakovic01** [comment]
> According to the rfc3696 section 3. the maximum length of an email address is A@B A(local part)=64 characters and B(domain part)=255 characters.
The minimal length is three because a valid email address has the form "a@b" and the smallest length for a and b is one.

I agree that these boundaries should be fixed.

Regarding email addresses that have UTF-8, I think that we should support these too, but it doesn't have high priority.

**Comment by rudder-free** [comment]
Thanks, working on it.

**Comment by drasko** [comment]
@rudder-free any updates on this?

**Comment by rudder-free** [comment]
> @rudder-free any updates on this?

Apologies for the delays, I have done some ground work for this, understanding how utf-8 and emails relates to each other. I am about to approach coding it. But if someone wants to take a stab at it, please feel free.

**Comment by manuio** [comment]
@rudder-free any updates on this?

**Comment by manuio** [comment]
@rudder-free  would you like to re-take this one?

**Comment by filinvadim** [comment]
Sorry I can't wait.

**Comment by manuio** [comment]
@filinvadim thank you!

**Comment by filinvadim** [comment]
Despite the fact that my PR was not accepted for third-party reasons feel free to copy-paste my code and make another PR. Cheers!

**Comment by manuio** [comment]
@filinvadim Your PR was not accepted simply because you didn't want to resolve our remarks and decided that it was the moment to merge while the work left was doable in 5min.

**Comment by filinvadim** [comment]
@manuio i've just wanted emphasize difference between "contribution" and "working for free".

**Comment by manuio** [comment]
@filinvadim I understand the difference and we always appreciate any type of contribution, including yours.  However, we can't review depending on any external criteria. Otherwise it would be a mess to maintain this project.

I think that the work left can be done pretty fast. It would be a pity that you don't finish this PR and become contributor. There is no pressure, you can do it when you want and it would be normal if it takes some days. 

We would also understand that you don't want to continue and in any case we thank you for your code!

**Comment by filinvadim** [comment]
You take my heart away @manuio! It's already done.
I'm sorry if I was rude.

**Comment by manuio** [comment]
@filinvadim Glad to ear that and thank you for your understanding :) I'll reopen the issue right now.
I'll do a last review but keep in mind that at least one more maintainer must review this PR. Good luck and thank you!
