### ISSUE TITLE
Add default content type per channel

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#800]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Currently, Mainflux has support for content type as a part of a topic (in case of MQTT), or header value (HTTP and WS). Some adapters maybe don't have an easy way to override topics or pass content type. This is why I suggest that we add support for the default content type per channel. If there is no content type specified when sending messages, services can read default content type for the specified channel.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a nice-to-have feature.

**Comment by drasko** [comment]
After some discussions, @mainflux/maintainers agreed that the simplest approach to give CT information to Mainflux would be via headers and paths.
