### ISSUE TITLE
Add support for customizable normalization logic

### ISSUE THREAD

**Issue by anovakovic01** [absmach/magistrala#803]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
One should be able to provide a transformation script to the normalizer. Normalizer will load this script in runtime and apply it to the received messages. This script should return a transformed message and a list of subjects to which these should be published. In combination with #802 this will provide full support for custom message formats.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
If we're going to introduce #802, this is a must-have.

**Comment by anovakovic01** [comment]
For scripting, we can use [tengo](https://github.com/d5/tengo).

**Comment by drasko** [comment]
This is good idea, but in order to avoid code complication, Normalizer will stay as is - as Writers understand only SenML.

On the other hand this idea can be followed in a new microservice that would have a role of some Rules Engine.
