### ISSUE TITLE
MQTT  fails when numerous clients with bad creds try to publish

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#811]
**BUG REPORT**

1. What were you trying to achieve?
benchmark the mqtt

2. What are the expected results?
mqtt working properly

3. What are the received results?
mqtt fails

```
00000000\",\"redis_git_dirty\":\"0\",\"redis_build_id\":\"cbfa5816ce932578\",\"redis_mode\":\"standalone\",\"os\":\"Linux 4.15.0-54-generic x86_64\",\"arch_bits\":\
mainflux-mqtt   | <--- Last few GCs --->
mainflux-mqtt   | 
mainflux-mqtt   | [1:0x561dc049d800]    13937 ms: Mark-sweep 972.3 (1029.9) -> 972.3 (994.4) MB, 88.0 / 0.0 ms  (average mu = 0.863, current mu = 0.000) last resort GC in old space requested
mainflux-mqtt   | [1:0x561dc049d800]    14025 ms: Mark-sweep 972.3 (994.4) -> 972.3 (993.9) MB, 88.0 / 0.0 ms  (average mu = 0.751, current mu = 0.000) last resort GC in old space requested
mainflux-mqtt   | 
mainflux-mqtt   | 
mainflux-mqtt   | <--- JS stacktrace --->
mainflux-mqtt   | 
mainflux-mqtt   | ==== JS stack trace =========================================
mainflux-mqtt   | 
mainflux-mqtt   |     0: ExitFrame [pc: 0x5234825be1d]
mainflux-mqtt   |     1: StubFrame [pc: 0x52348214822]
mainflux-mqtt   |     2: StubFrame [pc: 0x5234853598e]
mainflux-mqtt   | Security context: 0x286e0c7f2229 <JSObject>
mainflux-mqtt   |     3: flatstr(aka flatstr) [0x2cf147b10579] [/node_modules/flatstr/index.js:11] [bytecode=0x8223e86ef71 offset=3](this=0x3c1799e826f1 <undefined>,s=0x08223e806581 <Very long string[637855849]>)
mainflux-mqtt   |     4: pinoWrite [0x3364a67ffdb9] [/node_modules/pino/pino.js:225] [bytecode=0x382f8962f919 ...
mainflux-mqtt   | 
mainflux-mqtt   | FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
mainflux-mqtt exited with code 137

```

4. What are the steps to reproduce the issue?
```
go get github.com/krylovsk/mqtt-benchmark 
mqtt-benchmark --broker tcp://xxx.xxx.xxx.xxx:1883 --count 1000 --size 100 --clients 1000 --qos 2 --format text --password="$KEY" --username="$THING" --topic="channels/$CH/messages/test"
```

5. In what environment did you encounter the issue?
client pc ubuntu 18.04
mainflux server DO machine ubuntu 18.04 RAM 2GB

6. Additional information you deem important:

**Comment by chombium** [comment]
Exit code 137 means that the process was sent a SIGKILL. Which means that the container was send a kill signal because it has reached the memory limit. 
We might have a memory leak in the authentication methods.

**Comment by nmarcetic** [comment]
This happens usually when you are dealing with large datasets, but in our case not sure what can cause this error, which pointing out of memory as @chombium said.

**Comment by chombium** [comment]
@nmarcetic yes, the problem is the default allowed memory in node (V8). I would say that the reason is the size of the dataset. [V8 gives the user 1.7GB per default](https://medium.com/tomincode/increasing-nodes-memory-337dfb1a60dd).

@mteodor you could eventually re-test this by allowing more memory to node with `NODE_OPTIONS=--max-old-space-size=SPACE_IN_MB`. 
Depending on how you start the mqtt server, you should change the startup command for the node mqtt server:
* [docker-compose](https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml#L228) add the following envvar (adjust the space if needed)
```
 NODE_OPTIONS:--max-old-space-size=4096
```
* [directly from the console](https://github.com/mainflux/mainflux/blame/master/mqtt/aedes/README.md#L77) add another envvar:
```
NODE_OPTIONS="--max-old-space-size=4096"
```
* run inside a docker container without docker-compose add the envvar with ` -e NODE_OPTIONS="--max-old-space-size=4096` to your docker run command. The command will be something like:
```
docker run -p 9000:9000 -e NODE_OPTIONS="--max-old-space-size=4096"  -d me/app
```

**Comment by chombium** [comment]
@nmarcetic @mteodor personally I would not raise the allowed memory in the configs by default as it depends on the use case: mqtt topics, message size and the deployment infrastructure. I would suggest that we test this and add the config changes to the docs, instead.

**Comment by nmarcetic** [comment]
@chombium Agree, make sense :+1:  In the mine time, We are testing VerneMQ integration.

**Comment by dborovcanin** [comment]
@mteodor I can confirm the issue and the solution @chombium proposed seems to be working. This scenario where many unauthorized clients try to connect to the broker simultaneously is unlikely to happen (DDOS should be handled elsewhere) and adding something like:
```yaml
NODE_OPTIONS: --max-old-space-size=8192
```
[here](https://github.com/mainflux/mainflux/blob/93d939ea521defea184b8f25e0b2a6aa6c0f0c19/docker/aedes.yml#L31) should solve it. I would keep it like it is, at least for now. If somebody else has this problem, the solution is offered in this issue. I'm closing the issue now but I'll add a label `wontfix`.

**Comment by chombium** [comment]
@dusanb94 I think that instead of searching and pointing to this issue whenever someone has this problem, we could add the config parameter in the dev guide, . I will prepare a PR for this.

**Comment by drasko** [comment]
Thanks @chombium.

I propose that we keep this issue open until your doc PR is merged, so please refer to it in the PR commit message.
