### ISSUE TITLE
Dead dependencies

### ISSUE THREAD

**Issue by tdestro** [absmach/magistrala#842]
Probably more where this came from, but 

github.com/influxdata/influxdb/client/v2
is nonexistant.

**Comment by drasko** [comment]
Is this in vendoring?

@1995parham is working on transition to Go modules, and this should be corrected in this PR as well.

**Comment by 1995parham** [comment]
I can run `go mod tidy` on my PR to remove all unused packages.

**Comment by 1995parham** [comment]
I have run the command, and the result is available on #840

**Comment by manuio** [comment]
Fixed here: https://github.com/mainflux/mainflux/pull/971
