### ISSUE TITLE
Reorganize files and directories to follow Go project layout recommendations

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#844]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Based on [Go project-layout](https://github.com/golang-standards/project-layout), we should reorganize internal file and directory organization.

Move Mainflux services in `/internal`. Also, move Swagger docs in `/api`.

We need to see what packages whold be imported by other apps, and move these in `/pkg`

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Should-have

**Comment by nmarcetic** [comment]
Duplicated #666
