### ISSUE TITLE
Add FOSSA badge for licensing

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#845]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

It would be good if `License` section in `README.md` could have a [FOSSA](https://fossa.com/) badge, similar to [goswagger](https://github.com/go-swagger/go-swagger#licensing).

This would allow us to understand on a glance number of dependencies and their licensing ([example](https://app.fossa.io/projects/git%2Bgithub.com%2Fgo-swagger%2Fgo-swagger/refs/branch/master/cf3fb25e7a4f340882908c5386ba4f22647e93da/preview)).

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

Nice-to-have

**Comment by nmarcetic** [comment]
@drasko What's the status of this?
