### ISSUE TITLE
Failed to pull mainflux/dashflux:latest container image

### ISSUE THREAD

**Issue by yhung124** [absmach/magistrala#847]
**BUG REPORT**

1. What were you trying to achieve?
Pull mainflux dashflux container image

2. What are the expected results?
Pull image successfully.

3. What are the received results?
```
$ docker pull mainflux/dashflux:latest
Error response from daemon: pull access denied for mainflux/dashflux, repository does not exist or may require 'docker login'
```

4. What are the steps to reproduce the issue?
 - Just execute `docker pull mainflux/dashflux:latest`

5. In what environment did you encounter the issue?
OSX 10.14.3
Docker client 18.09.2

6. Additional information you deem important:

**Comment by chombium** [comment]
Hi @yhung124, 
Dashfllux has been deprecated and replaced by `ui`. You can the docker image [here](https://hub.docker.com/r/mainflux/ui). Please update to the latest version and deploy `ui`. Feel free to open another issue if you experience any problems.
