### ISSUE TITLE
make: *** [cli] Error 1 / cannot find package 

### ISSUE THREAD

**Issue by wassim6975** [absmach/magistrala#854]
Hello everyone, 

I have a problem when I try to make cli because it cannot find the package but my mainflux is in /Users/local/go/src/

Can you help me please ?
(Sorry again for this issue) 

It's what I did before : 

MacBook-Air-de-wassim:mainflux wassim$ docker-compose -f docker/docker-compose.yml up -d
WARNING: Found orphan containers (mainflux-mqtt, mainflux-mqtt-redis) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
mainflux-things-db is up-to-date
mainflux-jaeger is up-to-date
mainflux-things-redis is up-to-date
mainflux-users-db is up-to-date
mainflux-es-redis is up-to-date
mainflux-nats is up-to-date
mainflux-ui is up-to-date
mainflux-users is up-to-date
mainflux-normalizer is up-to-date
mainflux-things is up-to-date
mainflux-ws is up-to-date
mainflux-coap is up-to-date
mainflux-http is up-to-date
mainflux-nginx is up-to-date
MacBook-Air-de-wassim:mainflux wassim$ 

And : 

MacBook-Air-de-wassim:mainflux wassim$ make cli
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -ldflags "-s -w" -o build/mainflux-cli cmd/cli/main.go
cmd/cli/main.go:13:2: cannot find package "github.com/mainflux/mainflux/cli" in any of:
	/Users/wassim/go/src/mainflux/vendor/github.com/mainflux/mainflux/cli (vendor tree)
	/usr/local/go/src/github.com/mainflux/mainflux/cli (from $GOROOT)
	/Users/wassim/go/src/github.com/mainflux/mainflux/cli (from $GOPATH)
cmd/cli/main.go:14:2: cannot find package "github.com/mainflux/mainflux/sdk/go" in any of:
	/Users/wassim/go/src/mainflux/vendor/github.com/mainflux/mainflux/sdk/go (vendor tree)
	/usr/local/go/src/github.com/mainflux/mainflux/sdk/go (from $GOROOT)
	/Users/wassim/go/src/github.com/mainflux/mainflux/sdk/go (from $GOPATH)
make: *** [cli] Error 1

Thank you guys :)

**Comment by drasko** [comment]
What is your `$GOPATH` set to?

Also, gig you `go get` Mainflux code or you cloned it just to `/Users/local/go/src/`. Putting it there is worng, you must respect Go conventions.

**Comment by wassim6975** [comment]
Hello,
My GOPATH is : 
MacBook-Air-de-wassim:go wassim$ go env GOPATH
/Users/wassimbenjabria/go

I followed the go conventions and I put my Mainflux code in /Users/wassim/go/src

**Comment by anovakovic01** [comment]
@wassim6975 Follow go convention and use paths that include repository and owner. This means that Mainflux should be here `/Users/wassim/go/src/github.com/mainflux/mainflux`. Also, GOPATH is set to `/Users/wassimbenjabria/go`. Based on your Mainflux location, I would say that your GOPATH should be set to `/Users/wassim/go` instead of the current value. Hope this helps.

**Comment by drasko** [comment]
Closing this one, please reopen if needed.

**Comment by wassim6975** [comment]
Thank you for help
