### ISSUE TITLE
Remove UI from the monorepo

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#856]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
There are a lot of opened UI issues/enhancements and Mainflux team has no capacity to maintain open-source UI. This should be community effort, and move to dedicated `community-ui` repo.

Mainflux Labs offers professional support for Dashflux UI (https://www.mainflux.com/iot-device-management.html), which is proprietary product written in Angular, so it is up to community to maintain Elm-based UI.
 
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must-have

**Comment by chombium** [comment]
This seem reasonable although there is a danger if there are no maintainers the project will be abandoned or that the ui will not follow the api changes in the services. It will be crucial that we regularly update the Swagger descriptions for the services and keep the API as stable as possible.
Maybe we can add this kind o test as a point to the #643 

Has already been decided how are we going to deliver the UI. Would it still be part of the main docker-compose and loaded as git submodule or it will be deployed as a separated deployment as the other docker addons(readers, writers, etc)?

**Comment by drasko** [comment]
@chombium we had internal discussions, and we decided to abandon for no w this idea of separating stuff from Monorepo until e2e is done.
