### ISSUE TITLE
adding metadata for the users

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#858]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

It would be good  to have possibility to add metadata for the user

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Nice to have

**Comment by anovakovic01** [comment]
Resolved by #861.
