### ISSUE TITLE
Update SDK by adding missing features

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#862]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   the existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
We need to add missing features like bootstrap, provision, etc,.. Thing to consider maybe is MQTT messaging as requested in #515 by wrapping paho client into new client which supports mTLS and all other Mainflux specific config options. 

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must have.

**Comment by drasko** [comment]
@nmarcetic I started to think that MQTT and other messaging should not really be part of our SDK, as we will use standard libs.

Paho lib for example has many options - no need that we re-create all of this. Let user use whatever he wants for messaging.

**Comment by nmarcetic** [comment]
@drasko I agree but there is a lot of options around paho MQTT client I was thinking maybe to wrap it and make your dev more comfortable (supporting mTLS and all other config options). We should think about.

**Comment by nmarcetic** [comment]
@drasko Yea, you are right. Let's NOT do this and leave freedom to use messaging as users want's. There are too much config and options that vary from the use case. We will just add extra code and complexity by wrapping the client.

**Comment by chombium** [comment]
@drasko, @nmarcetic I totally agree with you. The only thing that we should provide is good integration api and an example how to use it
