### ISSUE TITLE
Docker-compose version mismatch

### ISSUE THREAD

**Issue by exocode** [absmach/magistrala#871]
**BUG REPORT**

1. What were you trying to achieve?
Running docker-compose

`docker-compose -f docker/docker-compose.yml -f docker/addons/influxdb-reader/docker-compose.yml -f docker/addons/influxdb-writer/docker-compose.yml up`

2. What are the expected results?

spin up stack

3. What are the received results?

ERROR
```
Version mismatch: file ./docker/docker-compose.yml specifies version 3.7 but extension file ./docker/addons/influxdb-reader/docker-compose.yml uses version 3.0
```

4. What are the steps to reproduce the issue?
- `git clone git@github.com:mainflux/mainflux.git`
- `cd mainflux`
- `docker-compose -f docker/docker-compose.yml -f docker/addons/influxdb-reader/docker-compose.yml -f docker/addons/influxdb-writer/docker-compose.yml up`

- If I change the `docker-compose.yml` files to "3.7" I ran into next issues: 

(shortened)
```
mainflux-users     | {"level":"error","message":"Failed to connect to postgres: dial tcp 172.24.0.8:5432: connect: connection refused","ts":"2019-09-25T16:44:21.5808126Z"}
mainflux-jaeger    | {"level":"info","ts":1569429861.5657432,"caller":"grpc/clientconn.go:1139","msg":"grpc: addrConn.createTransport failed to connect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection refused\". Reconnecting...","system":"grpc","grpc_log":true}
mainflux-nginx     | nginx: [emerg] host not found in upstream "mqtt-adapter:8080" in /etc/nginx/snippets/mqtt-ws-upstream.conf:5
Exception in thread Thread-55:
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.38/containers/35c504e9245f5a6ddf339ccc158b6cb07bfdb2d13d309e4dd1b1beb9e3c17936/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 233, in watch_events
  File "compose/container.py", line 215, in attach_log_stream
  File "compose/container.py", line 307, in attach
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 61, in attach
  File "site-packages/docker/api/client.py", line 400, in _read_from_socket
  File "site-packages/docker/api/client.py", line 311, in _get_raw_response_socket
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 409 Client Error: Conflict ("b'container 35c504e9245f5a6ddf339ccc158b6cb07bfdb2d13d309e4dd1b1beb9e3c17936 is restarting, wait until the container is running'")

mainflux-nginx exited with code 1
```

5. In what environment did you encounter the issue?
Locally MacBook Pro

6. Additional information you deem important:

**Comment by drasko** [comment]
MQTT adapter is now started from a separate `.yaml` file, in order to allow for Aedes/Verne selection: https://github.com/mainflux/mainflux/blob/master/Makefile#L149

**Comment by exocode** [comment]
Maybe you overlooked it. I mean the versions of the docker-compose files are different, so Docker wont spin up: 

https://github.com/mainflux/mainflux/blob/5e3bb270a30cfebc8b8e889643003892fbda7a13/docker/docker-compose.yml#L4

https://github.com/mainflux/mainflux/blob/5e3bb270a30cfebc8b8e889643003892fbda7a13/docker/addons/influxdb-reader/docker-compose.yml#L8

So its complaining when I try to spin up mainflux via 

`docker-compose -f docker/docker-compose.yml -f docker/addons/influxdb-reader/docker-compose.yml -f docker/addons/influxdb-writer/docker-compose.yml up`

Isn't that the correct spin up process anymore? I had that in my `.bash_history` from a few months ago. 

Can you please provide a command to correctly docker-compose up **Mainflux** with **InfluxDB**?
