### ISSUE TITLE
Add Open Tracing to official documentation

### ISSUE THREAD

**Issue by nwneisen** [absmach/magistrala#875]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Add a chapter to the official documentation to show developers how to use Jaeger and OpenTracing with Mainflux.

This should include:

- A short explanation of Open Tracing and Jaeger
- How to launch and access the Jaeger UI from Mainflux
- How to configure Jaeger (enable/disable, set ports)
- A small example of _things_ and using Jaeger to find where they can be made more efficient.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
should-have

I plan to write this documentation myself.  As mentioned by @drasko in #787 , I am also working a blog post showing how to use Jaeger in Mainflux.  I plan to go over the Jaeger UI in this post but I don't believe it should be included in the Mainflux documentation.  The UI is covered by the Jaeger documentation and I think it would be extra work to keep a version in sync in the Mainflux documentation.

**Comment by drasko** [comment]
@nwneisen this sounds great. Thanks a lot!

**Comment by nwneisen** [comment]
First draft in #877.
