### ISSUE TITLE
CONTRIBUTING.md javasript style link is dead

### ISSUE THREAD

**Issue by chombium** [absmach/magistrala#88]
Hi,

I stared "playing" with Mainflux and when I was checking the [contributing guide](https://github.com/mainflux/mainflux/blame/master/CONTRIBUTING.md) and I saw that the link to the [javascript guidelines](https://github.com/mainflux/mainflux/blame/master/CONTRIBUTING.md#L50) is dead.

Can someone please take a look at it?

Suggestion:
For the JavaScript/Node projects the [pre-commit](https://www.npmjs.com/package/pre-commit) can be used to run a style check with automatic corrections and eventually the unit tests if there are any. This package attaches a pre-commit hook and blocks the committing to the repo if some of the checks  (run scripts) .
This way it can be assured that the code is always  well formatted, the unit tests pass, a linter is run and code coverage is checked. 

Best Regards,
Jovan

**Comment by drasko** [comment]
Fixed by https://github.com/mainflux/mainflux/commit/b7863f171ca03d724baba51d3cc1539ecee4c4c1

Thanks for reporting.
