### ISSUE TITLE
Update SDK tests

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#888]
Add missing SDK tests

**Comment by manuio** [comment]
Started here: https://github.com/mainflux/mainflux/issues/417

**Comment by dborovcanin** [comment]
Add missing tests to SDK and increase SDK test coverage.
You can check which functions are missing tests by running:
```
go test -timeout 30s -coverprofile=cover.out github.com/absmach/magistrala/pkg/sdk/go
go tool cover -html=cover.out 
```

**Comment by felixgateru** [comment]
- [x] bootstrap tests
- [x] certs tests
- [x] channels tests
- [x] consumers tests
- [x] domains tests
- [x] groups tests
- [x] health tests
- [x] invitations tests
- [x] message tests
- [x] things tests
- [x] token tests
- [x] users tests
- [x] journal

**Comment by dborovcanin** [comment]
Is this the only PR left: #2250 ?

**Comment by felixgateru** [comment]
> Is this the only PR left: #2250 ?

No, all the prs related to this issue have been merged. It can be closed
