### ISSUE TITLE
How to detect a thing (channel-id) currently connected to Mainflux?

### ISSUE THREAD

**Issue by whitetiger21022014** [absmach/magistrala#892]
**FEATURE REQUEST**
Hello,
I find all documents for 2 requirements as below, but I don't see any guide

1. Have channel-id, I need to know how to find is thing already connected to Mainflux
(if thing is connected to Mainflux, Server will send publish message (command) to thing?)

mainflux-cli and web api's document 
Retrieve a subset list of Channels connected to Thing
mainflux-cli things connections <thing_id> <user_auth_token>

Retrieve a subset list of Things connected to Channel
mainflux-cli channels connections <channel_id> <user_auth_token>

 mosquitto_sub -u 46c4d624-4603-4511-be4f-3c4e0e66b6bd -P c63c0704-e969-4386-895d-7ffd9a76d189 -t channels/0e3e3796-628f-49b8-a472-0cacbc20ffb1/messages -h localhost

Then I show 
./mainflux-cli channels connections 0e3e3796-628f-49b8-a472-0cacbc20ffb1 eyJhbGciOiJIUzI1NiI            sInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzE1NDEwMjQsImlhdCI6MTU3MTUwNTAyNCwiaXNzIjoibWFpbmZsdXgiLCJzdWIiOiJnaWZ0ZWRfbm9ldGhlckBlbWFpbC5jb20ifQ.p7fO1tUwpTZT9Cqg0U6CQWY            29SRicDlglShKnUcCETk

{
  "limit": 100,
  "offset": 0,
  "things": [
    {
      "id": "46c4d624-4603-4511-be4f-3c4e0e66b6bd",
      "key": "c63c0704-e969-4386-895d-7ffd9a76d189",
      "name": "d0"
    }
  ],
  "total": 1
}

**But I can't find any keyword as connected**

2. Is there one user have admin right or another option, that user can publish message to each thing via channel-id?

Thank for your project

**Comment by manuio** [comment]
@whitetiger21022014 Thank you for your remark. Looks like this is only documented in Swagger, here https://github.com/mainflux/mainflux/blob/master/things/swagger.yaml#L68 and here https://github.com/mainflux/mainflux/blob/master/things/swagger.yaml#L314
As you can see there 2 endpoints to fetch `Things connected to a Channel` and `Channels connected to a Thing`.

This endpoints are created here:
https://github.com/mainflux/mainflux/blob/master/things/api/things/http/transport.go#L83
https://github.com/mainflux/mainflux/blob/master/things/api/things/http/transport.go#L125

Would you like to take this issue and add this informations in the documentation?

**Comment by whitetiger21022014** [comment]
@manuio 
I think it is a misunderstanding

- I use command:  sub mosquitto_sub -u thing_id _111 -P thing_key_111 -t channels/channel_id_111/messages
- And thing_id_111 sub successfully via channel_id_111 to Mainflux

My question is:
**Is there any API for checking channel_id_111 is currently connected to Mainflux? it means how to know the channel_id_111 is ACTIVE SESSION/CONNECTED CONNECTION**

B/c I just tested two below APIs, and it does not show any difference when Subscribed and no_Subscribed
/channels/{chanId}/things
/things/{thingId}/channels

Thank for your team

**Comment by whitetiger21022014** [comment]
I think there is a feature (GetCID) in NATS

https://github.com/nats-io/nats.go/commit/3e169334621a00165c5ee135fcc8074eb009d44a

[ADDED] Ability to retrieve client ID from server currently connected to

"GetCID returns the client ID assigned by the server the client
is currently connected to. Note that the value would change if
client reconnects. Also, returned value may be 0 if connecting
to a server pre 1.2.0, which did not send the CID back to the
client."

**Comment by manuio** [comment]
@whitetiger21022014 Yes it was a misunderstanding. Looks like you want to know if your Things subscriptions still active. This is not related to NATS which is our internal messages bus.

IMO you should use your MQTT client to fix this issue. For example, if you are using Paho you can use the function [isConnected](https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttClient.html#isConnected--).

Please, close this issue if you agree.
