### ISSUE TITLE
Suddenly get error: unauthorized subscribe: 7 PERMISSION_DENIED

### ISSUE THREAD

**Issue by whitetiger21022014** [absmach/magistrala#893]
**BUG REPORT**

Several days I run command
docker-compose -f docker/docker-compose.yml -f docker/aedes.yml up
and do not have any problem with sub/pub

Error:
A. I run with below command
docker-compose -f docker/docker-compose.yml -f docker/aedes.yml -f docker/addons/mongodb-reader/docker-compose.yml up
sub/pub still works, then after 20-30 minutes

B Dashboard Web http://192.168.111.141/  (MAINFLUX : Dashboard, things, channels, connection, messages)
I access above web, click connect, disconnect,............

I got the errors as below report
I don't know A or B cause that error, but I guest B option caused that problem, or also token
If you need do any test or database, please let me know

**Detail report**
Test user: "email": "gifted_noether@email.com"
docker-compose -f docker/docker-compose.yml -f docker/aedes.yml up

**1. List user's things**
curl -s -S -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzE2MjE2MjUsImlhdCI6MTU3MTU4NTYyNSwiaXNzIjoibWFpbmZsdXgiLCJzdWIiOiJnaWZ0ZWRfbm9ldGhlckBlbWFpbC5jb20ifQ.A3go1oYMJbNEY3GxyNycBK4dJvj0Ie_-EhTuI3Ifavo" http://localhost/things | jq
{
  "total": 2,
  "offset": 0,
  "limit": 10,
  "things": [
    {
      "id": "46c4d624-4603-4511-be4f-3c4e0e66b6bd",
      "name": "d0",
      "key": "c63c0704-e969-4386-895d-7ffd9a76d189"
    },
    {
      "id": "7bbb8a3d-2f29-4858-b7a0-9e38f8c592b3",
      "name": "d1",
      "key": "a899c6f5-bc9a-4064-baa4-dea0d145c3bf"
    }
  ]
}

**2. List user's channels**
curl -s -S -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzE2MjE2MjUsImlhdCI6MTU3MTU4NTYyNSwiaXNzIjoibWFpbmZsdXgiLCJzdWIiOiJnaWZ0ZWRfbm9ldGhlckBlbWFpbC5jb20ifQ.A3go1oYMJbNEY3GxyNycBK4dJvj0Ie_-EhTuI3Ifavo" http://localhost/channels | jq
{
  "total": 2,
  "offset": 0,
  "limit": 10,
  "channels": [
    {
      "id": "0e3e3796-628f-49b8-a472-0cacbc20ffb1",
      "name": "c0"
    },
    {
      "id": "9f6fd50c-c538-4bed-810d-bb423f460a48",
      "name": "c1"
    }
  ]
}

**3. mosquitto_sub (or pub)**

mosquitto_sub -u 46c4d624-4603-4511-be4f-3c4e0e66b6bd -P c63c0704-e969-4386-895d-7ffd9a76d189 -t channels/0e3e3796-628f-49b8-a472-0cacbc20ffb1/messages -h localhost -d
Client mosqsub|29928-ubuntu18 sending CONNECT
Client mosqsub|29928-ubuntu18 received CONNACK
Client mosqsub|29928-ubuntu18 sending SUBSCRIBE (Mid: 1, Topic: channels/0e3e3796-628f-49b8-a472-0cacbc20ffb1/messages, QoS: 0)
Client mosqsub|29928-ubuntu18 sending CONNECT
Client mosqsub|29928-ubuntu18 received CONNACK
Client mosqsub|29928-ubuntu18 sending SUBSCRIBE (Mid: 2, Topic: channels/0e3e3796-628f-49b8-a472-0cacbc20ffb1/messages, QoS: 0)

**4. Mainflux' errors**

mainflux-things | {"level":"info","message":"Method identify for key c63c0704-e969-4386-895d-7ffd9a76d189 and thing 46c4d624-4603-4511-be4f-3c4e0e66b6bd took 546.475µs to complete without errors.","ts":"2019-10-20T15:50:57.103993934Z"}
mainflux-mqtt   | {"level":30,"time":1571586657105,"msg":"connected","pid":1,"hostname":"4b83855e917f","client":{"id":"mosqsub|29928-ubuntu18"},"v":1}
mainflux-things | {"level":"warn","message":"Method can_access for channel 0e3e3796-628f-49b8-a472-0cacbc20ffb1 and thing  took 3.523642ms to complete with error: missing or invalid credentials provided.","ts":"2019-10-20T15:50:57.115829749Z"}
mainflux-mqtt   | {"name":"mqtt","hostname":"4b83855e917f","pid":1,"level":40,"msg":"unauthorized subscribe: 7 PERMISSION_DENIED: missing or invalid credentials provided","time":"2019-10-20T15:50:57.116Z","v":0}
mainflux-mqtt   | {"level":40,"time":1571586657116,"msg":"7 PERMISSION_DENIED: missing or invalid credentials provided","pid":1,"hostname":"4b83855e917f","client":{"id":"mosqsub|29928-ubuntu18"},"type":"Error","stack":"Error: 7 PERMISSION_DENIED: missing or invalid credentials provided\n    at Object.exports.createStatusError (/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/node_modules/grpc/src/client_interceptors.js:847:24)","code":7,"metadata":{"_internal_repr":{},"flags":0},"details":"missing or invalid credentials provided","v":1}
mainflux-mqtt   | {"name":"mqtt","hostname":"4b83855e917f","pid":1,"level":40,"msg":"client error: client: mosqsub|29928-ubuntu18, error: 7 PERMISSION_DENIED: missing or invalid credentials provided","time":"2019-10-20T15:50:57.117Z","v":0}
mainflux-mqtt   | {"level":30,"time":1571586657117,"msg":"disconnected","pid":1,"hostname":"4b83855e917f","client":{"id":"mosqsub|29928-ubuntu18"},"v":1}
mainflux-mqtt   | {"name":"mqtt","hostname":"4b83855e917f","pid":1,"level":30,"msg":"disconnect client mosqsub|29928-ubuntu18","time":"2019-10-20T15:50:57.117Z","v":0}
mainflux-things | {"level":"info","message":"Method identify for key c63c0704-e969-4386-895d-7ffd9a76d189 and thing 46c4d624-4603-4511-be4f-3c4e0e66b6bd took 1.336251ms to complete without errors.","ts":"2019-10-20T15:50:58.13475892Z"}
mainflux-mqtt   | {"level":30,"time":1571586658139,"msg":"connected","pid":1,"hostname":"4b83855e917f","client":{"id":"mosqsub|29928-ubuntu18"},"v":1}
mainflux-things | {"level":"warn","message":"Method can_access for channel 0e3e3796-628f-49b8-a472-0cacbc20ffb1 and thing  took 8.144173ms to complete with error: missing or invalid credentials provided.","ts":"2019-10-20T15:50:58.1624744Z"}
mainflux-mqtt   | {"name":"mqtt","hostname":"4b83855e917f","pid":1,"level":40,"msg":"unauthorized subscribe: 7 PERMISSION_DENIED: missing or invalid credentials provided","time":"2019-10-20T15:50:58.163Z","v":0}
mainflux-mqtt   | {"level":40,"time":1571586658164,"msg":"7 PERMISSION_DENIED: missing or invalid credentials provided","pid":1,"hostname":"4b83855e917f","client":{"id":"mosqsub|29928-ubuntu18"},"type":"Error","stack":"Error: 7 PERMISSION_DENIED: missing or invalid credentials provided\n    at Object.exports.createStatusError (/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/node_modules/grpc/src/client_interceptors.js:847:24)","code":7,"metadata":{"_internal_repr":{},"flags":0},"details":"missing or invalid credentials provided","v":1}
mainflux-mqtt   | {"name":"mqtt","hostname":"4b83855e917f","pid":1,"level":40,"msg":"client error: client: mosqsub|29928-ubuntu18, error: 7 PERMISSION_DENIED: missing or invalid credentials provided","time":"2019-10-20T15:50:58.164Z","v":0}
mainflux-mqtt   | {"level":30,"time":1571586658165,"msg":"disconnected","pid":1,"hostname":"4b83855e917f","client":{"id":"mosqsub|29928-ubuntu18"},"v":1}
mainflux-mqtt   | {"name":"mqtt","hostname":"4b83855e917f","pid":1,"level":30,"msg":"disconnect client mosqsub|29928-ubuntu18","time":"2019-10-20T15:50:58.166Z","v":0}

And one time as below
mainflux-things   | {"level":"info","message":"Method identify for key c63c0704-e969-4386-895d-7ffd9a76d189 and thing 46c4d624-4603-4511-be4f-3c4e0e66b6bd took 241.302µs to complete without errors.","ts":"2019-10-20T13:38:17.100215171Z"}
mainflux-mqtt     | {"level":30,"time":1571578697100,"msg":"connected","pid":1,"hostname":"cddeb45ae05a","client":{"id":"mosqsub|12066-ubuntu18"},"v":1}

**mainflux-things-db | 2019-10-20 13:38:17.105 UTC [25] ERROR:  invalid input syntax for type uuid: "0e3b1"
mainflux-things-db | 2019-10-20 13:38:17.105 UTC [25] STATEMENT:  SELECT EXISTS (SELECT 1 FROM connections WHERE channel_id = $1 AND thing_id = $2);**
mainflux-mqtt     | {"name":"mqtt","hostname":"cddeb45ae05a","pid":1,"level":40,"msg":"unauthorized subscribe: 7 PERMISSION_DENIED: missing or invalid credentials provided","time":"2019-10-20T13:38:17.105Z","v":0}
mainflux-mqtt     | {"level":40,"time":1571578697105,"msg":"7 PERMISSION_DENIED: missing or invalid credentials provided","pid":1,"hostname":"cddeb45ae05a","client":{"id":"mosqsub|12066-ubuntu18"},"type":"Error","stack":"Error: 7 PERMISSION_DENIED: missing or invalid credentials provided\n    at Object.exports.createStatusError (/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/node_modules/grpc/src/client_interceptors.js:847:24)","code":7,"metadata":{"_internal_repr":{},"flags":0},"details":"missing or invalid credentials provided","v":1}
mainflux-mqtt     | {"name":"mqtt","hostname":"cddeb45ae05a","pid":1,"level":40,"msg":"client error: client: mosqsub|12066-ubuntu18, error: 7 PERMISSION_DENIED: missing or invalid credentials provided","time":"2019-10-20T13:38:17.105Z","v":0}
mainflux-mqtt     | {"level":30,"time":1571578697107,"msg":"disconnected","pid":1,"hostname":"cddeb45ae05a","client":{"id":"mosqsub|12066-ubuntu18"},"v":1}
mainflux-mqtt     | {"name":"mqtt","hostname":"cddeb45ae05a","pid":1,"level":30,"msg":"disconnect client mosqsub|12066-ubuntu18","time":"2019-10-20T13:38:17.107Z","v":0}
mainflux-things   | {"level":"warn","message":"Method can_access for channel 0e3b1 and thing  took 1.875865ms to complete with error: missing or invalid credentials provided.","ts":"2019-10-20T13:38:17.105232173Z"}

**Comment by whitetiger21022014** [comment]
And if I just created new user, I still got error: "7 PERMISSION_DENIED: missing or invalid credentials provided" as above
Thanks

**Comment by drasko** [comment]
Looks to me like your DB is corrupted.

Can you delete this DB and restart/reinitialize the system and see what happends.

Also, UI is not really maintained, it is very experimental. APIs should be used.

**Comment by whitetiger21022014** [comment]
@drasko it is my mistake, b/c I disconnect in dashboard (access control)
