### ISSUE TITLE
Example for checking active MQTT client connections

### ISSUE THREAD

**Issue by whitetiger21022014** [absmach/magistrala#900]
**FEATURE REQUEST**

This is not the problem, it is an example for checking active MQTT client connections
Diagram
Sensors (MQTT client for sub, like smart home) <----- Mainflux  <------- Controller (pub)

Before the controller sends command to sensor, we need to check the sensor's status
- But we can't use https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttClient.html#isConnected-- , it caused the sensor Subscribed and not-Subscribed via use same client-ID
- And MQTT broker does not support for that feature
 
So we need "retain and last-will" feature  as below, I tested and it works as expected
http://www.steves-internet-guide.com/checking-active-mqtt-client-connections/

But as you known, below script use 'publish' for on_connect with simple payload "1", and senML  makes warning in syslog when checking syntax

This is simple script will be useful for beginner, you can modify, and please close this issue

In the future, it will be good if Mainflux has feature like also accept JSON, because senML is suitable for sensor sending information to cloud, but sensor also receives command with JSON syntax

mqtt_paho_sensor_sub.py
https://gist.github.com/whitetiger21022014/a736a05841d0e39143f8d440488c4fe4

**Comment by nmarcetic** [comment]
@whitetiger21022014 You must use SenML ONLY when you use writers or readers, so when you persist messages in a database (as you said SenML is for measurements and we only persist measurements in DB). For other stuff as status etc... you can use JSON, binary or send whatever you want via MQTT (it will not be saved in Database).  

Btw we are working on Digital twin concept as [discibed here](https://github.com/mainflux/mainflux/issues/730) there is a [WIP pull request](https://github.com/mainflux/mainflux/pull/855), we are estimating 2-3 weeks. 
This concept will help you a lot with   this `Before the controller sends command to sensor, we need to check the sensor's status`
