### ISSUE TITLE
Consider Mainflux message updates

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#919]
**FEATURE REQUEST**
Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
existing issue, otherwise, proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently, the Mainflux uses two types of messages: RawMessage and Message. RawMessages are exchanged internally over NATS and they represent the main data carrier, while Messages represent standardized messages. Working on #780 and extracting Normalizer to the separate package made me think about Message. Message type represents nothing else but a SenML record that can be consumed on the message consumer side. The decision to move message normalization to the separate package that will be utilized by the consumer (see #915) results in Normalizer service to become optional. This also opens an opportunity to make the normalization process more generic and less dependent on SenML specification. We can expose Normalizer as an interface and provide basic SenML implementation, but also leave the space for implementing different standards or using a custom message format passed as RawMessage Payload. This also implies removing Messages from the root level and keep them in SenML normalizer. The proposed interface declaration would be:

```go
type Normalizer interface {
    Normalize(mainflux.RawMessage) (interface{}, error)
}
```
and package structure would be similar to readers and writers:
- normalizer
        - doc.go
        - normalizer.go // Normalizer interface
    - senml
         - normalizer.go // SenML normalizer impl
         - message.go // SenML message struct
    - other_specification
        - normalizer.go // Other_specification normalizer impl
        - message.go // Other_specification message
    - custom
        - normalizer.go // Custom normalizer impl
        - message.go // Custom message

We could also rename `RawMessage` to `Message`, which sounds more convenient to me.

Pros:
1. Simplification and unification of Message
2. Generic Normalization
3. Decoupling from SenML

Cons:
1. If you want to serialize messages to Protobuf from Normalizer, you'll need to write your `.proto` files and compile them, which some developers might find complex.

@mainflux/contributors What are your thoughts on this?

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

This is should-have.

**Comment by nmarcetic** [comment]
Fully agree. Also, this is must IMHO
 `We could also rename RawMessage to Message, which sounds more convenient to me.`

RawMessage is wrong naming, its not raw at all :) I agree with suggestion ^ It should be just Message (representing Mainflux Message not Raw msg).

**Comment by manuio** [comment]
I also fully agree

**Comment by drasko** [comment]
Agreed. Structure was initially called `MainfluxMessage` and I think this name represents better what it really is - internal Mainflux message.

With SenML out of the way, no need for current `Message` struct any more.

Also, in the case of generic processing we should think if `Normalizer` should be called like that - as for SenML normalization is separating one message array in several messages, but for other format maybe "processing" would be the better word?

**Comment by manuio** [comment]
@drasko `message-formatter`?

**Comment by drasko** [comment]
Not two words, please :)

**Comment by dborovcanin** [comment]
@manuio Formatter sounds OK to me. @mainflux/maintainers Thanks for the feedback.

**Comment by anovakovic01** [comment]
I agree with everything you wrote. Also, think about renaming `Message` to `SenMLMessage`, or something like that. Regarding `normalizer` rename, I think that it's ok even if we leave it as is. But if we need to rename it, we can call it `processor` or `transformer` (robot in disguise :wink:).

**Comment by dborovcanin** [comment]
`Transformer` is a better choice because` formatter` implies just a format change, usually without modifying the content. However, there is no reason to prevent content modifications here.
