### ISSUE TITLE
Fix MF_THINGS_AUTH_GRPC_PORT ENV var in protocol adapters' READMEs

### ISSUE THREAD

**Issue by drasko** [absmach/magistrala#921]
**BUG REPORT**

1. What were you trying to achieve?

2. What are the expected results?

README files of protocol adapter services should contain info about [MF_THINGS_AUTH_GRPC_PORT](https://github.com/mainflux/mainflux/blob/da4fc624400d5a5172b2bf91a06369e7ed3d5176/.env#L58) and not the `MF_THINGS_URL` which was replaced (additionaly, port was changed from `8181` to `8183`).

[This](https://github.com/mainflux/mainflux/blob/da4fc624400d5a5172b2bf91a06369e7ed3d5176/docker/docker-compose.yml#L209) also should be fixed as well as [default URL](https://github.com/mainflux/mainflux/blob/da4fc624400d5a5172b2bf91a06369e7ed3d5176/cmd/http/main.go#L40) to Things service for auth.

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

**Comment by manuio** [comment]
@drasko We could replace `MF_THINGS_URL` by `MF_THINGS_AUTH_GRPC_URL` and `MF_THINGS_AUTH_GRPC_PORT= things:8183` in `.env`
