### ISSUE TITLE
Add ABAC in messaging

### ISSUE THREAD

**Issue by nmarcetic** [absmach/magistrala#931]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
   No
2. Describe the feature you are requesting, as well as the possible use case(s) for it.
  Add [ABAC](https://en.wikipedia.org/wiki/Attribute-based_access_control) policies to messaging, using [Casbin](https://casbin.org). This impl should provide as with features to set read/write permissions on a channel. Permission is controlled via policy, which can be set by the channel owner.
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
should-have

**Comment by drasko** [comment]
This issue has been broken in two: https://github.com/mainflux/mainflux/issues/1346 and https://github.com/mainflux/mainflux/issues/1347

Closing this one.
