### ISSUE TITLE
Benchmarking tool - timing results look too high

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#949]
Average time for message delivery seem it is too high, don't know if it is just displayed in wrong units.

**Comment by manuio** [comment]
@mteodor any news about this one?

**Comment by mteodor** [comment]
lets see if  mzbench tool satisfies benchmarking  and then decide if we need to address this

**Comment by blokovi** [comment]
I didn't notice this issue while using mzbench, @mteodor can we close this?

**Comment by dborovcanin** [comment]
Since we're not able to reproduce this one with other tools, and due to inactivity, I'm closing it.
