### ISSUE TITLE
Runtime error in normalizer - CBOR SenML

### ISSUE THREAD

**Issue by ngale1965** [absmach/magistrala#950]
Publishing SenML/CBOR topic looking like `[{0: "TST", 4: true}]`  in CBOR diagnostic notation (`81 a2 00 63 54 53 54 04 f5`) causes runtime error in normalizer.
Fix me, but I am sure that the message conforms [RFC 8428](https://tools.ietf.org/html/rfc8428).  
```bash
mainflux-mqtt   | {"level":30,"time":1573140521695,"msg":"published","pid":1,"hostname":"34e546c4ae1a","client":{"id":"GlobalClient"},"message":{"topic":"channels/1531a2f3-5a2a-4404-a168-cad5ea289d4c/messages/ct/application_senml-cbor","qos":0,"retain":false},"v":1}
mainflux-normalizer | {"level":"warn","message":"Method normalize took 46.934µs to complete with error: cbor decode error [pos 3]: runtime error: index out of range [0] with length 0.","ts":"2019-11-07T15:28:41.695720118Z"}
```

On the other hand  the message encoded as
```bash
[{"n": "TST", "vb": true}]
81         # array(1)
A2         # map(2)
61         # text(1)
6E         # "n"
63         # text(3)
545354     #"TST"
62         # text(2)
7662       # "vb"
F5         # primitive(21)
```
is processed fine.
Seems there is RFC 8428 violation bug in https://github.com/cisco/senml + https://github.com/ugorji/go . See  "RFC 8428 (August 2018) Jennings, et al. Standards Track [Page 19]"

**Comment by dborovcanin** [comment]
@ngale1965 The pull request with the fix is sent to the SenML lib: https://github.com/cisco/senml/pull/23. Please have in mind that Normalizer service is removed as of #924 in favor of message normalization on the message consumer side.

**Comment by x448** [comment]
@dusanb94 If there's no response to your pull request, maybe this will help. 

I created [Disco SenML](https://github.com/x448/senml).  It's a debloated cisco/senml with bugfixes for issues that's been open for years.  Programs like senmlCat are 4 MB smaller.

It passes all unit tests from cisco/senml and I just tagged the [initial release](https://github.com/x448/senml/releases):
```
Disco SenML initial release on Nov 24, 2019.

Specific cisco/senml issues fixed in this release:

"CBOR does not encode or decode numeric field names cisco/senml #2" (2016).
"Base Value and Base Sum missing from the model cisco/senml #18" (2017).
"CBOR support uses go-codec which adds bloat to the binary cisco/senml #22" (2019).

Changes from cisco/senml (4d43ea8, Oct 10, 2019):

Compiled programs are each 4 MB smaller (senmlCat and senmlServer).
CBOR representation uses integers for labels, so it no longer violates SenML RFC 8428.
Missing Base Value and Base Sum are added to the model.
Fixed bad test data in unit tests and added new CBOR test using example from
SenML RFC 8428 so all unit tests pass.
Removed MessagePack feature for reasons cited in README.md.
Replaced ugorji/go with fxamacker/cbor v1.3.1.
Use Go modules and have at least one tagged release.
Require Go 1.12
Added name to LICENSE.
Updated README.md with new name "Disco SenML"
```
