### ISSUE TITLE
Does it have the founction of rule engine!?  

### ISSUE THREAD

**Issue by long0419** [absmach/magistrala#958]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?

2. What are the expected results?

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

**Comment by drasko** [comment]
Currently, Mainflux does not implement Rules Engine as a specific service.

Conditional data processing (rule engine) can be easily implemented on the applicative level. Just subscribe to Mainflux NATS and process data under the conditions you like. You can then re-publish data back to NATS if you want Writers to write them in DB.
