### ISSUE TITLE
Export service

### ISSUE THREAD

**Issue by mteodor** [absmach/magistrala#964]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

There is a requirement for service that runs on edge that is able to send messages to mainflux in cloud via MQTT, messages are received on localy ran NATS from some custom service or from mainflux that runs on edge.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by nmarcetic** [comment]
Closed with #961
