### ISSUE TITLE
Add list API Keys endpoint

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#969]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Add endpoint for listing User keys to the Auth service.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a must-have dfeature.

**Comment by drasko** [comment]
What's the status of this one?
