### ISSUE TITLE
Improve error handling in Auth service

### ISSUE THREAD

**Issue by dborovcanin** [absmach/magistrala#970]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
User Mainflux `errors` package to handle errors in the Auth service.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a must-have feature.

**Comment by drasko** [comment]
@dusanb94 @blokovi is this one finished?

**Comment by manuio** [comment]
@drasko looks like it's resolved here: https://github.com/mainflux/mainflux/pull/1105

**Comment by blokovi** [comment]
yes, this one is resolved with #1105
