### ISSUE TITLE
Grafana page timing out

### ISSUE THREAD

**Issue by sharmmoh1983** [absmach/magistrala#977]
I have installed Mainflux on DigitalOcean but the Grafana page is not opening

**Comment by manuio** [comment]
@sharmmoh1983 have you started the `influxdb-writer` service?

**Comment by sharmmoh1983** [comment]
@manuio I have got it started but now no messages are appearing on Grafana.
```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/query",
    "params": {
      "db": "mainflux",
      "q": "SELECT \"value\" FROM \"autogen\".\"messages\" WHERE (\"channel\" = '64310c75-5f6a-4a9c-87df-e879edd99ca2') AND time >= 1575464400000ms and time <= 1575550799999ms",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms"
  },
  "response": {
    "results": [
      {
        "statement_id": 0
      }
    ]
  }
}
```


`mosquitto_pub -u 38c72699-7e34-494a-acb2-b7dd52731215 -P 2f800626-02dc-4fc5-9a45-11d81382385a -t channels/64310c75-5f6a-4a9c-87df-e879edd99ca2/messages -h 165.22.242.198 -m '[{"bn":"name","bu":"A", "n": "voltage", "u": "V", "v": 120.1 }, { "n": "current", "t": -2, "v": 1.5 },{ "n": "current", "t": -1, "v": 1.6 }, { "n": "current", "t": 0, "v": 1.7 }]'`

**Comment by manuio** [comment]
@sharmmoh1983 From where are you accessing to the page?  From the UI or from `http://localhost:3001/`?

**Comment by sharmmoh1983** [comment]
I am running UI on DigitalOcean. I am accessing using cloud url :3001

**Comment by manuio** [comment]
@sharmmoh1983 did you configured this URL: `https://github.com/mainflux/ui/blob/master/src/environments/environment.prod.ts#L28`? 
If not you must set your cloud URL and rebuild a new UI image.

**Comment by sharmmoh1983** [comment]
@manuio I am able to access grafana and UI and also tokens using Cloud  IP . I am not able to figure out how to add this url while running docker compose? Also how can see messages I am sending to channel on Druflux UI 
Also UI always pops up message gateway not found ,how to add  gateways ?

**Comment by manuio** [comment]
@sharmmoh1983 UI still in development and will be stable for release 1.0.0. The Gateway message pops up because you don't have all needed services running. I'll add more docs soon to explain how the setup all services for UI.
For now you can maybe set  the grafana URL here: https://github.com/mainflux/ui/blob/master/src/environments/environment.prod.ts#L28 and build a new image with `make docker_ui`: https://github.com/mainflux/ui/blob/master/README.md

**Comment by sharmmoh1983** [comment]
@manuio  For running edge mainflux or gateways do we have to buy Mainflux device ?
Can we run edge/gateway binary on any Raspberry pi to connect to devices and Mainflux Cloud

**Comment by drasko** [comment]
@sharmmoh1983 no need for proprietary HW, [Agent](https://github.com/mainflux/agent) is HW agnostic.
