### ISSUE TITLE
When can it be compleately ready for deployment. 

### ISSUE THREAD

**Issue by indoriasnahil** [absmach/magistrala#978]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?

2. What are the expected results?

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

**Comment by drasko** [comment]
Question is not clear, Mainflux is used today in commercial products and professional. You need to contact [Mainflux Labs](https://www.mainflux.com/) for commercial inquiries.
