### ISSUE TITLE
Connect endpoint doesn't return errror if request lists are empty

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#982]
**BUG REPORT**

1. What were you trying to achieve?
Receive an error if /connect request lists of Things and Channels are empty 
2. What are the expected results?
Get an error
3. What are the received results?
Status Ok 
4. What are the steps to reproduce the issue?
Connect Things and Channels with empty lists

**Comment by manuio** [comment]
@nwneisen would you like to take this one? 

I think that the problem is here: https://github.com/mainflux/mainflux/blob/master/things/api/things/http/requests.go#L255
There is no check for empty arrays.

**Comment by nwneisen** [comment]
@manuio This is misleading. Even though `OK` is returned, nothing is actually happening. When the empty lists are iterated over they simply fall through.

I believe this should be handled by checking if either `ChannelIDs` or `ThingIDs` are empty. If one of them is, then a `things.ErrMalformedEntity` should be returned. I can  open a PR to make this change.

**Comment by nmarcetic** [comment]
Closed by #985
