### ISSUE TITLE
Fetch not connected Things or Channels

### ISSUE THREAD

**Issue by manuio** [absmach/magistrala#983]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Fetch Channels or Things IDs not connected to a given Thing or Channel.
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
nice-to-have

**Comment by Nitheshnithu121** [comment]
Can any one please tell me how to send the data from iot sensors to mainflux through esp8266 wifi module with the help of code example please please

**Comment by mteodor** [comment]
@Nitheshnithu121 have you checked this https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino
I haven't played with that exact hardware but that seems like a code that could work
you would only have to use method with username and password here
https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino#L88 - where username is thing_id and password is thing_key .
Topics for publish and subscribe would have to look like
`channels/<channel_id>/messages` - where channel_id is connected to thing that you use for connecting.

**Comment by drasko** [comment]
@Nitheshnithu121 @mteodor plase spamming this thread it is completely unrelated to ESP8266. Open new issues if needed.

**Comment by manuio** [comment]
Documentation updated here: https://github.com/mainflux/docs/pull/43

**Comment by manuio** [comment]
Implemented on the UI here: https://github.com/mainflux/ui/pull/104
