### ISSUE TITLE
mainflux/users

### ISSUE THREAD

**Issue by snahil** [absmach/magistrala#987]
After the registration of the user and password the login is not working for the latest update 

sha256:27e377cf6ecbaa9789d048796dea179cd99f112a2c7ecfa04bab2ad5b8839ce7

**Comment by dborovcanin** [comment]
@snahil Can you, please, fill the issue template properly? This report does not give us any meaningful information.

**Comment by snahil** [comment]
I am using ma mainflux release 0.9 ,  while i am running "docker-compose.yml" for the container to be started for the services and mapping which is manage internally and pulling the latest image from the "docker-hub" but the most resent update "sha256:27e377cf6ecbaa9789d048796dea179cd99f112a2c7ecfa04bab2ad5b8839ce7" have a issue that after the registration of the user through mainflux web interface, i receive a successful conformation for it as a code of "200", but when i am login using the same id , it is unable to connect with the  data base .

after changing the "sha256:27e377cf6ecbaa9789d048796dea179cd99f112a2c7ecfa04bab2ad5b8839ce7" to "sha256:e89f5258cf230617ba91bb5b3a3097e9788b5c361772fe4b862bb3ba50ddbd44" i am able to login. as their  config issue with the latest images , i have also tested the latest image with multiple servers but the result is same

**Comment by drasko** [comment]
Please try CLI or curl. If this works, then open an issue in the `mainflux/ui`, because this looks like UI issue.
